// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: inspect.proto

package inspect

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "github.com/micro/go-api/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Inspect service

type InspectService interface {
	List(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error)
	AppDetail(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error)
	TagDetail(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error)
}

type inspectService struct {
	c    client.Client
	name string
}

func NewInspectService(name string, c client.Client) InspectService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "inspect"
	}
	return &inspectService{
		c:    c,
		name: name,
	}
}

func (c *inspectService) List(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error) {
	req := c.c.NewRequest(c.name, "Inspect.List", in)
	out := new(proto1.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inspectService) AppDetail(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error) {
	req := c.c.NewRequest(c.name, "Inspect.AppDetail", in)
	out := new(proto1.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inspectService) TagDetail(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error) {
	req := c.c.NewRequest(c.name, "Inspect.TagDetail", in)
	out := new(proto1.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Inspect service

type InspectHandler interface {
	List(context.Context, *proto1.Request, *proto1.Response) error
	AppDetail(context.Context, *proto1.Request, *proto1.Response) error
	TagDetail(context.Context, *proto1.Request, *proto1.Response) error
}

func RegisterInspectHandler(s server.Server, hdlr InspectHandler, opts ...server.HandlerOption) error {
	type inspect interface {
		List(ctx context.Context, in *proto1.Request, out *proto1.Response) error
		AppDetail(ctx context.Context, in *proto1.Request, out *proto1.Response) error
		TagDetail(ctx context.Context, in *proto1.Request, out *proto1.Response) error
	}
	type Inspect struct {
		inspect
	}
	h := &inspectHandler{hdlr}
	return s.Handle(s.NewHandler(&Inspect{h}, opts...))
}

type inspectHandler struct {
	InspectHandler
}

func (h *inspectHandler) List(ctx context.Context, in *proto1.Request, out *proto1.Response) error {
	return h.InspectHandler.List(ctx, in, out)
}

func (h *inspectHandler) AppDetail(ctx context.Context, in *proto1.Request, out *proto1.Response) error {
	return h.InspectHandler.AppDetail(ctx, in, out)
}

func (h *inspectHandler) TagDetail(ctx context.Context, in *proto1.Request, out *proto1.Response) error {
	return h.InspectHandler.TagDetail(ctx, in, out)
}
