// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nodemanager.proto

package nodemanager

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetApiserverVersionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetApiserverVersionRequest) Reset()         { *m = GetApiserverVersionRequest{} }
func (m *GetApiserverVersionRequest) String() string { return proto.CompactTextString(m) }
func (*GetApiserverVersionRequest) ProtoMessage()    {}
func (*GetApiserverVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{0}
}

func (m *GetApiserverVersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApiserverVersionRequest.Unmarshal(m, b)
}
func (m *GetApiserverVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApiserverVersionRequest.Marshal(b, m, deterministic)
}
func (m *GetApiserverVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApiserverVersionRequest.Merge(m, src)
}
func (m *GetApiserverVersionRequest) XXX_Size() int {
	return xxx_messageInfo_GetApiserverVersionRequest.Size(m)
}
func (m *GetApiserverVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApiserverVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetApiserverVersionRequest proto.InternalMessageInfo

type GetApiserverVersionResponse struct {
	GitVersion           string   `protobuf:"bytes,1,opt,name=GitVersion,proto3" json:"GitVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetApiserverVersionResponse) Reset()         { *m = GetApiserverVersionResponse{} }
func (m *GetApiserverVersionResponse) String() string { return proto.CompactTextString(m) }
func (*GetApiserverVersionResponse) ProtoMessage()    {}
func (*GetApiserverVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{1}
}

func (m *GetApiserverVersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApiserverVersionResponse.Unmarshal(m, b)
}
func (m *GetApiserverVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApiserverVersionResponse.Marshal(b, m, deterministic)
}
func (m *GetApiserverVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApiserverVersionResponse.Merge(m, src)
}
func (m *GetApiserverVersionResponse) XXX_Size() int {
	return xxx_messageInfo_GetApiserverVersionResponse.Size(m)
}
func (m *GetApiserverVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApiserverVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetApiserverVersionResponse proto.InternalMessageInfo

func (m *GetApiserverVersionResponse) GetGitVersion() string {
	if m != nil {
		return m.GitVersion
	}
	return ""
}

type GetMasterStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMasterStatusRequest) Reset()         { *m = GetMasterStatusRequest{} }
func (m *GetMasterStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetMasterStatusRequest) ProtoMessage()    {}
func (*GetMasterStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{2}
}

func (m *GetMasterStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMasterStatusRequest.Unmarshal(m, b)
}
func (m *GetMasterStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMasterStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetMasterStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMasterStatusRequest.Merge(m, src)
}
func (m *GetMasterStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetMasterStatusRequest.Size(m)
}
func (m *GetMasterStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMasterStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMasterStatusRequest proto.InternalMessageInfo

type GetMasterStatusResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMasterStatusResponse) Reset()         { *m = GetMasterStatusResponse{} }
func (m *GetMasterStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetMasterStatusResponse) ProtoMessage()    {}
func (*GetMasterStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{3}
}

func (m *GetMasterStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMasterStatusResponse.Unmarshal(m, b)
}
func (m *GetMasterStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMasterStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetMasterStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMasterStatusResponse.Merge(m, src)
}
func (m *GetMasterStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetMasterStatusResponse.Size(m)
}
func (m *GetMasterStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMasterStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMasterStatusResponse proto.InternalMessageInfo

type GetClusterCpuRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClusterCpuRequest) Reset()         { *m = GetClusterCpuRequest{} }
func (m *GetClusterCpuRequest) String() string { return proto.CompactTextString(m) }
func (*GetClusterCpuRequest) ProtoMessage()    {}
func (*GetClusterCpuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{4}
}

func (m *GetClusterCpuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterCpuRequest.Unmarshal(m, b)
}
func (m *GetClusterCpuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterCpuRequest.Marshal(b, m, deterministic)
}
func (m *GetClusterCpuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterCpuRequest.Merge(m, src)
}
func (m *GetClusterCpuRequest) XXX_Size() int {
	return xxx_messageInfo_GetClusterCpuRequest.Size(m)
}
func (m *GetClusterCpuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterCpuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterCpuRequest proto.InternalMessageInfo

type GetClusterCpuResponse struct {
	CPU                  int32    `protobuf:"varint,1,opt,name=CPU,proto3" json:"CPU,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClusterCpuResponse) Reset()         { *m = GetClusterCpuResponse{} }
func (m *GetClusterCpuResponse) String() string { return proto.CompactTextString(m) }
func (*GetClusterCpuResponse) ProtoMessage()    {}
func (*GetClusterCpuResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{5}
}

func (m *GetClusterCpuResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterCpuResponse.Unmarshal(m, b)
}
func (m *GetClusterCpuResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterCpuResponse.Marshal(b, m, deterministic)
}
func (m *GetClusterCpuResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterCpuResponse.Merge(m, src)
}
func (m *GetClusterCpuResponse) XXX_Size() int {
	return xxx_messageInfo_GetClusterCpuResponse.Size(m)
}
func (m *GetClusterCpuResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterCpuResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterCpuResponse proto.InternalMessageInfo

func (m *GetClusterCpuResponse) GetCPU() int32 {
	if m != nil {
		return m.CPU
	}
	return 0
}

type GetClusterMemoryRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClusterMemoryRequest) Reset()         { *m = GetClusterMemoryRequest{} }
func (m *GetClusterMemoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetClusterMemoryRequest) ProtoMessage()    {}
func (*GetClusterMemoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{6}
}

func (m *GetClusterMemoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterMemoryRequest.Unmarshal(m, b)
}
func (m *GetClusterMemoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterMemoryRequest.Marshal(b, m, deterministic)
}
func (m *GetClusterMemoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterMemoryRequest.Merge(m, src)
}
func (m *GetClusterMemoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetClusterMemoryRequest.Size(m)
}
func (m *GetClusterMemoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterMemoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterMemoryRequest proto.InternalMessageInfo

type GetClusterMemoryResponse struct {
	Memory               int32    `protobuf:"varint,1,opt,name=Memory,proto3" json:"Memory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClusterMemoryResponse) Reset()         { *m = GetClusterMemoryResponse{} }
func (m *GetClusterMemoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetClusterMemoryResponse) ProtoMessage()    {}
func (*GetClusterMemoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{7}
}

func (m *GetClusterMemoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterMemoryResponse.Unmarshal(m, b)
}
func (m *GetClusterMemoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterMemoryResponse.Marshal(b, m, deterministic)
}
func (m *GetClusterMemoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterMemoryResponse.Merge(m, src)
}
func (m *GetClusterMemoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetClusterMemoryResponse.Size(m)
}
func (m *GetClusterMemoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterMemoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterMemoryResponse proto.InternalMessageInfo

func (m *GetClusterMemoryResponse) GetMemory() int32 {
	if m != nil {
		return m.Memory
	}
	return 0
}

type GetTotalPodNumberRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTotalPodNumberRequest) Reset()         { *m = GetTotalPodNumberRequest{} }
func (m *GetTotalPodNumberRequest) String() string { return proto.CompactTextString(m) }
func (*GetTotalPodNumberRequest) ProtoMessage()    {}
func (*GetTotalPodNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{8}
}

func (m *GetTotalPodNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTotalPodNumberRequest.Unmarshal(m, b)
}
func (m *GetTotalPodNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTotalPodNumberRequest.Marshal(b, m, deterministic)
}
func (m *GetTotalPodNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTotalPodNumberRequest.Merge(m, src)
}
func (m *GetTotalPodNumberRequest) XXX_Size() int {
	return xxx_messageInfo_GetTotalPodNumberRequest.Size(m)
}
func (m *GetTotalPodNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTotalPodNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTotalPodNumberRequest proto.InternalMessageInfo

type GetTotalPodNumberResponse struct {
	PodNumber            int32    `protobuf:"varint,1,opt,name=PodNumber,proto3" json:"PodNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTotalPodNumberResponse) Reset()         { *m = GetTotalPodNumberResponse{} }
func (m *GetTotalPodNumberResponse) String() string { return proto.CompactTextString(m) }
func (*GetTotalPodNumberResponse) ProtoMessage()    {}
func (*GetTotalPodNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{9}
}

func (m *GetTotalPodNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTotalPodNumberResponse.Unmarshal(m, b)
}
func (m *GetTotalPodNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTotalPodNumberResponse.Marshal(b, m, deterministic)
}
func (m *GetTotalPodNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTotalPodNumberResponse.Merge(m, src)
}
func (m *GetTotalPodNumberResponse) XXX_Size() int {
	return xxx_messageInfo_GetTotalPodNumberResponse.Size(m)
}
func (m *GetTotalPodNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTotalPodNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTotalPodNumberResponse proto.InternalMessageInfo

func (m *GetTotalPodNumberResponse) GetPodNumber() int32 {
	if m != nil {
		return m.PodNumber
	}
	return 0
}

type GetNetworkComponentRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNetworkComponentRequest) Reset()         { *m = GetNetworkComponentRequest{} }
func (m *GetNetworkComponentRequest) String() string { return proto.CompactTextString(m) }
func (*GetNetworkComponentRequest) ProtoMessage()    {}
func (*GetNetworkComponentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{10}
}

func (m *GetNetworkComponentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNetworkComponentRequest.Unmarshal(m, b)
}
func (m *GetNetworkComponentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNetworkComponentRequest.Marshal(b, m, deterministic)
}
func (m *GetNetworkComponentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNetworkComponentRequest.Merge(m, src)
}
func (m *GetNetworkComponentRequest) XXX_Size() int {
	return xxx_messageInfo_GetNetworkComponentRequest.Size(m)
}
func (m *GetNetworkComponentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNetworkComponentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNetworkComponentRequest proto.InternalMessageInfo

type NetworkComponent struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkComponent) Reset()         { *m = NetworkComponent{} }
func (m *NetworkComponent) String() string { return proto.CompactTextString(m) }
func (*NetworkComponent) ProtoMessage()    {}
func (*NetworkComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{11}
}

func (m *NetworkComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkComponent.Unmarshal(m, b)
}
func (m *NetworkComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkComponent.Marshal(b, m, deterministic)
}
func (m *NetworkComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkComponent.Merge(m, src)
}
func (m *NetworkComponent) XXX_Size() int {
	return xxx_messageInfo_NetworkComponent.Size(m)
}
func (m *NetworkComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkComponent.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkComponent proto.InternalMessageInfo

func (m *NetworkComponent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NetworkComponent) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetNetworkComponentResponse struct {
	NetworkComponent     *NetworkComponent `protobuf:"bytes,1,opt,name=NetworkComponent,proto3" json:"NetworkComponent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetNetworkComponentResponse) Reset()         { *m = GetNetworkComponentResponse{} }
func (m *GetNetworkComponentResponse) String() string { return proto.CompactTextString(m) }
func (*GetNetworkComponentResponse) ProtoMessage()    {}
func (*GetNetworkComponentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{12}
}

func (m *GetNetworkComponentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNetworkComponentResponse.Unmarshal(m, b)
}
func (m *GetNetworkComponentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNetworkComponentResponse.Marshal(b, m, deterministic)
}
func (m *GetNetworkComponentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNetworkComponentResponse.Merge(m, src)
}
func (m *GetNetworkComponentResponse) XXX_Size() int {
	return xxx_messageInfo_GetNetworkComponentResponse.Size(m)
}
func (m *GetNetworkComponentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNetworkComponentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNetworkComponentResponse proto.InternalMessageInfo

func (m *GetNetworkComponentResponse) GetNetworkComponent() *NetworkComponent {
	if m != nil {
		return m.NetworkComponent
	}
	return nil
}

type GetDNSComponentRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDNSComponentRequest) Reset()         { *m = GetDNSComponentRequest{} }
func (m *GetDNSComponentRequest) String() string { return proto.CompactTextString(m) }
func (*GetDNSComponentRequest) ProtoMessage()    {}
func (*GetDNSComponentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{13}
}

func (m *GetDNSComponentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDNSComponentRequest.Unmarshal(m, b)
}
func (m *GetDNSComponentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDNSComponentRequest.Marshal(b, m, deterministic)
}
func (m *GetDNSComponentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDNSComponentRequest.Merge(m, src)
}
func (m *GetDNSComponentRequest) XXX_Size() int {
	return xxx_messageInfo_GetDNSComponentRequest.Size(m)
}
func (m *GetDNSComponentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDNSComponentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDNSComponentRequest proto.InternalMessageInfo

type DNSComponent struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DNSComponent) Reset()         { *m = DNSComponent{} }
func (m *DNSComponent) String() string { return proto.CompactTextString(m) }
func (*DNSComponent) ProtoMessage()    {}
func (*DNSComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{14}
}

func (m *DNSComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DNSComponent.Unmarshal(m, b)
}
func (m *DNSComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DNSComponent.Marshal(b, m, deterministic)
}
func (m *DNSComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DNSComponent.Merge(m, src)
}
func (m *DNSComponent) XXX_Size() int {
	return xxx_messageInfo_DNSComponent.Size(m)
}
func (m *DNSComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_DNSComponent.DiscardUnknown(m)
}

var xxx_messageInfo_DNSComponent proto.InternalMessageInfo

func (m *DNSComponent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DNSComponent) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetDNSComponentResponse struct {
	DNSComponent         *DNSComponent `protobuf:"bytes,1,opt,name=DNSComponent,proto3" json:"DNSComponent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetDNSComponentResponse) Reset()         { *m = GetDNSComponentResponse{} }
func (m *GetDNSComponentResponse) String() string { return proto.CompactTextString(m) }
func (*GetDNSComponentResponse) ProtoMessage()    {}
func (*GetDNSComponentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{15}
}

func (m *GetDNSComponentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDNSComponentResponse.Unmarshal(m, b)
}
func (m *GetDNSComponentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDNSComponentResponse.Marshal(b, m, deterministic)
}
func (m *GetDNSComponentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDNSComponentResponse.Merge(m, src)
}
func (m *GetDNSComponentResponse) XXX_Size() int {
	return xxx_messageInfo_GetDNSComponentResponse.Size(m)
}
func (m *GetDNSComponentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDNSComponentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDNSComponentResponse proto.InternalMessageInfo

func (m *GetDNSComponentResponse) GetDNSComponent() *DNSComponent {
	if m != nil {
		return m.DNSComponent
	}
	return nil
}

type GetMonitorComponentRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMonitorComponentRequest) Reset()         { *m = GetMonitorComponentRequest{} }
func (m *GetMonitorComponentRequest) String() string { return proto.CompactTextString(m) }
func (*GetMonitorComponentRequest) ProtoMessage()    {}
func (*GetMonitorComponentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{16}
}

func (m *GetMonitorComponentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMonitorComponentRequest.Unmarshal(m, b)
}
func (m *GetMonitorComponentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMonitorComponentRequest.Marshal(b, m, deterministic)
}
func (m *GetMonitorComponentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMonitorComponentRequest.Merge(m, src)
}
func (m *GetMonitorComponentRequest) XXX_Size() int {
	return xxx_messageInfo_GetMonitorComponentRequest.Size(m)
}
func (m *GetMonitorComponentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMonitorComponentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMonitorComponentRequest proto.InternalMessageInfo

type MonitorComponent struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MonitorComponent) Reset()         { *m = MonitorComponent{} }
func (m *MonitorComponent) String() string { return proto.CompactTextString(m) }
func (*MonitorComponent) ProtoMessage()    {}
func (*MonitorComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{17}
}

func (m *MonitorComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorComponent.Unmarshal(m, b)
}
func (m *MonitorComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorComponent.Marshal(b, m, deterministic)
}
func (m *MonitorComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorComponent.Merge(m, src)
}
func (m *MonitorComponent) XXX_Size() int {
	return xxx_messageInfo_MonitorComponent.Size(m)
}
func (m *MonitorComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorComponent.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorComponent proto.InternalMessageInfo

func (m *MonitorComponent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MonitorComponent) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetMonitorComponentResponse struct {
	MonitorComponent     *MonitorComponent `protobuf:"bytes,1,opt,name=MonitorComponent,proto3" json:"MonitorComponent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetMonitorComponentResponse) Reset()         { *m = GetMonitorComponentResponse{} }
func (m *GetMonitorComponentResponse) String() string { return proto.CompactTextString(m) }
func (*GetMonitorComponentResponse) ProtoMessage()    {}
func (*GetMonitorComponentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{18}
}

func (m *GetMonitorComponentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMonitorComponentResponse.Unmarshal(m, b)
}
func (m *GetMonitorComponentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMonitorComponentResponse.Marshal(b, m, deterministic)
}
func (m *GetMonitorComponentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMonitorComponentResponse.Merge(m, src)
}
func (m *GetMonitorComponentResponse) XXX_Size() int {
	return xxx_messageInfo_GetMonitorComponentResponse.Size(m)
}
func (m *GetMonitorComponentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMonitorComponentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMonitorComponentResponse proto.InternalMessageInfo

func (m *GetMonitorComponentResponse) GetMonitorComponent() *MonitorComponent {
	if m != nil {
		return m.MonitorComponent
	}
	return nil
}

type GetNodesRequest struct {
	Label                string   `protobuf:"bytes,1,opt,name=Label,proto3" json:"Label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodesRequest) Reset()         { *m = GetNodesRequest{} }
func (m *GetNodesRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodesRequest) ProtoMessage()    {}
func (*GetNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{19}
}

func (m *GetNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodesRequest.Unmarshal(m, b)
}
func (m *GetNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodesRequest.Marshal(b, m, deterministic)
}
func (m *GetNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodesRequest.Merge(m, src)
}
func (m *GetNodesRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodesRequest.Size(m)
}
func (m *GetNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodesRequest proto.InternalMessageInfo

func (m *GetNodesRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type Node struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	Cpu                  int32    `protobuf:"varint,3,opt,name=Cpu,proto3" json:"Cpu,omitempty"`
	Memory               int32    `protobuf:"varint,4,opt,name=Memory,proto3" json:"Memory,omitempty"`
	PodNumber            int32    `protobuf:"varint,5,opt,name=PodNumber,proto3" json:"PodNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{20}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Node) GetCpu() int32 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *Node) GetMemory() int32 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *Node) GetPodNumber() int32 {
	if m != nil {
		return m.PodNumber
	}
	return 0
}

type GetNodesResponse struct {
	Node                 []*Node  `protobuf:"bytes,1,rep,name=Node,proto3" json:"Node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodesResponse) Reset()         { *m = GetNodesResponse{} }
func (m *GetNodesResponse) String() string { return proto.CompactTextString(m) }
func (*GetNodesResponse) ProtoMessage()    {}
func (*GetNodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{21}
}

func (m *GetNodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodesResponse.Unmarshal(m, b)
}
func (m *GetNodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodesResponse.Marshal(b, m, deterministic)
}
func (m *GetNodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodesResponse.Merge(m, src)
}
func (m *GetNodesResponse) XXX_Size() int {
	return xxx_messageInfo_GetNodesResponse.Size(m)
}
func (m *GetNodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodesResponse proto.InternalMessageInfo

func (m *GetNodesResponse) GetNode() []*Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type NodeBase struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	GroupName            string   `protobuf:"bytes,3,opt,name=GroupName,proto3" json:"GroupName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeBase) Reset()         { *m = NodeBase{} }
func (m *NodeBase) String() string { return proto.CompactTextString(m) }
func (*NodeBase) ProtoMessage()    {}
func (*NodeBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{22}
}

func (m *NodeBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeBase.Unmarshal(m, b)
}
func (m *NodeBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeBase.Marshal(b, m, deterministic)
}
func (m *NodeBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeBase.Merge(m, src)
}
func (m *NodeBase) XXX_Size() int {
	return xxx_messageInfo_NodeBase.Size(m)
}
func (m *NodeBase) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeBase.DiscardUnknown(m)
}

var xxx_messageInfo_NodeBase proto.InternalMessageInfo

func (m *NodeBase) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeBase) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *NodeBase) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

type GetNodeNameListResponse struct {
	Node                 []*NodeBase `protobuf:"bytes,1,rep,name=Node,proto3" json:"Node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetNodeNameListResponse) Reset()         { *m = GetNodeNameListResponse{} }
func (m *GetNodeNameListResponse) String() string { return proto.CompactTextString(m) }
func (*GetNodeNameListResponse) ProtoMessage()    {}
func (*GetNodeNameListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{23}
}

func (m *GetNodeNameListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeNameListResponse.Unmarshal(m, b)
}
func (m *GetNodeNameListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeNameListResponse.Marshal(b, m, deterministic)
}
func (m *GetNodeNameListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeNameListResponse.Merge(m, src)
}
func (m *GetNodeNameListResponse) XXX_Size() int {
	return xxx_messageInfo_GetNodeNameListResponse.Size(m)
}
func (m *GetNodeNameListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeNameListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeNameListResponse proto.InternalMessageInfo

func (m *GetNodeNameListResponse) GetNode() []*NodeBase {
	if m != nil {
		return m.Node
	}
	return nil
}

type GetNodeStatusRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeStatusRequest) Reset()         { *m = GetNodeStatusRequest{} }
func (m *GetNodeStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodeStatusRequest) ProtoMessage()    {}
func (*GetNodeStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{24}
}

func (m *GetNodeStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeStatusRequest.Unmarshal(m, b)
}
func (m *GetNodeStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetNodeStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeStatusRequest.Merge(m, src)
}
func (m *GetNodeStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodeStatusRequest.Size(m)
}
func (m *GetNodeStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeStatusRequest proto.InternalMessageInfo

func (m *GetNodeStatusRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type NodeStatus struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=Ip,proto3" json:"Ip,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	CpuUsage             int32    `protobuf:"varint,3,opt,name=CpuUsage,proto3" json:"CpuUsage,omitempty"`
	MemUsage             int32    `protobuf:"varint,4,opt,name=MemUsage,proto3" json:"MemUsage,omitempty"`
	OSVersion            string   `protobuf:"bytes,5,opt,name=OSVersion,proto3" json:"OSVersion,omitempty"`
	K8SVersion           string   `protobuf:"bytes,6,opt,name=K8SVersion,proto3" json:"K8SVersion,omitempty"`
	Pods                 []*Pod   `protobuf:"bytes,7,rep,name=Pods,proto3" json:"Pods,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeStatus) Reset()         { *m = NodeStatus{} }
func (m *NodeStatus) String() string { return proto.CompactTextString(m) }
func (*NodeStatus) ProtoMessage()    {}
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{25}
}

func (m *NodeStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeStatus.Unmarshal(m, b)
}
func (m *NodeStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeStatus.Marshal(b, m, deterministic)
}
func (m *NodeStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeStatus.Merge(m, src)
}
func (m *NodeStatus) XXX_Size() int {
	return xxx_messageInfo_NodeStatus.Size(m)
}
func (m *NodeStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeStatus.DiscardUnknown(m)
}

var xxx_messageInfo_NodeStatus proto.InternalMessageInfo

func (m *NodeStatus) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *NodeStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeStatus) GetCpuUsage() int32 {
	if m != nil {
		return m.CpuUsage
	}
	return 0
}

func (m *NodeStatus) GetMemUsage() int32 {
	if m != nil {
		return m.MemUsage
	}
	return 0
}

func (m *NodeStatus) GetOSVersion() string {
	if m != nil {
		return m.OSVersion
	}
	return ""
}

func (m *NodeStatus) GetK8SVersion() string {
	if m != nil {
		return m.K8SVersion
	}
	return ""
}

func (m *NodeStatus) GetPods() []*Pod {
	if m != nil {
		return m.Pods
	}
	return nil
}

type Pod struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	NameSpace            string   `protobuf:"bytes,2,opt,name=NameSpace,proto3" json:"NameSpace,omitempty"`
	PodIP                string   `protobuf:"bytes,3,opt,name=PodIP,proto3" json:"PodIP,omitempty"`
	Running              string   `protobuf:"bytes,4,opt,name=Running,proto3" json:"Running,omitempty"`
	Restarts             int32    `protobuf:"varint,5,opt,name=Restarts,proto3" json:"Restarts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pod) Reset()         { *m = Pod{} }
func (m *Pod) String() string { return proto.CompactTextString(m) }
func (*Pod) ProtoMessage()    {}
func (*Pod) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{26}
}

func (m *Pod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pod.Unmarshal(m, b)
}
func (m *Pod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pod.Marshal(b, m, deterministic)
}
func (m *Pod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pod.Merge(m, src)
}
func (m *Pod) XXX_Size() int {
	return xxx_messageInfo_Pod.Size(m)
}
func (m *Pod) XXX_DiscardUnknown() {
	xxx_messageInfo_Pod.DiscardUnknown(m)
}

var xxx_messageInfo_Pod proto.InternalMessageInfo

func (m *Pod) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pod) GetNameSpace() string {
	if m != nil {
		return m.NameSpace
	}
	return ""
}

func (m *Pod) GetPodIP() string {
	if m != nil {
		return m.PodIP
	}
	return ""
}

func (m *Pod) GetRunning() string {
	if m != nil {
		return m.Running
	}
	return ""
}

func (m *Pod) GetRestarts() int32 {
	if m != nil {
		return m.Restarts
	}
	return 0
}

type GetNodeStatusResponse struct {
	NodeStatus           *NodeStatus `protobuf:"bytes,1,opt,name=NodeStatus,proto3" json:"NodeStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetNodeStatusResponse) Reset()         { *m = GetNodeStatusResponse{} }
func (m *GetNodeStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetNodeStatusResponse) ProtoMessage()    {}
func (*GetNodeStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{27}
}

func (m *GetNodeStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeStatusResponse.Unmarshal(m, b)
}
func (m *GetNodeStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetNodeStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeStatusResponse.Merge(m, src)
}
func (m *GetNodeStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetNodeStatusResponse.Size(m)
}
func (m *GetNodeStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeStatusResponse proto.InternalMessageInfo

func (m *GetNodeStatusResponse) GetNodeStatus() *NodeStatus {
	if m != nil {
		return m.NodeStatus
	}
	return nil
}

type GetGroupRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupRequest) Reset()         { *m = GetGroupRequest{} }
func (m *GetGroupRequest) String() string { return proto.CompactTextString(m) }
func (*GetGroupRequest) ProtoMessage()    {}
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{28}
}

func (m *GetGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupRequest.Unmarshal(m, b)
}
func (m *GetGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupRequest.Marshal(b, m, deterministic)
}
func (m *GetGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupRequest.Merge(m, src)
}
func (m *GetGroupRequest) XXX_Size() int {
	return xxx_messageInfo_GetGroupRequest.Size(m)
}
func (m *GetGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupRequest proto.InternalMessageInfo

func (m *GetGroupRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetGroupResponse struct {
	Groupname            string   `protobuf:"bytes,1,opt,name=Groupname,proto3" json:"Groupname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupResponse) Reset()         { *m = GetGroupResponse{} }
func (m *GetGroupResponse) String() string { return proto.CompactTextString(m) }
func (*GetGroupResponse) ProtoMessage()    {}
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{29}
}

func (m *GetGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupResponse.Unmarshal(m, b)
}
func (m *GetGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupResponse.Marshal(b, m, deterministic)
}
func (m *GetGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupResponse.Merge(m, src)
}
func (m *GetGroupResponse) XXX_Size() int {
	return xxx_messageInfo_GetGroupResponse.Size(m)
}
func (m *GetGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupResponse proto.InternalMessageInfo

func (m *GetGroupResponse) GetGroupname() string {
	if m != nil {
		return m.Groupname
	}
	return ""
}

type AddToDefaultGroupRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToDefaultGroupRequest) Reset()         { *m = AddToDefaultGroupRequest{} }
func (m *AddToDefaultGroupRequest) String() string { return proto.CompactTextString(m) }
func (*AddToDefaultGroupRequest) ProtoMessage()    {}
func (*AddToDefaultGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{30}
}

func (m *AddToDefaultGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToDefaultGroupRequest.Unmarshal(m, b)
}
func (m *AddToDefaultGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToDefaultGroupRequest.Marshal(b, m, deterministic)
}
func (m *AddToDefaultGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToDefaultGroupRequest.Merge(m, src)
}
func (m *AddToDefaultGroupRequest) XXX_Size() int {
	return xxx_messageInfo_AddToDefaultGroupRequest.Size(m)
}
func (m *AddToDefaultGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToDefaultGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddToDefaultGroupRequest proto.InternalMessageInfo

func (m *AddToDefaultGroupRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddToDefaultGroupResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToDefaultGroupResponse) Reset()         { *m = AddToDefaultGroupResponse{} }
func (m *AddToDefaultGroupResponse) String() string { return proto.CompactTextString(m) }
func (*AddToDefaultGroupResponse) ProtoMessage()    {}
func (*AddToDefaultGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{31}
}

func (m *AddToDefaultGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToDefaultGroupResponse.Unmarshal(m, b)
}
func (m *AddToDefaultGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToDefaultGroupResponse.Marshal(b, m, deterministic)
}
func (m *AddToDefaultGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToDefaultGroupResponse.Merge(m, src)
}
func (m *AddToDefaultGroupResponse) XXX_Size() int {
	return xxx_messageInfo_AddToDefaultGroupResponse.Size(m)
}
func (m *AddToDefaultGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToDefaultGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddToDefaultGroupResponse proto.InternalMessageInfo

type RemoveFromDefaultGroupRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFromDefaultGroupRequest) Reset()         { *m = RemoveFromDefaultGroupRequest{} }
func (m *RemoveFromDefaultGroupRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveFromDefaultGroupRequest) ProtoMessage()    {}
func (*RemoveFromDefaultGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{32}
}

func (m *RemoveFromDefaultGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFromDefaultGroupRequest.Unmarshal(m, b)
}
func (m *RemoveFromDefaultGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFromDefaultGroupRequest.Marshal(b, m, deterministic)
}
func (m *RemoveFromDefaultGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFromDefaultGroupRequest.Merge(m, src)
}
func (m *RemoveFromDefaultGroupRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFromDefaultGroupRequest.Size(m)
}
func (m *RemoveFromDefaultGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFromDefaultGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFromDefaultGroupRequest proto.InternalMessageInfo

func (m *RemoveFromDefaultGroupRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RemoveFromDefaultGroupResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFromDefaultGroupResponse) Reset()         { *m = RemoveFromDefaultGroupResponse{} }
func (m *RemoveFromDefaultGroupResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveFromDefaultGroupResponse) ProtoMessage()    {}
func (*RemoveFromDefaultGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{33}
}

func (m *RemoveFromDefaultGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFromDefaultGroupResponse.Unmarshal(m, b)
}
func (m *RemoveFromDefaultGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFromDefaultGroupResponse.Marshal(b, m, deterministic)
}
func (m *RemoveFromDefaultGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFromDefaultGroupResponse.Merge(m, src)
}
func (m *RemoveFromDefaultGroupResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveFromDefaultGroupResponse.Size(m)
}
func (m *RemoveFromDefaultGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFromDefaultGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFromDefaultGroupResponse proto.InternalMessageInfo

type AddToGroupRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Groupname            string   `protobuf:"bytes,2,opt,name=Groupname,proto3" json:"Groupname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToGroupRequest) Reset()         { *m = AddToGroupRequest{} }
func (m *AddToGroupRequest) String() string { return proto.CompactTextString(m) }
func (*AddToGroupRequest) ProtoMessage()    {}
func (*AddToGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{34}
}

func (m *AddToGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToGroupRequest.Unmarshal(m, b)
}
func (m *AddToGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToGroupRequest.Marshal(b, m, deterministic)
}
func (m *AddToGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToGroupRequest.Merge(m, src)
}
func (m *AddToGroupRequest) XXX_Size() int {
	return xxx_messageInfo_AddToGroupRequest.Size(m)
}
func (m *AddToGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddToGroupRequest proto.InternalMessageInfo

func (m *AddToGroupRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddToGroupRequest) GetGroupname() string {
	if m != nil {
		return m.Groupname
	}
	return ""
}

type AddToGroupResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToGroupResponse) Reset()         { *m = AddToGroupResponse{} }
func (m *AddToGroupResponse) String() string { return proto.CompactTextString(m) }
func (*AddToGroupResponse) ProtoMessage()    {}
func (*AddToGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{35}
}

func (m *AddToGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToGroupResponse.Unmarshal(m, b)
}
func (m *AddToGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToGroupResponse.Marshal(b, m, deterministic)
}
func (m *AddToGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToGroupResponse.Merge(m, src)
}
func (m *AddToGroupResponse) XXX_Size() int {
	return xxx_messageInfo_AddToGroupResponse.Size(m)
}
func (m *AddToGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddToGroupResponse proto.InternalMessageInfo

type RemoveFromGroupRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Groupname            string   `protobuf:"bytes,2,opt,name=Groupname,proto3" json:"Groupname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFromGroupRequest) Reset()         { *m = RemoveFromGroupRequest{} }
func (m *RemoveFromGroupRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveFromGroupRequest) ProtoMessage()    {}
func (*RemoveFromGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{36}
}

func (m *RemoveFromGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFromGroupRequest.Unmarshal(m, b)
}
func (m *RemoveFromGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFromGroupRequest.Marshal(b, m, deterministic)
}
func (m *RemoveFromGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFromGroupRequest.Merge(m, src)
}
func (m *RemoveFromGroupRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFromGroupRequest.Size(m)
}
func (m *RemoveFromGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFromGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFromGroupRequest proto.InternalMessageInfo

func (m *RemoveFromGroupRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RemoveFromGroupRequest) GetGroupname() string {
	if m != nil {
		return m.Groupname
	}
	return ""
}

type RemoveFromGroupResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFromGroupResponse) Reset()         { *m = RemoveFromGroupResponse{} }
func (m *RemoveFromGroupResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveFromGroupResponse) ProtoMessage()    {}
func (*RemoveFromGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{37}
}

func (m *RemoveFromGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFromGroupResponse.Unmarshal(m, b)
}
func (m *RemoveFromGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFromGroupResponse.Marshal(b, m, deterministic)
}
func (m *RemoveFromGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFromGroupResponse.Merge(m, src)
}
func (m *RemoveFromGroupResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveFromGroupResponse.Size(m)
}
func (m *RemoveFromGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFromGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFromGroupResponse proto.InternalMessageInfo

type GetGroupNodeListRequest struct {
	Groupname            string   `protobuf:"bytes,1,opt,name=Groupname,proto3" json:"Groupname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupNodeListRequest) Reset()         { *m = GetGroupNodeListRequest{} }
func (m *GetGroupNodeListRequest) String() string { return proto.CompactTextString(m) }
func (*GetGroupNodeListRequest) ProtoMessage()    {}
func (*GetGroupNodeListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_159ac905e83eaac5, []int{38}
}

func (m *GetGroupNodeListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupNodeListRequest.Unmarshal(m, b)
}
func (m *GetGroupNodeListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupNodeListRequest.Marshal(b, m, deterministic)
}
func (m *GetGroupNodeListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupNodeListRequest.Merge(m, src)
}
func (m *GetGroupNodeListRequest) XXX_Size() int {
	return xxx_messageInfo_GetGroupNodeListRequest.Size(m)
}
func (m *GetGroupNodeListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupNodeListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupNodeListRequest proto.InternalMessageInfo

func (m *GetGroupNodeListRequest) GetGroupname() string {
	if m != nil {
		return m.Groupname
	}
	return ""
}

func init() {
	proto.RegisterType((*GetApiserverVersionRequest)(nil), "GetApiserverVersionRequest")
	proto.RegisterType((*GetApiserverVersionResponse)(nil), "GetApiserverVersionResponse")
	proto.RegisterType((*GetMasterStatusRequest)(nil), "GetMasterStatusRequest")
	proto.RegisterType((*GetMasterStatusResponse)(nil), "GetMasterStatusResponse")
	proto.RegisterType((*GetClusterCpuRequest)(nil), "GetClusterCpuRequest")
	proto.RegisterType((*GetClusterCpuResponse)(nil), "GetClusterCpuResponse")
	proto.RegisterType((*GetClusterMemoryRequest)(nil), "GetClusterMemoryRequest")
	proto.RegisterType((*GetClusterMemoryResponse)(nil), "GetClusterMemoryResponse")
	proto.RegisterType((*GetTotalPodNumberRequest)(nil), "GetTotalPodNumberRequest")
	proto.RegisterType((*GetTotalPodNumberResponse)(nil), "GetTotalPodNumberResponse")
	proto.RegisterType((*GetNetworkComponentRequest)(nil), "GetNetworkComponentRequest")
	proto.RegisterType((*NetworkComponent)(nil), "NetworkComponent")
	proto.RegisterType((*GetNetworkComponentResponse)(nil), "GetNetworkComponentResponse")
	proto.RegisterType((*GetDNSComponentRequest)(nil), "GetDNSComponentRequest")
	proto.RegisterType((*DNSComponent)(nil), "DNSComponent")
	proto.RegisterType((*GetDNSComponentResponse)(nil), "GetDNSComponentResponse")
	proto.RegisterType((*GetMonitorComponentRequest)(nil), "GetMonitorComponentRequest")
	proto.RegisterType((*MonitorComponent)(nil), "MonitorComponent")
	proto.RegisterType((*GetMonitorComponentResponse)(nil), "GetMonitorComponentResponse")
	proto.RegisterType((*GetNodesRequest)(nil), "GetNodesRequest")
	proto.RegisterType((*Node)(nil), "Node")
	proto.RegisterType((*GetNodesResponse)(nil), "GetNodesResponse")
	proto.RegisterType((*NodeBase)(nil), "NodeBase")
	proto.RegisterType((*GetNodeNameListResponse)(nil), "GetNodeNameListResponse")
	proto.RegisterType((*GetNodeStatusRequest)(nil), "GetNodeStatusRequest")
	proto.RegisterType((*NodeStatus)(nil), "NodeStatus")
	proto.RegisterType((*Pod)(nil), "Pod")
	proto.RegisterType((*GetNodeStatusResponse)(nil), "GetNodeStatusResponse")
	proto.RegisterType((*GetGroupRequest)(nil), "GetGroupRequest")
	proto.RegisterType((*GetGroupResponse)(nil), "GetGroupResponse")
	proto.RegisterType((*AddToDefaultGroupRequest)(nil), "AddToDefaultGroupRequest")
	proto.RegisterType((*AddToDefaultGroupResponse)(nil), "AddToDefaultGroupResponse")
	proto.RegisterType((*RemoveFromDefaultGroupRequest)(nil), "RemoveFromDefaultGroupRequest")
	proto.RegisterType((*RemoveFromDefaultGroupResponse)(nil), "RemoveFromDefaultGroupResponse")
	proto.RegisterType((*AddToGroupRequest)(nil), "AddToGroupRequest")
	proto.RegisterType((*AddToGroupResponse)(nil), "AddToGroupResponse")
	proto.RegisterType((*RemoveFromGroupRequest)(nil), "RemoveFromGroupRequest")
	proto.RegisterType((*RemoveFromGroupResponse)(nil), "RemoveFromGroupResponse")
	proto.RegisterType((*GetGroupNodeListRequest)(nil), "GetGroupNodeListRequest")
}

func init() { proto.RegisterFile("nodemanager.proto", fileDescriptor_159ac905e83eaac5) }

var fileDescriptor_159ac905e83eaac5 = []byte{
	// 1029 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0x5f, 0x73, 0xdb, 0x44,
	0x10, 0x97, 0xff, 0xb5, 0xf1, 0x86, 0x42, 0x7c, 0x4d, 0x1c, 0x59, 0x71, 0x43, 0xe6, 0x66, 0x18,
	0x0a, 0x0c, 0x37, 0x34, 0x7d, 0x68, 0x61, 0xa6, 0x40, 0x71, 0xa8, 0x27, 0x10, 0x07, 0x8f, 0x92,
	0xf2, 0x02, 0x2f, 0x0a, 0x3a, 0x32, 0x1e, 0x62, 0x9d, 0xd0, 0x9f, 0x32, 0xf0, 0xca, 0x17, 0xe3,
	0x5b, 0xf0, 0x75, 0x18, 0xed, 0xad, 0xfe, 0x4b, 0x0e, 0x81, 0x27, 0xeb, 0x76, 0xf7, 0x7e, 0xbb,
	0xb7, 0xbb, 0xb7, 0xf7, 0x33, 0x8c, 0x3c, 0xe5, 0xca, 0xb5, 0xe3, 0x39, 0xd7, 0x32, 0x10, 0x7e,
	0xa0, 0x22, 0xc5, 0xa7, 0x60, 0xcd, 0x65, 0xf4, 0xd2, 0x5f, 0x85, 0x32, 0x78, 0x23, 0x83, 0xef,
	0x65, 0x10, 0xae, 0x94, 0x67, 0xcb, 0x5f, 0x63, 0x19, 0x46, 0xfc, 0x05, 0x1c, 0x34, 0x6a, 0x43,
	0x5f, 0x79, 0xa1, 0x64, 0x87, 0x00, 0xf3, 0x55, 0x44, 0x52, 0xb3, 0x73, 0xd4, 0x79, 0x3c, 0xb4,
	0x0b, 0x12, 0x6e, 0xc2, 0x78, 0x2e, 0xa3, 0x85, 0x13, 0x46, 0x32, 0xb8, 0x88, 0x9c, 0x28, 0x0e,
	0x53, 0xe0, 0x09, 0xec, 0xd7, 0x34, 0x1a, 0x94, 0x8f, 0x61, 0x77, 0x2e, 0xa3, 0xd9, 0x4d, 0x9c,
	0xe8, 0x66, 0x7e, 0x9c, 0x6e, 0xf9, 0x00, 0xf6, 0x2a, 0x72, 0x8a, 0x62, 0x07, 0x7a, 0xb3, 0xe5,
	0x6b, 0x74, 0x3f, 0xb0, 0x93, 0x4f, 0x42, 0x27, 0xd3, 0x85, 0x5c, 0xab, 0xe0, 0xf7, 0x14, 0xe5,
	0x18, 0xcc, 0xba, 0x8a, 0x80, 0xc6, 0x70, 0x4f, 0x4b, 0x08, 0x8b, 0x56, 0xdc, 0xc2, 0x3d, 0x97,
	0x2a, 0x72, 0x6e, 0x96, 0xca, 0x3d, 0x8f, 0xd7, 0x57, 0x32, 0x48, 0xf1, 0x3e, 0x85, 0x49, 0x83,
	0x8e, 0x00, 0xa7, 0x30, 0xcc, 0x84, 0x84, 0x99, 0x0b, 0x28, 0xf5, 0xe7, 0x32, 0xfa, 0x4d, 0x05,
	0xbf, 0xcc, 0xd4, 0xda, 0x57, 0x9e, 0xf4, 0xa2, 0x14, 0xf8, 0x73, 0xd8, 0xa9, 0xaa, 0x18, 0x83,
	0xfe, 0xb9, 0xb3, 0x96, 0x94, 0x69, 0xfc, 0x4e, 0x82, 0xd6, 0x09, 0x34, 0xbb, 0x28, 0xa5, 0x15,
	0xff, 0x11, 0x4b, 0x57, 0x47, 0xa7, 0xd0, 0x5e, 0xd4, 0xe1, 0x11, 0x76, 0xfb, 0x78, 0x24, 0x6a,
	0x9b, 0x6a, 0xa6, 0x54, 0xd9, 0x93, 0xf3, 0x8b, 0x5a, 0xdc, 0x9f, 0xc1, 0x5b, 0x45, 0xf1, 0x9d,
	0x62, 0x3e, 0xc3, 0xba, 0x95, 0x51, 0x29, 0xde, 0x27, 0x65, 0x58, 0x8a, 0xf5, 0x81, 0x28, 0x19,
	0x97, 0x4c, 0x28, 0xbf, 0x0b, 0xe5, 0xad, 0x22, 0x15, 0x34, 0xe5, 0xb7, 0xaa, 0xfa, 0x0f, 0xf9,
	0xad, 0xa3, 0xe7, 0xf9, 0xad, 0xea, 0xb2, 0xfc, 0xd6, 0x36, 0xd5, 0x4c, 0xf9, 0xfb, 0xf0, 0x4e,
	0x52, 0x3d, 0xe5, 0xca, 0xf4, 0xca, 0xb0, 0x5d, 0x18, 0x9c, 0x39, 0x57, 0xf2, 0x86, 0xa2, 0xd3,
	0x0b, 0xfe, 0x07, 0xf4, 0x13, 0xab, 0xbb, 0x84, 0x8e, 0x17, 0xc6, 0x8f, 0xcd, 0x1e, 0x5d, 0x18,
	0x3f, 0x2e, 0x74, 0x7e, 0xbf, 0xd8, 0xf9, 0xe5, 0x06, 0x1e, 0x54, 0x1b, 0xf8, 0x63, 0xd8, 0xc9,
	0x83, 0xa4, 0x73, 0x4f, 0x74, 0x3c, 0x66, 0xe7, 0xa8, 0xf7, 0x78, 0xfb, 0x78, 0x20, 0x92, 0x85,
	0x8d, 0x22, 0x7e, 0x09, 0x5b, 0xc9, 0xef, 0x57, 0x4e, 0x78, 0xb7, 0x70, 0xa7, 0x30, 0x9c, 0x07,
	0x2a, 0xf6, 0x71, 0x43, 0x0f, 0x55, 0xb9, 0x80, 0x3f, 0xc7, 0x9e, 0x49, 0x80, 0x93, 0xe5, 0xd9,
	0x2a, 0xcc, 0x6b, 0xf0, 0xa8, 0x14, 0xcb, 0x50, 0xa4, 0xde, 0x29, 0x9e, 0x0f, 0x71, 0xd0, 0x24,
	0x9f, 0xa5, 0xd9, 0xd4, 0x14, 0x1b, 0xff, 0xab, 0x03, 0x90, 0x5b, 0xb2, 0xb7, 0xa1, 0x7b, 0xea,
	0x93, 0x41, 0xf7, 0xd4, 0xcf, 0xb6, 0x74, 0x0b, 0xc7, 0xb1, 0x60, 0x6b, 0xe6, 0xc7, 0xaf, 0x43,
	0xe7, 0x5a, 0x52, 0xaa, 0xb3, 0x75, 0xa2, 0x5b, 0xc8, 0xb5, 0xd6, 0xe9, 0x8c, 0x67, 0xeb, 0xe4,
	0xb8, 0xdf, 0x5d, 0xa4, 0x33, 0x75, 0xa0, 0x8f, 0x9b, 0x09, 0x92, 0x91, 0xfb, 0xed, 0xf3, 0x4c,
	0x7d, 0x4f, 0x8f, 0xdc, 0x5c, 0xc2, 0x4c, 0xe8, 0x2f, 0x95, 0x1b, 0x9a, 0xf7, 0xf1, 0xcc, 0x7d,
	0xb1, 0x54, 0xae, 0x8d, 0x12, 0xfe, 0x67, 0x07, 0x7a, 0x4b, 0xe5, 0x36, 0xa6, 0x7e, 0x0a, 0xc3,
	0xe4, 0xf7, 0xc2, 0x77, 0x7e, 0x4a, 0x0f, 0x91, 0x0b, 0x92, 0xce, 0x5b, 0x2a, 0xf7, 0x74, 0x49,
	0xc9, 0xd7, 0x0b, 0x66, 0xc2, 0x7d, 0x3b, 0xf6, 0xbc, 0x95, 0x77, 0x8d, 0x47, 0x18, 0xda, 0xe9,
	0x32, 0x39, 0x9d, 0x2d, 0xc3, 0xc8, 0x09, 0xa2, 0x90, 0x9a, 0x26, 0x5b, 0xf3, 0x13, 0x9c, 0xe2,
	0xc5, 0xa4, 0x53, 0xb1, 0x3e, 0x2a, 0x26, 0x98, 0xae, 0xca, 0xb6, 0x28, 0x18, 0x16, 0xd4, 0xfc,
	0x3d, 0xbc, 0x1e, 0xd8, 0x04, 0x9b, 0xaa, 0xf6, 0x09, 0x36, 0x28, 0x99, 0xe5, 0x33, 0x19, 0x05,
	0x5e, 0x6e, 0x9c, 0x0b, 0xb8, 0x00, 0xf3, 0xa5, 0xeb, 0x5e, 0xaa, 0x13, 0xf9, 0xb3, 0x13, 0xdf,
	0xdc, 0xee, 0xe1, 0x00, 0x26, 0x0d, 0xf6, 0xf4, 0x92, 0x3d, 0x85, 0x47, 0xb6, 0x5c, 0xab, 0x37,
	0xf2, 0x55, 0xa0, 0xd6, 0xff, 0x16, 0xf1, 0x08, 0x0e, 0xdb, 0x36, 0x11, 0xec, 0xd7, 0x30, 0x42,
	0x9f, 0xb7, 0x41, 0x95, 0x8f, 0xda, 0xad, 0x1e, 0x75, 0x17, 0x58, 0x11, 0x86, 0xc0, 0xbf, 0x81,
	0x71, 0xee, 0xfe, 0x7f, 0x7a, 0x98, 0xc0, 0x7e, 0x0d, 0x8b, 0xdc, 0x3c, 0xc3, 0x5b, 0xab, 0x6f,
	0xb1, 0x72, 0xe9, 0xda, 0x6a, 0x3f, 0x1b, 0x0b, 0x74, 0xfc, 0xf7, 0x10, 0xb6, 0x93, 0x1d, 0x0b,
	0xcd, 0x62, 0x98, 0x0d, 0x0f, 0x1b, 0x18, 0x0a, 0x3b, 0x10, 0xed, 0xac, 0xc6, 0x9a, 0x8a, 0x0d,
	0xa4, 0x86, 0x1b, 0xec, 0x15, 0x76, 0x57, 0x91, 0x9c, 0xb0, 0x7d, 0xd1, 0x4c, 0x64, 0x2c, 0x53,
	0xb4, 0xf1, 0x18, 0x83, 0x7d, 0x09, 0x0f, 0x4a, 0x8c, 0x85, 0xed, 0x89, 0x26, 0x66, 0x63, 0x8d,
	0x45, 0x23, 0xb1, 0xe1, 0x06, 0x3b, 0xc5, 0x06, 0x2e, 0xb1, 0x15, 0x66, 0x8a, 0x16, 0x6e, 0x63,
	0x4d, 0x44, 0x1b, 0xb5, 0xe1, 0x06, 0x3b, 0x83, 0x51, 0x8d, 0xa8, 0x30, 0xdc, 0xd1, 0x48, 0x6c,
	0x2c, 0x4b, 0xb4, 0xf2, 0x1a, 0x6e, 0x50, 0xda, 0x6b, 0x04, 0x05, 0xd3, 0xde, 0xc2, 0x68, 0x74,
	0xda, 0xdb, 0x08, 0x49, 0x96, 0xf6, 0x12, 0x79, 0xc0, 0xb4, 0x37, 0xb0, 0x0c, 0x9d, 0xf6, 0x26,
	0xa2, 0x90, 0xc5, 0x56, 0x7b, 0xdc, 0x31, 0xb6, 0x16, 0x36, 0xa0, 0x63, 0x6b, 0x7b, 0xcc, 0xb9,
	0xc1, 0x9e, 0xc0, 0x56, 0xfa, 0xd4, 0xb1, 0x1d, 0x51, 0x79, 0x9a, 0xad, 0x91, 0xa8, 0xbe, 0x83,
	0x59, 0xf5, 0x0b, 0x8f, 0xc6, 0x9e, 0x68, 0x7a, 0x6e, 0x74, 0xf5, 0xeb, 0x03, 0x31, 0x73, 0x8a,
	0xbd, 0xaf, 0x9d, 0x16, 0xef, 0xa3, 0x76, 0x5a, 0xbe, 0x55, 0x58, 0xe5, 0xda, 0x3c, 0x62, 0x13,
	0xd1, 0x36, 0xd3, 0x2c, 0x4b, 0xb4, 0x8f, 0x2f, 0x83, 0xfd, 0x50, 0x1c, 0x06, 0x25, 0xc8, 0x43,
	0xb1, 0x71, 0xb2, 0x59, 0xef, 0x8a, 0x5b, 0x86, 0x98, 0xc1, 0x9e, 0x01, 0xe4, 0xf3, 0x87, 0x31,
	0x51, 0x9b, 0x69, 0xd6, 0x43, 0xd1, 0x30, 0xa0, 0xb0, 0x4f, 0x2a, 0x63, 0x85, 0xed, 0x8b, 0xe6,
	0xa1, 0x65, 0x99, 0xa2, 0x6d, 0x02, 0x19, 0xec, 0x8b, 0x8c, 0x63, 0xa5, 0xcc, 0xa1, 0xa1, 0xb4,
	0xa6, 0x68, 0x61, 0x17, 0x98, 0xec, 0xdd, 0xe2, 0x10, 0xcb, 0x50, 0x4c, 0xd1, 0x32, 0xdb, 0x36,
	0xa1, 0x5d, 0xdd, 0xc3, 0x3f, 0x64, 0x4f, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x72, 0x71,
	0x91, 0xa5, 0x0d, 0x00, 0x00,
}
