// Code generated by protoc-gen-go. DO NOT EDIT.
// source: businesscenter.proto

package businesscenter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/micro/go-api/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RpcListAppRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UserType             int32    `protobuf:"varint,2,opt,name=UserType,proto3" json:"UserType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcListAppRequest) Reset()         { *m = RpcListAppRequest{} }
func (m *RpcListAppRequest) String() string { return proto.CompactTextString(m) }
func (*RpcListAppRequest) ProtoMessage()    {}
func (*RpcListAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_businesscenter_462a86278eb4ca79, []int{0}
}
func (m *RpcListAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcListAppRequest.Unmarshal(m, b)
}
func (m *RpcListAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcListAppRequest.Marshal(b, m, deterministic)
}
func (dst *RpcListAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcListAppRequest.Merge(dst, src)
}
func (m *RpcListAppRequest) XXX_Size() int {
	return xxx_messageInfo_RpcListAppRequest.Size(m)
}
func (m *RpcListAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcListAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RpcListAppRequest proto.InternalMessageInfo

func (m *RpcListAppRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RpcListAppRequest) GetUserType() int32 {
	if m != nil {
		return m.UserType
	}
	return 0
}

type RpcListAppResponse struct {
	AppItems             []*AppItem `protobuf:"bytes,1,rep,name=AppItems,proto3" json:"AppItems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RpcListAppResponse) Reset()         { *m = RpcListAppResponse{} }
func (m *RpcListAppResponse) String() string { return proto.CompactTextString(m) }
func (*RpcListAppResponse) ProtoMessage()    {}
func (*RpcListAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_businesscenter_462a86278eb4ca79, []int{1}
}
func (m *RpcListAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcListAppResponse.Unmarshal(m, b)
}
func (m *RpcListAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcListAppResponse.Marshal(b, m, deterministic)
}
func (dst *RpcListAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcListAppResponse.Merge(dst, src)
}
func (m *RpcListAppResponse) XXX_Size() int {
	return xxx_messageInfo_RpcListAppResponse.Size(m)
}
func (m *RpcListAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcListAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RpcListAppResponse proto.InternalMessageInfo

func (m *RpcListAppResponse) GetAppItems() []*AppItem {
	if m != nil {
		return m.AppItems
	}
	return nil
}

type RpcQueryAppRequest struct {
	AppID                int32    `protobuf:"varint,1,opt,name=AppID,proto3" json:"AppID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcQueryAppRequest) Reset()         { *m = RpcQueryAppRequest{} }
func (m *RpcQueryAppRequest) String() string { return proto.CompactTextString(m) }
func (*RpcQueryAppRequest) ProtoMessage()    {}
func (*RpcQueryAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_businesscenter_462a86278eb4ca79, []int{2}
}
func (m *RpcQueryAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcQueryAppRequest.Unmarshal(m, b)
}
func (m *RpcQueryAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcQueryAppRequest.Marshal(b, m, deterministic)
}
func (dst *RpcQueryAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcQueryAppRequest.Merge(dst, src)
}
func (m *RpcQueryAppRequest) XXX_Size() int {
	return xxx_messageInfo_RpcQueryAppRequest.Size(m)
}
func (m *RpcQueryAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcQueryAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RpcQueryAppRequest proto.InternalMessageInfo

func (m *RpcQueryAppRequest) GetAppID() int32 {
	if m != nil {
		return m.AppID
	}
	return 0
}

type RpcQueryAppResponse struct {
	AppID                int32     `protobuf:"varint,1,opt,name=AppID,proto3" json:"AppID,omitempty"`
	AppName              string    `protobuf:"bytes,2,opt,name=AppName,proto3" json:"AppName,omitempty"`
	Environments         []*AppEnv `protobuf:"bytes,3,rep,name=Environments,proto3" json:"Environments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RpcQueryAppResponse) Reset()         { *m = RpcQueryAppResponse{} }
func (m *RpcQueryAppResponse) String() string { return proto.CompactTextString(m) }
func (*RpcQueryAppResponse) ProtoMessage()    {}
func (*RpcQueryAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_businesscenter_462a86278eb4ca79, []int{3}
}
func (m *RpcQueryAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcQueryAppResponse.Unmarshal(m, b)
}
func (m *RpcQueryAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcQueryAppResponse.Marshal(b, m, deterministic)
}
func (dst *RpcQueryAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcQueryAppResponse.Merge(dst, src)
}
func (m *RpcQueryAppResponse) XXX_Size() int {
	return xxx_messageInfo_RpcQueryAppResponse.Size(m)
}
func (m *RpcQueryAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcQueryAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RpcQueryAppResponse proto.InternalMessageInfo

func (m *RpcQueryAppResponse) GetAppID() int32 {
	if m != nil {
		return m.AppID
	}
	return 0
}

func (m *RpcQueryAppResponse) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *RpcQueryAppResponse) GetEnvironments() []*AppEnv {
	if m != nil {
		return m.Environments
	}
	return nil
}

type RPCListAppEnvsResponse struct {
	Envs                 []*AppEnv `protobuf:"bytes,1,rep,name=Envs,proto3" json:"Envs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RPCListAppEnvsResponse) Reset()         { *m = RPCListAppEnvsResponse{} }
func (m *RPCListAppEnvsResponse) String() string { return proto.CompactTextString(m) }
func (*RPCListAppEnvsResponse) ProtoMessage()    {}
func (*RPCListAppEnvsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_businesscenter_462a86278eb4ca79, []int{4}
}
func (m *RPCListAppEnvsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCListAppEnvsResponse.Unmarshal(m, b)
}
func (m *RPCListAppEnvsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCListAppEnvsResponse.Marshal(b, m, deterministic)
}
func (dst *RPCListAppEnvsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCListAppEnvsResponse.Merge(dst, src)
}
func (m *RPCListAppEnvsResponse) XXX_Size() int {
	return xxx_messageInfo_RPCListAppEnvsResponse.Size(m)
}
func (m *RPCListAppEnvsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCListAppEnvsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RPCListAppEnvsResponse proto.InternalMessageInfo

func (m *RPCListAppEnvsResponse) GetEnvs() []*AppEnv {
	if m != nil {
		return m.Envs
	}
	return nil
}

type AppEnv struct {
	EnvId                int32            `protobuf:"varint,1,opt,name=EnvId,proto3" json:"EnvId,omitempty"`
	EnvName              string           `protobuf:"bytes,2,opt,name=EnvName,proto3" json:"EnvName,omitempty"`
	EnvType              int32            `protobuf:"varint,3,opt,name=EnvType,proto3" json:"EnvType,omitempty"`
	Projects             []*ParentProject `protobuf:"bytes,4,rep,name=Projects,proto3" json:"Projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AppEnv) Reset()         { *m = AppEnv{} }
func (m *AppEnv) String() string { return proto.CompactTextString(m) }
func (*AppEnv) ProtoMessage()    {}
func (*AppEnv) Descriptor() ([]byte, []int) {
	return fileDescriptor_businesscenter_462a86278eb4ca79, []int{5}
}
func (m *AppEnv) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppEnv.Unmarshal(m, b)
}
func (m *AppEnv) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppEnv.Marshal(b, m, deterministic)
}
func (dst *AppEnv) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppEnv.Merge(dst, src)
}
func (m *AppEnv) XXX_Size() int {
	return xxx_messageInfo_AppEnv.Size(m)
}
func (m *AppEnv) XXX_DiscardUnknown() {
	xxx_messageInfo_AppEnv.DiscardUnknown(m)
}

var xxx_messageInfo_AppEnv proto.InternalMessageInfo

func (m *AppEnv) GetEnvId() int32 {
	if m != nil {
		return m.EnvId
	}
	return 0
}

func (m *AppEnv) GetEnvName() string {
	if m != nil {
		return m.EnvName
	}
	return ""
}

func (m *AppEnv) GetEnvType() int32 {
	if m != nil {
		return m.EnvType
	}
	return 0
}

func (m *AppEnv) GetProjects() []*ParentProject {
	if m != nil {
		return m.Projects
	}
	return nil
}

type ParentProject struct {
	EnvId                int32    `protobuf:"varint,1,opt,name=EnvId,proto3" json:"EnvId,omitempty"`
	ProjectId            int32    `protobuf:"varint,2,opt,name=ProjectId,proto3" json:"ProjectId,omitempty"`
	ProjectName          string   `protobuf:"bytes,3,opt,name=ProjectName,proto3" json:"ProjectName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParentProject) Reset()         { *m = ParentProject{} }
func (m *ParentProject) String() string { return proto.CompactTextString(m) }
func (*ParentProject) ProtoMessage()    {}
func (*ParentProject) Descriptor() ([]byte, []int) {
	return fileDescriptor_businesscenter_462a86278eb4ca79, []int{6}
}
func (m *ParentProject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParentProject.Unmarshal(m, b)
}
func (m *ParentProject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParentProject.Marshal(b, m, deterministic)
}
func (dst *ParentProject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParentProject.Merge(dst, src)
}
func (m *ParentProject) XXX_Size() int {
	return xxx_messageInfo_ParentProject.Size(m)
}
func (m *ParentProject) XXX_DiscardUnknown() {
	xxx_messageInfo_ParentProject.DiscardUnknown(m)
}

var xxx_messageInfo_ParentProject proto.InternalMessageInfo

func (m *ParentProject) GetEnvId() int32 {
	if m != nil {
		return m.EnvId
	}
	return 0
}

func (m *ParentProject) GetProjectId() int32 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *ParentProject) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

type AppParam struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppParam) Reset()         { *m = AppParam{} }
func (m *AppParam) String() string { return proto.CompactTextString(m) }
func (*AppParam) ProtoMessage()    {}
func (*AppParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_businesscenter_462a86278eb4ca79, []int{7}
}
func (m *AppParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppParam.Unmarshal(m, b)
}
func (m *AppParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppParam.Marshal(b, m, deterministic)
}
func (dst *AppParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppParam.Merge(dst, src)
}
func (m *AppParam) XXX_Size() int {
	return xxx_messageInfo_AppParam.Size(m)
}
func (m *AppParam) XXX_DiscardUnknown() {
	xxx_messageInfo_AppParam.DiscardUnknown(m)
}

var xxx_messageInfo_AppParam proto.InternalMessageInfo

type AppItem struct {
	AppID                int32    `protobuf:"varint,1,opt,name=AppID,proto3" json:"AppID,omitempty"`
	AppName              string   `protobuf:"bytes,2,opt,name=AppName,proto3" json:"AppName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppItem) Reset()         { *m = AppItem{} }
func (m *AppItem) String() string { return proto.CompactTextString(m) }
func (*AppItem) ProtoMessage()    {}
func (*AppItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_businesscenter_462a86278eb4ca79, []int{8}
}
func (m *AppItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppItem.Unmarshal(m, b)
}
func (m *AppItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppItem.Marshal(b, m, deterministic)
}
func (dst *AppItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppItem.Merge(dst, src)
}
func (m *AppItem) XXX_Size() int {
	return xxx_messageInfo_AppItem.Size(m)
}
func (m *AppItem) XXX_DiscardUnknown() {
	xxx_messageInfo_AppItem.DiscardUnknown(m)
}

var xxx_messageInfo_AppItem proto.InternalMessageInfo

func (m *AppItem) GetAppID() int32 {
	if m != nil {
		return m.AppID
	}
	return 0
}

func (m *AppItem) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

type AppList struct {
	AppList              []*AppItem `protobuf:"bytes,1,rep,name=AppList,proto3" json:"AppList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AppList) Reset()         { *m = AppList{} }
func (m *AppList) String() string { return proto.CompactTextString(m) }
func (*AppList) ProtoMessage()    {}
func (*AppList) Descriptor() ([]byte, []int) {
	return fileDescriptor_businesscenter_462a86278eb4ca79, []int{9}
}
func (m *AppList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppList.Unmarshal(m, b)
}
func (m *AppList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppList.Marshal(b, m, deterministic)
}
func (dst *AppList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppList.Merge(dst, src)
}
func (m *AppList) XXX_Size() int {
	return xxx_messageInfo_AppList.Size(m)
}
func (m *AppList) XXX_DiscardUnknown() {
	xxx_messageInfo_AppList.DiscardUnknown(m)
}

var xxx_messageInfo_AppList proto.InternalMessageInfo

func (m *AppList) GetAppList() []*AppItem {
	if m != nil {
		return m.AppList
	}
	return nil
}

type ParentProjectInfo struct {
	ParentProjectID      int32    `protobuf:"varint,1,opt,name=ParentProjectID,proto3" json:"ParentProjectID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParentProjectInfo) Reset()         { *m = ParentProjectInfo{} }
func (m *ParentProjectInfo) String() string { return proto.CompactTextString(m) }
func (*ParentProjectInfo) ProtoMessage()    {}
func (*ParentProjectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_businesscenter_462a86278eb4ca79, []int{10}
}
func (m *ParentProjectInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParentProjectInfo.Unmarshal(m, b)
}
func (m *ParentProjectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParentProjectInfo.Marshal(b, m, deterministic)
}
func (dst *ParentProjectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParentProjectInfo.Merge(dst, src)
}
func (m *ParentProjectInfo) XXX_Size() int {
	return xxx_messageInfo_ParentProjectInfo.Size(m)
}
func (m *ParentProjectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ParentProjectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ParentProjectInfo proto.InternalMessageInfo

func (m *ParentProjectInfo) GetParentProjectID() int32 {
	if m != nil {
		return m.ParentProjectID
	}
	return 0
}

type AppInfo struct {
	AppID                int32    `protobuf:"varint,1,opt,name=AppID,proto3" json:"AppID,omitempty"`
	AppName              string   `protobuf:"bytes,2,opt,name=AppName,proto3" json:"AppName,omitempty"`
	EnvironmentName      string   `protobuf:"bytes,3,opt,name=EnvironmentName,proto3" json:"EnvironmentName,omitempty"`
	EnvironmentType      int32    `protobuf:"varint,4,opt,name=EnvironmentType,proto3" json:"EnvironmentType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppInfo) Reset()         { *m = AppInfo{} }
func (m *AppInfo) String() string { return proto.CompactTextString(m) }
func (*AppInfo) ProtoMessage()    {}
func (*AppInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_businesscenter_462a86278eb4ca79, []int{11}
}
func (m *AppInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppInfo.Unmarshal(m, b)
}
func (m *AppInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppInfo.Marshal(b, m, deterministic)
}
func (dst *AppInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppInfo.Merge(dst, src)
}
func (m *AppInfo) XXX_Size() int {
	return xxx_messageInfo_AppInfo.Size(m)
}
func (m *AppInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AppInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AppInfo proto.InternalMessageInfo

func (m *AppInfo) GetAppID() int32 {
	if m != nil {
		return m.AppID
	}
	return 0
}

func (m *AppInfo) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *AppInfo) GetEnvironmentName() string {
	if m != nil {
		return m.EnvironmentName
	}
	return ""
}

func (m *AppInfo) GetEnvironmentType() int32 {
	if m != nil {
		return m.EnvironmentType
	}
	return 0
}

func init() {
	proto.RegisterType((*RpcListAppRequest)(nil), "RpcListAppRequest")
	proto.RegisterType((*RpcListAppResponse)(nil), "RpcListAppResponse")
	proto.RegisterType((*RpcQueryAppRequest)(nil), "RpcQueryAppRequest")
	proto.RegisterType((*RpcQueryAppResponse)(nil), "RpcQueryAppResponse")
	proto.RegisterType((*RPCListAppEnvsResponse)(nil), "RPCListAppEnvsResponse")
	proto.RegisterType((*AppEnv)(nil), "AppEnv")
	proto.RegisterType((*ParentProject)(nil), "ParentProject")
	proto.RegisterType((*AppParam)(nil), "AppParam")
	proto.RegisterType((*AppItem)(nil), "AppItem")
	proto.RegisterType((*AppList)(nil), "AppList")
	proto.RegisterType((*ParentProjectInfo)(nil), "ParentProjectInfo")
	proto.RegisterType((*AppInfo)(nil), "AppInfo")
}

func init() {
	proto.RegisterFile("businesscenter.proto", fileDescriptor_businesscenter_462a86278eb4ca79)
}

var fileDescriptor_businesscenter_462a86278eb4ca79 = []byte{
	// 695 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xeb, 0x6e, 0xd3, 0x30,
	0x14, 0x6e, 0xe9, 0x7a, 0x3b, 0xbb, 0x94, 0x79, 0xdd, 0xa8, 0x0a, 0x42, 0x95, 0x85, 0xa0, 0x1a,
	0xcc, 0x45, 0x43, 0xc0, 0x36, 0x40, 0xa8, 0x5b, 0xcb, 0x54, 0x31, 0x4d, 0x25, 0x6c, 0x0f, 0x90,
	0x75, 0xa6, 0x84, 0x35, 0xb6, 0x71, 0xd2, 0xa2, 0xee, 0x07, 0x0f, 0x80, 0xc4, 0x3b, 0x23, 0x3b,
	0x4e, 0x97, 0xa4, 0x45, 0x4a, 0xff, 0xf9, 0x5c, 0x3e, 0x9f, 0xcf, 0x3e, 0xe7, 0xb3, 0xa1, 0x7a,
	0x35, 0xf6, 0x1c, 0x46, 0x3d, 0x6f, 0x40, 0x99, 0x4f, 0x25, 0x11, 0x92, 0xfb, 0xbc, 0xfe, 0x6c,
	0xe8, 0xf8, 0xdf, 0xc7, 0x57, 0x64, 0xc0, 0xdd, 0x96, 0xeb, 0x0c, 0x24, 0x6f, 0x0d, 0xf9, 0x9e,
	0x2d, 0x9c, 0x96, 0x0e, 0xb7, 0x6c, 0xe1, 0x04, 0x89, 0xf8, 0x14, 0x36, 0x2d, 0x31, 0x38, 0x73,
	0x3c, 0xbf, 0x2d, 0x84, 0x45, 0x7f, 0x8e, 0xa9, 0xe7, 0xa3, 0x1d, 0x28, 0x5c, 0x7a, 0x54, 0xf6,
	0xae, 0x6b, 0xd9, 0x46, 0xb6, 0x99, 0xb3, 0x8c, 0x85, 0xea, 0x50, 0x52, 0xab, 0x8b, 0xa9, 0xa0,
	0xb5, 0x7b, 0x8d, 0x6c, 0x33, 0x6f, 0xcd, 0x6c, 0x7c, 0x04, 0x28, 0xba, 0x91, 0x27, 0x38, 0xf3,
	0x28, 0x7a, 0x02, 0xa5, 0xb6, 0x10, 0x3d, 0x9f, 0xba, 0x5e, 0x2d, 0xdb, 0xc8, 0x35, 0x57, 0xf7,
	0x4b, 0xc4, 0x38, 0xac, 0x59, 0x04, 0xef, 0x6a, 0xec, 0x97, 0x31, 0x95, 0xd3, 0x08, 0x8b, 0x2a,
	0xe4, 0x55, 0x46, 0x47, 0x93, 0xc8, 0x5b, 0x81, 0x81, 0x25, 0x6c, 0xc5, 0x72, 0x4d, 0xa1, 0x85,
	0xc9, 0xa8, 0x06, 0xc5, 0xb6, 0x10, 0xe7, 0xb6, 0x1b, 0xf0, 0x2d, 0x5b, 0xa1, 0x89, 0x9e, 0xc3,
	0x5a, 0x97, 0x4d, 0x1c, 0xc9, 0x99, 0x4b, 0x99, 0xef, 0xd5, 0x72, 0x9a, 0x5c, 0x51, 0x91, 0xeb,
	0xb2, 0x89, 0x15, 0x0b, 0xe2, 0xd7, 0xb0, 0x63, 0xf5, 0x4f, 0xcc, 0xd9, 0xba, 0x6c, 0xe2, 0xcd,
	0xca, 0x3e, 0x84, 0x15, 0x65, 0x9b, 0xb3, 0xcd, 0xe0, 0xda, 0x89, 0x7f, 0x43, 0x21, 0xb0, 0x15,
	0xbb, 0x2e, 0x9b, 0x98, 0xfb, 0xcc, 0x5b, 0x81, 0xa1, 0xd8, 0x75, 0xd9, 0x24, 0xca, 0xce, 0x98,
	0x26, 0xa2, 0xef, 0x39, 0xa7, 0x11, 0xa1, 0x89, 0x76, 0xa1, 0xd4, 0x97, 0xfc, 0x07, 0x1d, 0xf8,
	0x5e, 0x6d, 0x45, 0x17, 0xdd, 0x20, 0x7d, 0x5b, 0x52, 0xe6, 0x1b, 0xb7, 0x35, 0x8b, 0x63, 0x0a,
	0xeb, 0xb1, 0xd0, 0x7f, 0x68, 0x3c, 0x82, 0xb2, 0x49, 0xe8, 0x5d, 0x9b, 0xb6, 0xde, 0x39, 0x50,
	0x03, 0x56, 0x8d, 0xa1, 0x89, 0xe6, 0x34, 0xd1, 0xa8, 0x0b, 0x83, 0xee, 0x71, 0xdf, 0x96, 0xb6,
	0x8b, 0x0f, 0xf5, 0x85, 0xab, 0xae, 0x2e, 0xdb, 0x11, 0xbc, 0xa7, 0x23, 0xea, 0x92, 0x11, 0x9e,
	0x2d, 0xe7, 0x86, 0x26, 0x0c, 0xe0, 0x0f, 0xb0, 0x19, 0x3b, 0x5c, 0x8f, 0x7d, 0xe3, 0xa8, 0x09,
	0x95, 0xb8, 0x33, 0xac, 0x9e, 0x74, 0xe3, 0xbf, 0xd9, 0x80, 0xa9, 0x42, 0x2d, 0x3b, 0x3b, 0x4d,
	0xa8, 0x44, 0xc6, 0x23, 0x72, 0x2d, 0x49, 0x77, 0x22, 0x53, 0xf7, 0x73, 0x25, 0xe0, 0x93, 0x70,
	0xef, 0xff, 0x29, 0xc2, 0xc6, 0x71, 0x4c, 0xc9, 0x68, 0x0f, 0x0a, 0xe7, 0xf4, 0x57, 0x5b, 0x08,
	0x54, 0x21, 0x43, 0x4e, 0x94, 0x66, 0x8d, 0x34, 0xea, 0xf7, 0xef, 0x1c, 0xc1, 0x20, 0xe2, 0x0c,
	0x7a, 0x09, 0xe5, 0x4b, 0x71, 0x6d, 0xfb, 0x34, 0x35, 0xa2, 0x05, 0xa5, 0x50, 0x47, 0xe9, 0x00,
	0x87, 0x80, 0x42, 0xc0, 0xf1, 0x34, 0xb8, 0xd1, 0x5e, 0x27, 0x35, 0xbb, 0x0e, 0x1d, 0xd1, 0x25,
	0xd8, 0x11, 0x28, 0x1a, 0xc5, 0xa5, 0xcb, 0x3f, 0x48, 0x0c, 0x84, 0x9e, 0xa4, 0x54, 0xc8, 0x2e,
	0x3c, 0xd6, 0xc7, 0xfa, 0x7c, 0xf0, 0xb5, 0x2f, 0x79, 0x6c, 0x93, 0xe3, 0xe9, 0x05, 0x4d, 0xbb,
	0xcd, 0x7b, 0xd8, 0x56, 0x35, 0xcf, 0xf9, 0x99, 0xc3, 0x6e, 0x82, 0x5d, 0x4e, 0x25, 0x1f, 0xa7,
	0xa4, 0xff, 0x06, 0x2a, 0x9f, 0xc6, 0xb7, 0xb7, 0x53, 0xb5, 0x45, 0x00, 0x4e, 0x87, 0x7b, 0x07,
	0xd5, 0x04, 0x6e, 0x89, 0xa2, 0x4f, 0x61, 0xfd, 0x94, 0xfa, 0xed, 0xd1, 0x28, 0x54, 0x5e, 0x99,
	0x84, 0x52, 0xae, 0x6b, 0xcd, 0x69, 0xa9, 0x65, 0xd0, 0x5b, 0xd8, 0x8e, 0x3c, 0xba, 0x91, 0xde,
	0x23, 0x32, 0x27, 0xc2, 0x00, 0xa8, 0x56, 0x1a, 0x08, 0x77, 0x2f, 0x27, 0x42, 0x64, 0xee, 0xaf,
	0xa9, 0x6f, 0x91, 0xf9, 0x6f, 0x03, 0x67, 0xd0, 0x11, 0xac, 0x5a, 0xfd, 0x93, 0xd9, 0x78, 0xea,
	0xac, 0xc4, 0x07, 0x51, 0xaf, 0x92, 0x05, 0x3f, 0x01, 0xce, 0xa0, 0x8f, 0xb0, 0x11, 0x7f, 0xae,
	0x17, 0x16, 0x7e, 0x40, 0x16, 0xbf, 0xe9, 0x38, 0xb3, 0x7f, 0x03, 0x6b, 0x1d, 0x2a, 0x46, 0x7c,
	0xea, 0xda, 0xcc, 0x1e, 0x52, 0xa5, 0xc4, 0x9e, 0x2b, 0xb8, 0x4c, 0xd9, 0x92, 0x17, 0x90, 0xd7,
	0xac, 0x52, 0x65, 0x5f, 0x15, 0xf4, 0x47, 0xfc, 0xea, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x08,
	0x89, 0x00, 0xa6, 0xc9, 0x07, 0x00, 0x00,
}
