// Code generated by protoc-gen-go. DO NOT EDIT.
// source: terraform.proto

package terraform

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TFProviderType struct {
	TFProviderTypeName   string   `protobuf:"bytes,1,opt,name=TFProviderTypeName,proto3" json:"TFProviderTypeName,omitempty"`
	TFProviderTypeVars   string   `protobuf:"bytes,2,opt,name=TFProviderTypeVars,proto3" json:"TFProviderTypeVars,omitempty"`
	TFProviderTypeGitUrl string   `protobuf:"bytes,3,opt,name=TFProviderTypeGitUrl,proto3" json:"TFProviderTypeGitUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TFProviderType) Reset()         { *m = TFProviderType{} }
func (m *TFProviderType) String() string { return proto.CompactTextString(m) }
func (*TFProviderType) ProtoMessage()    {}
func (*TFProviderType) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbef5fc442f72120, []int{0}
}

func (m *TFProviderType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TFProviderType.Unmarshal(m, b)
}
func (m *TFProviderType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TFProviderType.Marshal(b, m, deterministic)
}
func (m *TFProviderType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TFProviderType.Merge(m, src)
}
func (m *TFProviderType) XXX_Size() int {
	return xxx_messageInfo_TFProviderType.Size(m)
}
func (m *TFProviderType) XXX_DiscardUnknown() {
	xxx_messageInfo_TFProviderType.DiscardUnknown(m)
}

var xxx_messageInfo_TFProviderType proto.InternalMessageInfo

func (m *TFProviderType) GetTFProviderTypeName() string {
	if m != nil {
		return m.TFProviderTypeName
	}
	return ""
}

func (m *TFProviderType) GetTFProviderTypeVars() string {
	if m != nil {
		return m.TFProviderTypeVars
	}
	return ""
}

func (m *TFProviderType) GetTFProviderTypeGitUrl() string {
	if m != nil {
		return m.TFProviderTypeGitUrl
	}
	return ""
}

type TFProviderTypeResponse struct {
	TFProviderTypeID     string   `protobuf:"bytes,1,opt,name=TFProviderTypeID,proto3" json:"TFProviderTypeID,omitempty"`
	TFProviderTypeName   string   `protobuf:"bytes,2,opt,name=TFProviderTypeName,proto3" json:"TFProviderTypeName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TFProviderTypeResponse) Reset()         { *m = TFProviderTypeResponse{} }
func (m *TFProviderTypeResponse) String() string { return proto.CompactTextString(m) }
func (*TFProviderTypeResponse) ProtoMessage()    {}
func (*TFProviderTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbef5fc442f72120, []int{1}
}

func (m *TFProviderTypeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TFProviderTypeResponse.Unmarshal(m, b)
}
func (m *TFProviderTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TFProviderTypeResponse.Marshal(b, m, deterministic)
}
func (m *TFProviderTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TFProviderTypeResponse.Merge(m, src)
}
func (m *TFProviderTypeResponse) XXX_Size() int {
	return xxx_messageInfo_TFProviderTypeResponse.Size(m)
}
func (m *TFProviderTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TFProviderTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TFProviderTypeResponse proto.InternalMessageInfo

func (m *TFProviderTypeResponse) GetTFProviderTypeID() string {
	if m != nil {
		return m.TFProviderTypeID
	}
	return ""
}

func (m *TFProviderTypeResponse) GetTFProviderTypeName() string {
	if m != nil {
		return m.TFProviderTypeName
	}
	return ""
}

func init() {
	proto.RegisterType((*TFProviderType)(nil), "TFProviderType")
	proto.RegisterType((*TFProviderTypeResponse)(nil), "TFProviderTypeResponse")
}

func init() { proto.RegisterFile("terraform.proto", fileDescriptor_fbef5fc442f72120) }

var fileDescriptor_fbef5fc442f72120 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x49, 0x2d, 0x2a,
	0x4a, 0x4c, 0xcb, 0x2f, 0xca, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x5a, 0xc2, 0xc8, 0xc5,
	0x17, 0xe2, 0x16, 0x50, 0x94, 0x5f, 0x96, 0x99, 0x92, 0x5a, 0x14, 0x52, 0x59, 0x90, 0x2a, 0xa4,
	0xc7, 0x25, 0x84, 0x2a, 0xe2, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x84,
	0x45, 0x06, 0x53, 0x7d, 0x58, 0x62, 0x51, 0xb1, 0x04, 0x13, 0x36, 0xf5, 0x20, 0x19, 0x21, 0x23,
	0x2e, 0x11, 0x54, 0x51, 0xf7, 0xcc, 0x92, 0xd0, 0xa2, 0x1c, 0x09, 0x66, 0xb0, 0x0e, 0xac, 0x72,
	0x4a, 0x25, 0x5c, 0x62, 0xa8, 0xe2, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x5a,
	0x5c, 0x02, 0xa8, 0x32, 0x9e, 0x2e, 0x50, 0xb7, 0x62, 0x88, 0xe3, 0xf0, 0x19, 0x13, 0x2e, 0x9f,
	0x19, 0x79, 0x71, 0x71, 0x86, 0xc0, 0xc2, 0x4b, 0xc8, 0x96, 0x4b, 0x10, 0x55, 0x89, 0x63, 0x4a,
	0x8a, 0x10, 0xbf, 0x1e, 0xaa, 0x98, 0x94, 0xb8, 0x1e, 0x76, 0x77, 0x26, 0xb1, 0x81, 0xc3, 0xdb,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xc0, 0xdb, 0x94, 0x89, 0x82, 0x01, 0x00, 0x00,
}
