// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vmdeploy.proto

package vmdeploy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/micro/go-api/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CIBase struct {
	CIID                 int32    `protobuf:"varint,1,opt,name=CIID,proto3" json:"CIID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CIBase) Reset()         { *m = CIBase{} }
func (m *CIBase) String() string { return proto.CompactTextString(m) }
func (*CIBase) ProtoMessage()    {}
func (*CIBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_vmdeploy_fc67694043378a28, []int{0}
}
func (m *CIBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CIBase.Unmarshal(m, b)
}
func (m *CIBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CIBase.Marshal(b, m, deterministic)
}
func (dst *CIBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CIBase.Merge(dst, src)
}
func (m *CIBase) XXX_Size() int {
	return xxx_messageInfo_CIBase.Size(m)
}
func (m *CIBase) XXX_DiscardUnknown() {
	xxx_messageInfo_CIBase.DiscardUnknown(m)
}

var xxx_messageInfo_CIBase proto.InternalMessageInfo

func (m *CIBase) GetCIID() int32 {
	if m != nil {
		return m.CIID
	}
	return 0
}

type DeploymentList struct {
	DeploymentList       []*DeploymentInfo `protobuf:"bytes,1,rep,name=DeploymentList,proto3" json:"DeploymentList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeploymentList) Reset()         { *m = DeploymentList{} }
func (m *DeploymentList) String() string { return proto.CompactTextString(m) }
func (*DeploymentList) ProtoMessage()    {}
func (*DeploymentList) Descriptor() ([]byte, []int) {
	return fileDescriptor_vmdeploy_fc67694043378a28, []int{1}
}
func (m *DeploymentList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentList.Unmarshal(m, b)
}
func (m *DeploymentList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentList.Marshal(b, m, deterministic)
}
func (dst *DeploymentList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentList.Merge(dst, src)
}
func (m *DeploymentList) XXX_Size() int {
	return xxx_messageInfo_DeploymentList.Size(m)
}
func (m *DeploymentList) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentList.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentList proto.InternalMessageInfo

func (m *DeploymentList) GetDeploymentList() []*DeploymentInfo {
	if m != nil {
		return m.DeploymentList
	}
	return nil
}

type DeploymentInfo struct {
	DeploymentId            string   `protobuf:"bytes,1,opt,name=DeploymentId,proto3" json:"DeploymentId,omitempty"`
	DeploymentType          int32    `protobuf:"varint,2,opt,name=DeploymentType,proto3" json:"DeploymentType,omitempty"`
	ParentProjectId         int32    `protobuf:"varint,3,opt,name=ParentProjectId,proto3" json:"ParentProjectId,omitempty"`
	DeploymentCiId          int32    `protobuf:"varint,4,opt,name=DeploymentCiId,proto3" json:"DeploymentCiId,omitempty"`
	DeploymentTempletId     int32    `protobuf:"varint,5,opt,name=DeploymentTempletId,proto3" json:"DeploymentTempletId,omitempty"`
	DeploymentName          string   `protobuf:"bytes,6,opt,name=DeploymentName,proto3" json:"DeploymentName,omitempty"`
	DeploymentTempletValue  string   `protobuf:"bytes,7,opt,name=DeploymentTempletValue,proto3" json:"DeploymentTempletValue,omitempty"`
	DeploymentStatus        int32    `protobuf:"varint,8,opt,name=DeploymentStatus,proto3" json:"DeploymentStatus,omitempty"`
	DeploymentReleaseNumber int32    `protobuf:"varint,9,opt,name=DeploymentReleaseNumber,proto3" json:"DeploymentReleaseNumber,omitempty"`
	CreateTime              string   `protobuf:"bytes,10,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime              string   `protobuf:"bytes,11,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	DeploymentTempletName   string   `protobuf:"bytes,12,opt,name=DeploymentTempletName,proto3" json:"DeploymentTempletName,omitempty"`
	DeploymentTempletOS     int32    `protobuf:"varint,13,opt,name=DeploymentTempletOS,proto3" json:"DeploymentTempletOS,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *DeploymentInfo) Reset()         { *m = DeploymentInfo{} }
func (m *DeploymentInfo) String() string { return proto.CompactTextString(m) }
func (*DeploymentInfo) ProtoMessage()    {}
func (*DeploymentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_vmdeploy_fc67694043378a28, []int{2}
}
func (m *DeploymentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentInfo.Unmarshal(m, b)
}
func (m *DeploymentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentInfo.Marshal(b, m, deterministic)
}
func (dst *DeploymentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentInfo.Merge(dst, src)
}
func (m *DeploymentInfo) XXX_Size() int {
	return xxx_messageInfo_DeploymentInfo.Size(m)
}
func (m *DeploymentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentInfo proto.InternalMessageInfo

func (m *DeploymentInfo) GetDeploymentId() string {
	if m != nil {
		return m.DeploymentId
	}
	return ""
}

func (m *DeploymentInfo) GetDeploymentType() int32 {
	if m != nil {
		return m.DeploymentType
	}
	return 0
}

func (m *DeploymentInfo) GetParentProjectId() int32 {
	if m != nil {
		return m.ParentProjectId
	}
	return 0
}

func (m *DeploymentInfo) GetDeploymentCiId() int32 {
	if m != nil {
		return m.DeploymentCiId
	}
	return 0
}

func (m *DeploymentInfo) GetDeploymentTempletId() int32 {
	if m != nil {
		return m.DeploymentTempletId
	}
	return 0
}

func (m *DeploymentInfo) GetDeploymentName() string {
	if m != nil {
		return m.DeploymentName
	}
	return ""
}

func (m *DeploymentInfo) GetDeploymentTempletValue() string {
	if m != nil {
		return m.DeploymentTempletValue
	}
	return ""
}

func (m *DeploymentInfo) GetDeploymentStatus() int32 {
	if m != nil {
		return m.DeploymentStatus
	}
	return 0
}

func (m *DeploymentInfo) GetDeploymentReleaseNumber() int32 {
	if m != nil {
		return m.DeploymentReleaseNumber
	}
	return 0
}

func (m *DeploymentInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *DeploymentInfo) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *DeploymentInfo) GetDeploymentTempletName() string {
	if m != nil {
		return m.DeploymentTempletName
	}
	return ""
}

func (m *DeploymentInfo) GetDeploymentTempletOS() int32 {
	if m != nil {
		return m.DeploymentTempletOS
	}
	return 0
}

type DeploymentID struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeploymentID) Reset()         { *m = DeploymentID{} }
func (m *DeploymentID) String() string { return proto.CompactTextString(m) }
func (*DeploymentID) ProtoMessage()    {}
func (*DeploymentID) Descriptor() ([]byte, []int) {
	return fileDescriptor_vmdeploy_fc67694043378a28, []int{3}
}
func (m *DeploymentID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentID.Unmarshal(m, b)
}
func (m *DeploymentID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentID.Marshal(b, m, deterministic)
}
func (dst *DeploymentID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentID.Merge(dst, src)
}
func (m *DeploymentID) XXX_Size() int {
	return xxx_messageInfo_DeploymentID.Size(m)
}
func (m *DeploymentID) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentID.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentID proto.InternalMessageInfo

func (m *DeploymentID) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type NewSingleDeploymentInfo struct {
	DeploymentType       int32    `protobuf:"varint,1,opt,name=DeploymentType,proto3" json:"DeploymentType,omitempty"`
	DeploymentValue      string   `protobuf:"bytes,2,opt,name=DeploymentValue,proto3" json:"DeploymentValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewSingleDeploymentInfo) Reset()         { *m = NewSingleDeploymentInfo{} }
func (m *NewSingleDeploymentInfo) String() string { return proto.CompactTextString(m) }
func (*NewSingleDeploymentInfo) ProtoMessage()    {}
func (*NewSingleDeploymentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_vmdeploy_fc67694043378a28, []int{4}
}
func (m *NewSingleDeploymentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewSingleDeploymentInfo.Unmarshal(m, b)
}
func (m *NewSingleDeploymentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewSingleDeploymentInfo.Marshal(b, m, deterministic)
}
func (dst *NewSingleDeploymentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewSingleDeploymentInfo.Merge(dst, src)
}
func (m *NewSingleDeploymentInfo) XXX_Size() int {
	return xxx_messageInfo_NewSingleDeploymentInfo.Size(m)
}
func (m *NewSingleDeploymentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NewSingleDeploymentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NewSingleDeploymentInfo proto.InternalMessageInfo

func (m *NewSingleDeploymentInfo) GetDeploymentType() int32 {
	if m != nil {
		return m.DeploymentType
	}
	return 0
}

func (m *NewSingleDeploymentInfo) GetDeploymentValue() string {
	if m != nil {
		return m.DeploymentValue
	}
	return ""
}

type SingleDeploymentInfo struct {
	DeploymentId            string   `protobuf:"bytes,1,opt,name=DeploymentId,proto3" json:"DeploymentId,omitempty"`
	DeploymentType          int32    `protobuf:"varint,2,opt,name=DeploymentType,proto3" json:"DeploymentType,omitempty"`
	DeploymentValue         string   `protobuf:"bytes,3,opt,name=DeploymentValue,proto3" json:"DeploymentValue,omitempty"`
	DeploymentName          string   `protobuf:"bytes,4,opt,name=DeploymentName,proto3" json:"DeploymentName,omitempty"`
	DeploymentStatus        int32    `protobuf:"varint,5,opt,name=DeploymentStatus,proto3" json:"DeploymentStatus,omitempty"`
	DeploymentReleaseNumber int32    `protobuf:"varint,6,opt,name=DeploymentReleaseNumber,proto3" json:"DeploymentReleaseNumber,omitempty"`
	CreateTime              string   `protobuf:"bytes,7,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime              string   `protobuf:"bytes,8,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *SingleDeploymentInfo) Reset()         { *m = SingleDeploymentInfo{} }
func (m *SingleDeploymentInfo) String() string { return proto.CompactTextString(m) }
func (*SingleDeploymentInfo) ProtoMessage()    {}
func (*SingleDeploymentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_vmdeploy_fc67694043378a28, []int{5}
}
func (m *SingleDeploymentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleDeploymentInfo.Unmarshal(m, b)
}
func (m *SingleDeploymentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleDeploymentInfo.Marshal(b, m, deterministic)
}
func (dst *SingleDeploymentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleDeploymentInfo.Merge(dst, src)
}
func (m *SingleDeploymentInfo) XXX_Size() int {
	return xxx_messageInfo_SingleDeploymentInfo.Size(m)
}
func (m *SingleDeploymentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleDeploymentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SingleDeploymentInfo proto.InternalMessageInfo

func (m *SingleDeploymentInfo) GetDeploymentId() string {
	if m != nil {
		return m.DeploymentId
	}
	return ""
}

func (m *SingleDeploymentInfo) GetDeploymentType() int32 {
	if m != nil {
		return m.DeploymentType
	}
	return 0
}

func (m *SingleDeploymentInfo) GetDeploymentValue() string {
	if m != nil {
		return m.DeploymentValue
	}
	return ""
}

func (m *SingleDeploymentInfo) GetDeploymentName() string {
	if m != nil {
		return m.DeploymentName
	}
	return ""
}

func (m *SingleDeploymentInfo) GetDeploymentStatus() int32 {
	if m != nil {
		return m.DeploymentStatus
	}
	return 0
}

func (m *SingleDeploymentInfo) GetDeploymentReleaseNumber() int32 {
	if m != nil {
		return m.DeploymentReleaseNumber
	}
	return 0
}

func (m *SingleDeploymentInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *SingleDeploymentInfo) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

type UpdateSingleDeploymentInfo struct {
	DeploymentId         string   `protobuf:"bytes,1,opt,name=DeploymentId,proto3" json:"DeploymentId,omitempty"`
	DeploymentType       int32    `protobuf:"varint,2,opt,name=DeploymentType,proto3" json:"DeploymentType,omitempty"`
	DeploymentValue      string   `protobuf:"bytes,3,opt,name=DeploymentValue,proto3" json:"DeploymentValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSingleDeploymentInfo) Reset()         { *m = UpdateSingleDeploymentInfo{} }
func (m *UpdateSingleDeploymentInfo) String() string { return proto.CompactTextString(m) }
func (*UpdateSingleDeploymentInfo) ProtoMessage()    {}
func (*UpdateSingleDeploymentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_vmdeploy_fc67694043378a28, []int{6}
}
func (m *UpdateSingleDeploymentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSingleDeploymentInfo.Unmarshal(m, b)
}
func (m *UpdateSingleDeploymentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSingleDeploymentInfo.Marshal(b, m, deterministic)
}
func (dst *UpdateSingleDeploymentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSingleDeploymentInfo.Merge(dst, src)
}
func (m *UpdateSingleDeploymentInfo) XXX_Size() int {
	return xxx_messageInfo_UpdateSingleDeploymentInfo.Size(m)
}
func (m *UpdateSingleDeploymentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSingleDeploymentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSingleDeploymentInfo proto.InternalMessageInfo

func (m *UpdateSingleDeploymentInfo) GetDeploymentId() string {
	if m != nil {
		return m.DeploymentId
	}
	return ""
}

func (m *UpdateSingleDeploymentInfo) GetDeploymentType() int32 {
	if m != nil {
		return m.DeploymentType
	}
	return 0
}

func (m *UpdateSingleDeploymentInfo) GetDeploymentValue() string {
	if m != nil {
		return m.DeploymentValue
	}
	return ""
}

type UpdateResult struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResult) Reset()         { *m = UpdateResult{} }
func (m *UpdateResult) String() string { return proto.CompactTextString(m) }
func (*UpdateResult) ProtoMessage()    {}
func (*UpdateResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_vmdeploy_fc67694043378a28, []int{7}
}
func (m *UpdateResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResult.Unmarshal(m, b)
}
func (m *UpdateResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResult.Marshal(b, m, deterministic)
}
func (dst *UpdateResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResult.Merge(dst, src)
}
func (m *UpdateResult) XXX_Size() int {
	return xxx_messageInfo_UpdateResult.Size(m)
}
func (m *UpdateResult) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResult.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResult proto.InternalMessageInfo

func (m *UpdateResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type SingleDeploymentID struct {
	DeploymentId         string   `protobuf:"bytes,1,opt,name=DeploymentId,proto3" json:"DeploymentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleDeploymentID) Reset()         { *m = SingleDeploymentID{} }
func (m *SingleDeploymentID) String() string { return proto.CompactTextString(m) }
func (*SingleDeploymentID) ProtoMessage()    {}
func (*SingleDeploymentID) Descriptor() ([]byte, []int) {
	return fileDescriptor_vmdeploy_fc67694043378a28, []int{8}
}
func (m *SingleDeploymentID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleDeploymentID.Unmarshal(m, b)
}
func (m *SingleDeploymentID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleDeploymentID.Marshal(b, m, deterministic)
}
func (dst *SingleDeploymentID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleDeploymentID.Merge(dst, src)
}
func (m *SingleDeploymentID) XXX_Size() int {
	return xxx_messageInfo_SingleDeploymentID.Size(m)
}
func (m *SingleDeploymentID) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleDeploymentID.DiscardUnknown(m)
}

var xxx_messageInfo_SingleDeploymentID proto.InternalMessageInfo

func (m *SingleDeploymentID) GetDeploymentId() string {
	if m != nil {
		return m.DeploymentId
	}
	return ""
}

type IfHostLinkDeployReq struct {
	HostId               int32    `protobuf:"varint,1,opt,name=HostId,proto3" json:"HostId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IfHostLinkDeployReq) Reset()         { *m = IfHostLinkDeployReq{} }
func (m *IfHostLinkDeployReq) String() string { return proto.CompactTextString(m) }
func (*IfHostLinkDeployReq) ProtoMessage()    {}
func (*IfHostLinkDeployReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_vmdeploy_fc67694043378a28, []int{9}
}
func (m *IfHostLinkDeployReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IfHostLinkDeployReq.Unmarshal(m, b)
}
func (m *IfHostLinkDeployReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IfHostLinkDeployReq.Marshal(b, m, deterministic)
}
func (dst *IfHostLinkDeployReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IfHostLinkDeployReq.Merge(dst, src)
}
func (m *IfHostLinkDeployReq) XXX_Size() int {
	return xxx_messageInfo_IfHostLinkDeployReq.Size(m)
}
func (m *IfHostLinkDeployReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IfHostLinkDeployReq.DiscardUnknown(m)
}

var xxx_messageInfo_IfHostLinkDeployReq proto.InternalMessageInfo

func (m *IfHostLinkDeployReq) GetHostId() int32 {
	if m != nil {
		return m.HostId
	}
	return 0
}

type IfHostLinkDeployRes struct {
	State                bool     `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IfHostLinkDeployRes) Reset()         { *m = IfHostLinkDeployRes{} }
func (m *IfHostLinkDeployRes) String() string { return proto.CompactTextString(m) }
func (*IfHostLinkDeployRes) ProtoMessage()    {}
func (*IfHostLinkDeployRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_vmdeploy_fc67694043378a28, []int{10}
}
func (m *IfHostLinkDeployRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IfHostLinkDeployRes.Unmarshal(m, b)
}
func (m *IfHostLinkDeployRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IfHostLinkDeployRes.Marshal(b, m, deterministic)
}
func (dst *IfHostLinkDeployRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IfHostLinkDeployRes.Merge(dst, src)
}
func (m *IfHostLinkDeployRes) XXX_Size() int {
	return xxx_messageInfo_IfHostLinkDeployRes.Size(m)
}
func (m *IfHostLinkDeployRes) XXX_DiscardUnknown() {
	xxx_messageInfo_IfHostLinkDeployRes.DiscardUnknown(m)
}

var xxx_messageInfo_IfHostLinkDeployRes proto.InternalMessageInfo

func (m *IfHostLinkDeployRes) GetState() bool {
	if m != nil {
		return m.State
	}
	return false
}

func init() {
	proto.RegisterType((*CIBase)(nil), "CIBase")
	proto.RegisterType((*DeploymentList)(nil), "DeploymentList")
	proto.RegisterType((*DeploymentInfo)(nil), "DeploymentInfo")
	proto.RegisterType((*DeploymentID)(nil), "DeploymentID")
	proto.RegisterType((*NewSingleDeploymentInfo)(nil), "NewSingleDeploymentInfo")
	proto.RegisterType((*SingleDeploymentInfo)(nil), "SingleDeploymentInfo")
	proto.RegisterType((*UpdateSingleDeploymentInfo)(nil), "UpdateSingleDeploymentInfo")
	proto.RegisterType((*UpdateResult)(nil), "UpdateResult")
	proto.RegisterType((*SingleDeploymentID)(nil), "SingleDeploymentID")
	proto.RegisterType((*IfHostLinkDeployReq)(nil), "IfHostLinkDeployReq")
	proto.RegisterType((*IfHostLinkDeployRes)(nil), "IfHostLinkDeployRes")
}

func init() { proto.RegisterFile("vmdeploy.proto", fileDescriptor_vmdeploy_fc67694043378a28) }

var fileDescriptor_vmdeploy_fc67694043378a28 = []byte{
	// 843 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xdd, 0x4e, 0xdb, 0x48,
	0x14, 0x4e, 0x42, 0xfe, 0x38, 0x10, 0x92, 0x9d, 0x84, 0xc4, 0x78, 0x11, 0x42, 0xa3, 0xd5, 0x2e,
	0xda, 0x15, 0xce, 0x2a, 0x8b, 0x80, 0xa5, 0x2d, 0x6d, 0x49, 0x90, 0xb0, 0x84, 0x02, 0x75, 0x68,
	0x2f, 0x7a, 0xe7, 0x24, 0x43, 0xea, 0x12, 0xc7, 0xc6, 0x76, 0x4a, 0xf3, 0x0a, 0xbd, 0xec, 0x83,
	0xf5, 0x01, 0xfa, 0x18, 0x7d, 0x82, 0xca, 0x63, 0x23, 0x3b, 0xe3, 0xb1, 0xea, 0x44, 0xbd, 0xe8,
	0x5d, 0xe6, 0x3b, 0xf3, 0x7d, 0xe7, 0xcc, 0xf1, 0x37, 0x3f, 0x81, 0x8d, 0x0f, 0xfa, 0x90, 0x98,
	0x63, 0x63, 0x26, 0x99, 0x96, 0xe1, 0x18, 0xe2, 0x5f, 0x23, 0xcd, 0x79, 0x37, 0xed, 0x4b, 0x03,
	0x43, 0x6f, 0xea, 0xda, 0xc0, 0x32, 0x9a, 0x23, 0x63, 0x5f, 0x35, 0xb5, 0x26, 0x0d, 0x37, 0x55,
	0x53, 0xf3, 0x26, 0xe2, 0x6d, 0xc8, 0xb7, 0xe5, 0x33, 0xd5, 0x26, 0x08, 0x41, 0xb6, 0x2d, 0xcb,
	0x1d, 0x21, 0xbd, 0x9b, 0xde, 0xcb, 0x29, 0xf4, 0x37, 0x96, 0x61, 0xa3, 0x43, 0x65, 0x75, 0x32,
	0x71, 0x2e, 0x35, 0xdb, 0x41, 0x47, 0x2c, 0x22, 0xa4, 0x77, 0x57, 0xf6, 0xd6, 0x5a, 0x65, 0x29,
	0x80, 0xe5, 0xc9, 0xad, 0xa1, 0x30, 0xd3, 0xf0, 0x97, 0x6c, 0x98, 0xe9, 0x4e, 0x41, 0x18, 0xd6,
	0x43, 0xc8, 0x90, 0x66, 0x5e, 0x55, 0xe6, 0x30, 0xf4, 0x67, 0x98, 0x75, 0x33, 0x33, 0x89, 0x90,
	0xa1, 0xf5, 0x31, 0x28, 0xda, 0x83, 0xf2, 0xb5, 0x6a, 0x91, 0x89, 0x73, 0x6d, 0x19, 0xef, 0xc9,
	0xc0, 0x95, 0x5b, 0xa1, 0x13, 0x59, 0x78, 0x5e, 0xb1, 0xad, 0xc9, 0x43, 0x21, 0xcb, 0x2a, 0xba,
	0x28, 0xfa, 0x17, 0xaa, 0xa1, 0x1c, 0x44, 0x37, 0xc7, 0xc4, 0x55, 0xcd, 0xd1, 0xc9, 0xbc, 0xd0,
	0xbc, 0x72, 0x57, 0xd5, 0x89, 0x90, 0xa7, 0x2b, 0x62, 0x50, 0x74, 0x08, 0xf5, 0x08, 0xfd, 0x8d,
	0x3a, 0x9e, 0x12, 0xa1, 0x40, 0xe7, 0xc7, 0x44, 0xd1, 0xdf, 0x50, 0x09, 0x22, 0x3d, 0x47, 0x75,
	0xa6, 0xb6, 0x50, 0xa4, 0xe5, 0x44, 0x70, 0x74, 0x0c, 0x8d, 0x00, 0x53, 0xc8, 0x98, 0xa8, 0x36,
	0xe9, 0x4e, 0xf5, 0x3e, 0xb1, 0x84, 0x55, 0x4a, 0x89, 0x0b, 0xa3, 0x1d, 0x80, 0xb6, 0x45, 0x54,
	0x87, 0xdc, 0x68, 0x3a, 0x11, 0x80, 0x56, 0x14, 0x42, 0xdc, 0xf8, 0x6b, 0x73, 0xf8, 0x18, 0x5f,
	0xf3, 0xe2, 0x01, 0x82, 0x0e, 0x60, 0x33, 0x52, 0x3f, 0x6d, 0xc6, 0x3a, 0x9d, 0xca, 0x0f, 0x72,
	0xbb, 0x7d, 0xd5, 0x13, 0x4a, 0x31, 0xdd, 0xbe, 0xea, 0xe1, 0x9d, 0x39, 0xf7, 0x74, 0xd0, 0x06,
	0x64, 0x7c, 0xf7, 0xae, 0x2a, 0x19, 0xb9, 0x83, 0xef, 0xa0, 0xd1, 0x25, 0x0f, 0x3d, 0x6d, 0x32,
	0x1a, 0x13, 0xc6, 0x78, 0x51, 0x53, 0xa5, 0xe3, 0x4c, 0x15, 0x20, 0xde, 0x17, 0xca, 0x50, 0x7d,
	0x16, 0xc6, 0x5f, 0x33, 0x50, 0xe3, 0xa6, 0xfa, 0xc9, 0x1e, 0x67, 0xcb, 0x59, 0xe1, 0x96, 0xc3,
	0x71, 0x62, 0x96, 0xeb, 0x44, 0x9e, 0xa3, 0x72, 0x8b, 0x3b, 0x2a, 0xbf, 0x88, 0xa3, 0x0a, 0x3f,
	0x70, 0x54, 0x91, 0x75, 0x14, 0xfe, 0x9c, 0x06, 0xd1, 0x1b, 0xfe, 0x3a, 0x2d, 0xc6, 0x7f, 0xc0,
	0xba, 0x57, 0x93, 0x42, 0xec, 0xe9, 0xd8, 0x41, 0x35, 0xc8, 0x9d, 0x5b, 0x96, 0x61, 0xf9, 0xe9,
	0xbd, 0x01, 0x3e, 0x06, 0x14, 0xa9, 0xb9, 0x93, 0xa4, 0x62, 0xbc, 0x0f, 0x55, 0xf9, 0xf6, 0xc2,
	0xb0, 0x9d, 0x4b, 0x6d, 0x72, 0xe7, 0x45, 0x14, 0x72, 0x8f, 0xea, 0x90, 0x77, 0x41, 0x9f, 0x94,
	0x53, 0xfc, 0x11, 0xfe, 0x87, 0x37, 0xdd, 0x76, 0xab, 0xb2, 0x1d, 0xd5, 0xf1, 0x0c, 0x5e, 0x54,
	0xbc, 0x41, 0xeb, 0x53, 0x11, 0x20, 0x48, 0x86, 0x4e, 0xa0, 0xfa, 0x6a, 0x4a, 0xac, 0x19, 0x73,
	0xd4, 0x97, 0xa5, 0x91, 0x21, 0xb9, 0x37, 0x85, 0x42, 0xee, 0xa7, 0xc4, 0x76, 0xc4, 0x4a, 0x00,
	0xd8, 0xa6, 0x31, 0xb1, 0x09, 0x4e, 0xa1, 0x03, 0x28, 0x75, 0xc9, 0x43, 0x48, 0x2c, 0x11, 0xeb,
	0x08, 0x2a, 0x5e, 0xf3, 0x96, 0x20, 0x76, 0xc8, 0x98, 0x2c, 0x4e, 0x3c, 0x84, 0x32, 0xb3, 0xc6,
	0x64, 0xbc, 0x27, 0x50, 0x63, 0x13, 0xba, 0x5d, 0x4e, 0x46, 0x3e, 0x86, 0xdf, 0x5e, 0x0e, 0x87,
	0x4b, 0x32, 0xfd, 0x3d, 0xb4, 0x68, 0xc1, 0xcf, 0x41, 0x98, 0x4f, 0xe8, 0xeb, 0x5c, 0x1a, 0xa3,
	0x64, 0x02, 0x6d, 0xd8, 0xe6, 0x0a, 0x5c, 0x68, 0xb6, 0x63, 0x58, 0xb3, 0x64, 0x22, 0xa7, 0xd0,
	0x60, 0xda, 0xed, 0x79, 0x33, 0xe9, 0xfa, 0xff, 0x07, 0xd4, 0x73, 0x0c, 0x73, 0x99, 0xd6, 0xbd,
	0x80, 0xad, 0xc8, 0x41, 0xb4, 0x58, 0xf2, 0x13, 0xa8, 0x7a, 0xee, 0x74, 0x69, 0x9e, 0xd6, 0x8d,
	0x3a, 0x4a, 0xea, 0x33, 0x41, 0x31, 0x07, 0x74, 0xed, 0x6d, 0x8d, 0xd9, 0x50, 0x05, 0xc9, 0x7b,
	0x6a, 0x89, 0xe1, 0xc7, 0x12, 0x7d, 0x1c, 0xb9, 0x3c, 0xf4, 0xc8, 0x0b, 0x7d, 0xf1, 0x52, 0xf8,
	0x55, 0xd5, 0x11, 0xd9, 0x47, 0x16, 0x5d, 0x6d, 0x85, 0xdd, 0xf7, 0xa8, 0x26, 0x71, 0x4e, 0x0e,
	0x91, 0x87, 0xda, 0x38, 0xd5, 0x3a, 0x83, 0x82, 0x7f, 0xa9, 0xba, 0xbb, 0x8b, 0x56, 0xe0, 0x8f,
	0x13, 0x77, 0xac, 0xf5, 0x2d, 0x0b, 0x15, 0xf6, 0x9c, 0x73, 0xdb, 0xc8, 0xb9, 0x80, 0x93, 0xb5,
	0xf1, 0x19, 0xd4, 0xf9, 0x27, 0x7e, 0x32, 0xfa, 0x53, 0xd8, 0xa4, 0x0b, 0x59, 0x8e, 0x7d, 0x0a,
	0x0d, 0xdf, 0x37, 0xcb, 0xf1, 0xcf, 0x61, 0x27, 0x86, 0xbf, 0xe8, 0x1e, 0xf2, 0x65, 0xde, 0xaa,
	0xfd, 0xbe, 0xf6, 0x71, 0xd1, 0x32, 0x64, 0xa8, 0x2b, 0xe6, 0x80, 0xf7, 0x09, 0x04, 0x29, 0xe6,
	0x65, 0x24, 0x56, 0xa5, 0xe8, 0x75, 0x45, 0xa5, 0xb6, 0x14, 0x73, 0x10, 0xf3, 0x45, 0x7e, 0x97,
	0xe2, 0x2f, 0x67, 0xb1, 0x24, 0x85, 0x6f, 0x49, 0x9c, 0x42, 0x17, 0xc1, 0x06, 0x89, 0x28, 0xf1,
	0xb2, 0x8b, 0x9b, 0x12, 0x4f, 0x18, 0xa7, 0xfa, 0x79, 0xfa, 0x0f, 0xe6, 0xbf, 0xef, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xcf, 0x5d, 0xe1, 0x88, 0xfc, 0x0c, 0x00, 0x00,
}
