// Code generated by protoc-gen-go. DO NOT EDIT.
// source: namespace.proto

package namespace

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateNamespaceRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Cpu                  string   `protobuf:"bytes,2,opt,name=Cpu,proto3" json:"Cpu,omitempty"`
	Memory               string   `protobuf:"bytes,3,opt,name=Memory,proto3" json:"Memory,omitempty"`
	Pod                  string   `protobuf:"bytes,4,opt,name=Pod,proto3" json:"Pod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNamespaceRequest) Reset()         { *m = CreateNamespaceRequest{} }
func (m *CreateNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNamespaceRequest) ProtoMessage()    {}
func (*CreateNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{0}
}
func (m *CreateNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNamespaceRequest.Unmarshal(m, b)
}
func (m *CreateNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNamespaceRequest.Marshal(b, m, deterministic)
}
func (dst *CreateNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNamespaceRequest.Merge(dst, src)
}
func (m *CreateNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNamespaceRequest.Size(m)
}
func (m *CreateNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNamespaceRequest proto.InternalMessageInfo

func (m *CreateNamespaceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateNamespaceRequest) GetCpu() string {
	if m != nil {
		return m.Cpu
	}
	return ""
}

func (m *CreateNamespaceRequest) GetMemory() string {
	if m != nil {
		return m.Memory
	}
	return ""
}

func (m *CreateNamespaceRequest) GetPod() string {
	if m != nil {
		return m.Pod
	}
	return ""
}

type CreateNamespaceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNamespaceResponse) Reset()         { *m = CreateNamespaceResponse{} }
func (m *CreateNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNamespaceResponse) ProtoMessage()    {}
func (*CreateNamespaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{1}
}
func (m *CreateNamespaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNamespaceResponse.Unmarshal(m, b)
}
func (m *CreateNamespaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNamespaceResponse.Marshal(b, m, deterministic)
}
func (dst *CreateNamespaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNamespaceResponse.Merge(dst, src)
}
func (m *CreateNamespaceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateNamespaceResponse.Size(m)
}
func (m *CreateNamespaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNamespaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNamespaceResponse proto.InternalMessageInfo

type DeleteNamespaceRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNamespaceRequest) Reset()         { *m = DeleteNamespaceRequest{} }
func (m *DeleteNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteNamespaceRequest) ProtoMessage()    {}
func (*DeleteNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{2}
}
func (m *DeleteNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNamespaceRequest.Unmarshal(m, b)
}
func (m *DeleteNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNamespaceRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNamespaceRequest.Merge(dst, src)
}
func (m *DeleteNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteNamespaceRequest.Size(m)
}
func (m *DeleteNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNamespaceRequest proto.InternalMessageInfo

func (m *DeleteNamespaceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteNamespaceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNamespaceResponse) Reset()         { *m = DeleteNamespaceResponse{} }
func (m *DeleteNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteNamespaceResponse) ProtoMessage()    {}
func (*DeleteNamespaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{3}
}
func (m *DeleteNamespaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNamespaceResponse.Unmarshal(m, b)
}
func (m *DeleteNamespaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNamespaceResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteNamespaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNamespaceResponse.Merge(dst, src)
}
func (m *DeleteNamespaceResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteNamespaceResponse.Size(m)
}
func (m *DeleteNamespaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNamespaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNamespaceResponse proto.InternalMessageInfo

type GetNamespaceRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNamespaceRequest) Reset()         { *m = GetNamespaceRequest{} }
func (m *GetNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*GetNamespaceRequest) ProtoMessage()    {}
func (*GetNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{4}
}
func (m *GetNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNamespaceRequest.Unmarshal(m, b)
}
func (m *GetNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNamespaceRequest.Marshal(b, m, deterministic)
}
func (dst *GetNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNamespaceRequest.Merge(dst, src)
}
func (m *GetNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_GetNamespaceRequest.Size(m)
}
func (m *GetNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNamespaceRequest proto.InternalMessageInfo

func (m *GetNamespaceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetNamespaceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNamespaceResponse) Reset()         { *m = GetNamespaceResponse{} }
func (m *GetNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*GetNamespaceResponse) ProtoMessage()    {}
func (*GetNamespaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{5}
}
func (m *GetNamespaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNamespaceResponse.Unmarshal(m, b)
}
func (m *GetNamespaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNamespaceResponse.Marshal(b, m, deterministic)
}
func (dst *GetNamespaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNamespaceResponse.Merge(dst, src)
}
func (m *GetNamespaceResponse) XXX_Size() int {
	return xxx_messageInfo_GetNamespaceResponse.Size(m)
}
func (m *GetNamespaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNamespaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNamespaceResponse proto.InternalMessageInfo

type AllowToIPBlockRequest struct {
	Parentproject        string   `protobuf:"bytes,1,opt,name=Parentproject,proto3" json:"Parentproject,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	IPBlock              string   `protobuf:"bytes,3,opt,name=IPBlock,proto3" json:"IPBlock,omitempty"`
	Ports                []int32  `protobuf:"varint,4,rep,packed,name=Ports,proto3" json:"Ports,omitempty"`
	Protocol             string   `protobuf:"bytes,5,opt,name=Protocol,proto3" json:"Protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllowToIPBlockRequest) Reset()         { *m = AllowToIPBlockRequest{} }
func (m *AllowToIPBlockRequest) String() string { return proto.CompactTextString(m) }
func (*AllowToIPBlockRequest) ProtoMessage()    {}
func (*AllowToIPBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{6}
}
func (m *AllowToIPBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllowToIPBlockRequest.Unmarshal(m, b)
}
func (m *AllowToIPBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllowToIPBlockRequest.Marshal(b, m, deterministic)
}
func (dst *AllowToIPBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllowToIPBlockRequest.Merge(dst, src)
}
func (m *AllowToIPBlockRequest) XXX_Size() int {
	return xxx_messageInfo_AllowToIPBlockRequest.Size(m)
}
func (m *AllowToIPBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllowToIPBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllowToIPBlockRequest proto.InternalMessageInfo

func (m *AllowToIPBlockRequest) GetParentproject() string {
	if m != nil {
		return m.Parentproject
	}
	return ""
}

func (m *AllowToIPBlockRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AllowToIPBlockRequest) GetIPBlock() string {
	if m != nil {
		return m.IPBlock
	}
	return ""
}

func (m *AllowToIPBlockRequest) GetPorts() []int32 {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *AllowToIPBlockRequest) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

type AllowToIPBlockResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllowToIPBlockResponse) Reset()         { *m = AllowToIPBlockResponse{} }
func (m *AllowToIPBlockResponse) String() string { return proto.CompactTextString(m) }
func (*AllowToIPBlockResponse) ProtoMessage()    {}
func (*AllowToIPBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{7}
}
func (m *AllowToIPBlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllowToIPBlockResponse.Unmarshal(m, b)
}
func (m *AllowToIPBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllowToIPBlockResponse.Marshal(b, m, deterministic)
}
func (dst *AllowToIPBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllowToIPBlockResponse.Merge(dst, src)
}
func (m *AllowToIPBlockResponse) XXX_Size() int {
	return xxx_messageInfo_AllowToIPBlockResponse.Size(m)
}
func (m *AllowToIPBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllowToIPBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllowToIPBlockResponse proto.InternalMessageInfo

type AllowFromIPBlockRequest struct {
	Parentproject        string   `protobuf:"bytes,1,opt,name=Parentproject,proto3" json:"Parentproject,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	IPBlock              string   `protobuf:"bytes,3,opt,name=IPBlock,proto3" json:"IPBlock,omitempty"`
	Ports                []int32  `protobuf:"varint,4,rep,packed,name=Ports,proto3" json:"Ports,omitempty"`
	Protocol             string   `protobuf:"bytes,5,opt,name=Protocol,proto3" json:"Protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllowFromIPBlockRequest) Reset()         { *m = AllowFromIPBlockRequest{} }
func (m *AllowFromIPBlockRequest) String() string { return proto.CompactTextString(m) }
func (*AllowFromIPBlockRequest) ProtoMessage()    {}
func (*AllowFromIPBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{8}
}
func (m *AllowFromIPBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllowFromIPBlockRequest.Unmarshal(m, b)
}
func (m *AllowFromIPBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllowFromIPBlockRequest.Marshal(b, m, deterministic)
}
func (dst *AllowFromIPBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllowFromIPBlockRequest.Merge(dst, src)
}
func (m *AllowFromIPBlockRequest) XXX_Size() int {
	return xxx_messageInfo_AllowFromIPBlockRequest.Size(m)
}
func (m *AllowFromIPBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllowFromIPBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllowFromIPBlockRequest proto.InternalMessageInfo

func (m *AllowFromIPBlockRequest) GetParentproject() string {
	if m != nil {
		return m.Parentproject
	}
	return ""
}

func (m *AllowFromIPBlockRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AllowFromIPBlockRequest) GetIPBlock() string {
	if m != nil {
		return m.IPBlock
	}
	return ""
}

func (m *AllowFromIPBlockRequest) GetPorts() []int32 {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *AllowFromIPBlockRequest) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

type AllowFromIPBlockResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllowFromIPBlockResponse) Reset()         { *m = AllowFromIPBlockResponse{} }
func (m *AllowFromIPBlockResponse) String() string { return proto.CompactTextString(m) }
func (*AllowFromIPBlockResponse) ProtoMessage()    {}
func (*AllowFromIPBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{9}
}
func (m *AllowFromIPBlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllowFromIPBlockResponse.Unmarshal(m, b)
}
func (m *AllowFromIPBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllowFromIPBlockResponse.Marshal(b, m, deterministic)
}
func (dst *AllowFromIPBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllowFromIPBlockResponse.Merge(dst, src)
}
func (m *AllowFromIPBlockResponse) XXX_Size() int {
	return xxx_messageInfo_AllowFromIPBlockResponse.Size(m)
}
func (m *AllowFromIPBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllowFromIPBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllowFromIPBlockResponse proto.InternalMessageInfo

type AllowToNamespaceRequest struct {
	Parentproject        string   `protobuf:"bytes,1,opt,name=Parentproject,proto3" json:"Parentproject,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Namespace            string   `protobuf:"bytes,3,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	Ports                []int32  `protobuf:"varint,4,rep,packed,name=Ports,proto3" json:"Ports,omitempty"`
	Protocol             string   `protobuf:"bytes,5,opt,name=Protocol,proto3" json:"Protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllowToNamespaceRequest) Reset()         { *m = AllowToNamespaceRequest{} }
func (m *AllowToNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*AllowToNamespaceRequest) ProtoMessage()    {}
func (*AllowToNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{10}
}
func (m *AllowToNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllowToNamespaceRequest.Unmarshal(m, b)
}
func (m *AllowToNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllowToNamespaceRequest.Marshal(b, m, deterministic)
}
func (dst *AllowToNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllowToNamespaceRequest.Merge(dst, src)
}
func (m *AllowToNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_AllowToNamespaceRequest.Size(m)
}
func (m *AllowToNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllowToNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllowToNamespaceRequest proto.InternalMessageInfo

func (m *AllowToNamespaceRequest) GetParentproject() string {
	if m != nil {
		return m.Parentproject
	}
	return ""
}

func (m *AllowToNamespaceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AllowToNamespaceRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *AllowToNamespaceRequest) GetPorts() []int32 {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *AllowToNamespaceRequest) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

type AllowToNamespaceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllowToNamespaceResponse) Reset()         { *m = AllowToNamespaceResponse{} }
func (m *AllowToNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*AllowToNamespaceResponse) ProtoMessage()    {}
func (*AllowToNamespaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{11}
}
func (m *AllowToNamespaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllowToNamespaceResponse.Unmarshal(m, b)
}
func (m *AllowToNamespaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllowToNamespaceResponse.Marshal(b, m, deterministic)
}
func (dst *AllowToNamespaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllowToNamespaceResponse.Merge(dst, src)
}
func (m *AllowToNamespaceResponse) XXX_Size() int {
	return xxx_messageInfo_AllowToNamespaceResponse.Size(m)
}
func (m *AllowToNamespaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllowToNamespaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllowToNamespaceResponse proto.InternalMessageInfo

type AllowFromNamespaceRequest struct {
	Parentproject        string   `protobuf:"bytes,1,opt,name=Parentproject,proto3" json:"Parentproject,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Namespace            string   `protobuf:"bytes,3,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	Ports                []int32  `protobuf:"varint,4,rep,packed,name=Ports,proto3" json:"Ports,omitempty"`
	Protocol             string   `protobuf:"bytes,5,opt,name=Protocol,proto3" json:"Protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllowFromNamespaceRequest) Reset()         { *m = AllowFromNamespaceRequest{} }
func (m *AllowFromNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*AllowFromNamespaceRequest) ProtoMessage()    {}
func (*AllowFromNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{12}
}
func (m *AllowFromNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllowFromNamespaceRequest.Unmarshal(m, b)
}
func (m *AllowFromNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllowFromNamespaceRequest.Marshal(b, m, deterministic)
}
func (dst *AllowFromNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllowFromNamespaceRequest.Merge(dst, src)
}
func (m *AllowFromNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_AllowFromNamespaceRequest.Size(m)
}
func (m *AllowFromNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllowFromNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllowFromNamespaceRequest proto.InternalMessageInfo

func (m *AllowFromNamespaceRequest) GetParentproject() string {
	if m != nil {
		return m.Parentproject
	}
	return ""
}

func (m *AllowFromNamespaceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AllowFromNamespaceRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *AllowFromNamespaceRequest) GetPorts() []int32 {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *AllowFromNamespaceRequest) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

type AllowFromNamespaceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllowFromNamespaceResponse) Reset()         { *m = AllowFromNamespaceResponse{} }
func (m *AllowFromNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*AllowFromNamespaceResponse) ProtoMessage()    {}
func (*AllowFromNamespaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{13}
}
func (m *AllowFromNamespaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllowFromNamespaceResponse.Unmarshal(m, b)
}
func (m *AllowFromNamespaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllowFromNamespaceResponse.Marshal(b, m, deterministic)
}
func (dst *AllowFromNamespaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllowFromNamespaceResponse.Merge(dst, src)
}
func (m *AllowFromNamespaceResponse) XXX_Size() int {
	return xxx_messageInfo_AllowFromNamespaceResponse.Size(m)
}
func (m *AllowFromNamespaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllowFromNamespaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllowFromNamespaceResponse proto.InternalMessageInfo

type DeleteExistingRuleRequest struct {
	Parentproject        string   `protobuf:"bytes,1,opt,name=Parentproject,proto3" json:"Parentproject,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteExistingRuleRequest) Reset()         { *m = DeleteExistingRuleRequest{} }
func (m *DeleteExistingRuleRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteExistingRuleRequest) ProtoMessage()    {}
func (*DeleteExistingRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{14}
}
func (m *DeleteExistingRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteExistingRuleRequest.Unmarshal(m, b)
}
func (m *DeleteExistingRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteExistingRuleRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteExistingRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteExistingRuleRequest.Merge(dst, src)
}
func (m *DeleteExistingRuleRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteExistingRuleRequest.Size(m)
}
func (m *DeleteExistingRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteExistingRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteExistingRuleRequest proto.InternalMessageInfo

func (m *DeleteExistingRuleRequest) GetParentproject() string {
	if m != nil {
		return m.Parentproject
	}
	return ""
}

func (m *DeleteExistingRuleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteExistingRuleResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteExistingRuleResponse) Reset()         { *m = DeleteExistingRuleResponse{} }
func (m *DeleteExistingRuleResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteExistingRuleResponse) ProtoMessage()    {}
func (*DeleteExistingRuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{15}
}
func (m *DeleteExistingRuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteExistingRuleResponse.Unmarshal(m, b)
}
func (m *DeleteExistingRuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteExistingRuleResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteExistingRuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteExistingRuleResponse.Merge(dst, src)
}
func (m *DeleteExistingRuleResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteExistingRuleResponse.Size(m)
}
func (m *DeleteExistingRuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteExistingRuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteExistingRuleResponse proto.InternalMessageInfo

type Quota struct {
	MaxCPU               string   `protobuf:"bytes,1,opt,name=MaxCPU,proto3" json:"MaxCPU,omitempty"`
	MaxMemory            string   `protobuf:"bytes,2,opt,name=MaxMemory,proto3" json:"MaxMemory,omitempty"`
	MaxPods              string   `protobuf:"bytes,3,opt,name=MaxPods,proto3" json:"MaxPods,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Quota) Reset()         { *m = Quota{} }
func (m *Quota) String() string { return proto.CompactTextString(m) }
func (*Quota) ProtoMessage()    {}
func (*Quota) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{16}
}
func (m *Quota) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quota.Unmarshal(m, b)
}
func (m *Quota) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quota.Marshal(b, m, deterministic)
}
func (dst *Quota) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quota.Merge(dst, src)
}
func (m *Quota) XXX_Size() int {
	return xxx_messageInfo_Quota.Size(m)
}
func (m *Quota) XXX_DiscardUnknown() {
	xxx_messageInfo_Quota.DiscardUnknown(m)
}

var xxx_messageInfo_Quota proto.InternalMessageInfo

func (m *Quota) GetMaxCPU() string {
	if m != nil {
		return m.MaxCPU
	}
	return ""
}

func (m *Quota) GetMaxMemory() string {
	if m != nil {
		return m.MaxMemory
	}
	return ""
}

func (m *Quota) GetMaxPods() string {
	if m != nil {
		return m.MaxPods
	}
	return ""
}

type GetQuotaRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQuotaRequest) Reset()         { *m = GetQuotaRequest{} }
func (m *GetQuotaRequest) String() string { return proto.CompactTextString(m) }
func (*GetQuotaRequest) ProtoMessage()    {}
func (*GetQuotaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{17}
}
func (m *GetQuotaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuotaRequest.Unmarshal(m, b)
}
func (m *GetQuotaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuotaRequest.Marshal(b, m, deterministic)
}
func (dst *GetQuotaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuotaRequest.Merge(dst, src)
}
func (m *GetQuotaRequest) XXX_Size() int {
	return xxx_messageInfo_GetQuotaRequest.Size(m)
}
func (m *GetQuotaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuotaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuotaRequest proto.InternalMessageInfo

func (m *GetQuotaRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetQuotaResponse struct {
	Quota                *Quota   `protobuf:"bytes,1,opt,name=Quota,proto3" json:"Quota,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQuotaResponse) Reset()         { *m = GetQuotaResponse{} }
func (m *GetQuotaResponse) String() string { return proto.CompactTextString(m) }
func (*GetQuotaResponse) ProtoMessage()    {}
func (*GetQuotaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{18}
}
func (m *GetQuotaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuotaResponse.Unmarshal(m, b)
}
func (m *GetQuotaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuotaResponse.Marshal(b, m, deterministic)
}
func (dst *GetQuotaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuotaResponse.Merge(dst, src)
}
func (m *GetQuotaResponse) XXX_Size() int {
	return xxx_messageInfo_GetQuotaResponse.Size(m)
}
func (m *GetQuotaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuotaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuotaResponse proto.InternalMessageInfo

func (m *GetQuotaResponse) GetQuota() *Quota {
	if m != nil {
		return m.Quota
	}
	return nil
}

type ApplyQuotaRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Quota                *Quota   `protobuf:"bytes,2,opt,name=Quota,proto3" json:"Quota,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyQuotaRequest) Reset()         { *m = ApplyQuotaRequest{} }
func (m *ApplyQuotaRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyQuotaRequest) ProtoMessage()    {}
func (*ApplyQuotaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{19}
}
func (m *ApplyQuotaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyQuotaRequest.Unmarshal(m, b)
}
func (m *ApplyQuotaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyQuotaRequest.Marshal(b, m, deterministic)
}
func (dst *ApplyQuotaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyQuotaRequest.Merge(dst, src)
}
func (m *ApplyQuotaRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyQuotaRequest.Size(m)
}
func (m *ApplyQuotaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyQuotaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyQuotaRequest proto.InternalMessageInfo

func (m *ApplyQuotaRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ApplyQuotaRequest) GetQuota() *Quota {
	if m != nil {
		return m.Quota
	}
	return nil
}

type ApplyQuotaResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyQuotaResponse) Reset()         { *m = ApplyQuotaResponse{} }
func (m *ApplyQuotaResponse) String() string { return proto.CompactTextString(m) }
func (*ApplyQuotaResponse) ProtoMessage()    {}
func (*ApplyQuotaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{20}
}
func (m *ApplyQuotaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyQuotaResponse.Unmarshal(m, b)
}
func (m *ApplyQuotaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyQuotaResponse.Marshal(b, m, deterministic)
}
func (dst *ApplyQuotaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyQuotaResponse.Merge(dst, src)
}
func (m *ApplyQuotaResponse) XXX_Size() int {
	return xxx_messageInfo_ApplyQuotaResponse.Size(m)
}
func (m *ApplyQuotaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyQuotaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyQuotaResponse proto.InternalMessageInfo

type Config struct {
	ConfigName           string   `protobuf:"bytes,1,opt,name=ConfigName,proto3" json:"ConfigName,omitempty"`
	ConfigFileName       string   `protobuf:"bytes,2,opt,name=ConfigFileName,proto3" json:"ConfigFileName,omitempty"`
	ConfigFileContent    string   `protobuf:"bytes,3,opt,name=ConfigFileContent,proto3" json:"ConfigFileContent,omitempty"`
	NameSpace            string   `protobuf:"bytes,4,opt,name=NameSpace,proto3" json:"NameSpace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{21}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetConfigName() string {
	if m != nil {
		return m.ConfigName
	}
	return ""
}

func (m *Config) GetConfigFileName() string {
	if m != nil {
		return m.ConfigFileName
	}
	return ""
}

func (m *Config) GetConfigFileContent() string {
	if m != nil {
		return m.ConfigFileContent
	}
	return ""
}

func (m *Config) GetNameSpace() string {
	if m != nil {
		return m.NameSpace
	}
	return ""
}

type CreateOrUpdateConfigRequest struct {
	Config               *Config  `protobuf:"bytes,1,opt,name=Config,proto3" json:"Config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrUpdateConfigRequest) Reset()         { *m = CreateOrUpdateConfigRequest{} }
func (m *CreateOrUpdateConfigRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrUpdateConfigRequest) ProtoMessage()    {}
func (*CreateOrUpdateConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{22}
}
func (m *CreateOrUpdateConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrUpdateConfigRequest.Unmarshal(m, b)
}
func (m *CreateOrUpdateConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrUpdateConfigRequest.Marshal(b, m, deterministic)
}
func (dst *CreateOrUpdateConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrUpdateConfigRequest.Merge(dst, src)
}
func (m *CreateOrUpdateConfigRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrUpdateConfigRequest.Size(m)
}
func (m *CreateOrUpdateConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrUpdateConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrUpdateConfigRequest proto.InternalMessageInfo

func (m *CreateOrUpdateConfigRequest) GetConfig() *Config {
	if m != nil {
		return m.Config
	}
	return nil
}

type CreateOrUpdateConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrUpdateConfigResponse) Reset()         { *m = CreateOrUpdateConfigResponse{} }
func (m *CreateOrUpdateConfigResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrUpdateConfigResponse) ProtoMessage()    {}
func (*CreateOrUpdateConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{23}
}
func (m *CreateOrUpdateConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrUpdateConfigResponse.Unmarshal(m, b)
}
func (m *CreateOrUpdateConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrUpdateConfigResponse.Marshal(b, m, deterministic)
}
func (dst *CreateOrUpdateConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrUpdateConfigResponse.Merge(dst, src)
}
func (m *CreateOrUpdateConfigResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrUpdateConfigResponse.Size(m)
}
func (m *CreateOrUpdateConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrUpdateConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrUpdateConfigResponse proto.InternalMessageInfo

type DeleteConfigRequest struct {
	Config               *Config  `protobuf:"bytes,1,opt,name=Config,proto3" json:"Config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteConfigRequest) Reset()         { *m = DeleteConfigRequest{} }
func (m *DeleteConfigRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteConfigRequest) ProtoMessage()    {}
func (*DeleteConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{24}
}
func (m *DeleteConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteConfigRequest.Unmarshal(m, b)
}
func (m *DeleteConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteConfigRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteConfigRequest.Merge(dst, src)
}
func (m *DeleteConfigRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteConfigRequest.Size(m)
}
func (m *DeleteConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteConfigRequest proto.InternalMessageInfo

func (m *DeleteConfigRequest) GetConfig() *Config {
	if m != nil {
		return m.Config
	}
	return nil
}

type DeleteConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteConfigResponse) Reset()         { *m = DeleteConfigResponse{} }
func (m *DeleteConfigResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteConfigResponse) ProtoMessage()    {}
func (*DeleteConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_namespace_fb69335c4d620a7b, []int{25}
}
func (m *DeleteConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteConfigResponse.Unmarshal(m, b)
}
func (m *DeleteConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteConfigResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteConfigResponse.Merge(dst, src)
}
func (m *DeleteConfigResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteConfigResponse.Size(m)
}
func (m *DeleteConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteConfigResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateNamespaceRequest)(nil), "CreateNamespaceRequest")
	proto.RegisterType((*CreateNamespaceResponse)(nil), "CreateNamespaceResponse")
	proto.RegisterType((*DeleteNamespaceRequest)(nil), "DeleteNamespaceRequest")
	proto.RegisterType((*DeleteNamespaceResponse)(nil), "DeleteNamespaceResponse")
	proto.RegisterType((*GetNamespaceRequest)(nil), "GetNamespaceRequest")
	proto.RegisterType((*GetNamespaceResponse)(nil), "GetNamespaceResponse")
	proto.RegisterType((*AllowToIPBlockRequest)(nil), "AllowToIPBlockRequest")
	proto.RegisterType((*AllowToIPBlockResponse)(nil), "AllowToIPBlockResponse")
	proto.RegisterType((*AllowFromIPBlockRequest)(nil), "AllowFromIPBlockRequest")
	proto.RegisterType((*AllowFromIPBlockResponse)(nil), "AllowFromIPBlockResponse")
	proto.RegisterType((*AllowToNamespaceRequest)(nil), "AllowToNamespaceRequest")
	proto.RegisterType((*AllowToNamespaceResponse)(nil), "AllowToNamespaceResponse")
	proto.RegisterType((*AllowFromNamespaceRequest)(nil), "AllowFromNamespaceRequest")
	proto.RegisterType((*AllowFromNamespaceResponse)(nil), "AllowFromNamespaceResponse")
	proto.RegisterType((*DeleteExistingRuleRequest)(nil), "DeleteExistingRuleRequest")
	proto.RegisterType((*DeleteExistingRuleResponse)(nil), "DeleteExistingRuleResponse")
	proto.RegisterType((*Quota)(nil), "Quota")
	proto.RegisterType((*GetQuotaRequest)(nil), "GetQuotaRequest")
	proto.RegisterType((*GetQuotaResponse)(nil), "GetQuotaResponse")
	proto.RegisterType((*ApplyQuotaRequest)(nil), "ApplyQuotaRequest")
	proto.RegisterType((*ApplyQuotaResponse)(nil), "ApplyQuotaResponse")
	proto.RegisterType((*Config)(nil), "Config")
	proto.RegisterType((*CreateOrUpdateConfigRequest)(nil), "CreateOrUpdateConfigRequest")
	proto.RegisterType((*CreateOrUpdateConfigResponse)(nil), "CreateOrUpdateConfigResponse")
	proto.RegisterType((*DeleteConfigRequest)(nil), "DeleteConfigRequest")
	proto.RegisterType((*DeleteConfigResponse)(nil), "DeleteConfigResponse")
}

func init() { proto.RegisterFile("namespace.proto", fileDescriptor_namespace_fb69335c4d620a7b) }

var fileDescriptor_namespace_fb69335c4d620a7b = []byte{
	// 736 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x41, 0x6f, 0xd3, 0x4c,
	0x10, 0x75, 0xda, 0x24, 0x6d, 0xe7, 0xfb, 0x68, 0xd3, 0xa9, 0xeb, 0x38, 0xdb, 0x50, 0x2a, 0x0b,
	0x50, 0x91, 0xaa, 0x15, 0x14, 0x09, 0x4e, 0x20, 0x95, 0xd0, 0x56, 0x3d, 0x94, 0x9a, 0xd0, 0x88,
	0xb3, 0x49, 0x96, 0x12, 0x70, 0xbc, 0xc6, 0x76, 0x44, 0xfa, 0x5f, 0x40, 0x1c, 0x10, 0x3f, 0x8a,
	0x7f, 0x83, 0x6c, 0xaf, 0x63, 0xc7, 0x5e, 0x87, 0x42, 0x2f, 0xbd, 0x79, 0x66, 0xd7, 0xcf, 0x6f,
	0x26, 0x33, 0xef, 0x05, 0xd6, 0x1c, 0x6b, 0xc4, 0x7c, 0xd7, 0xea, 0x33, 0xea, 0x7a, 0x3c, 0xe0,
	0xc6, 0x07, 0xd0, 0x3a, 0x1e, 0xb3, 0x02, 0xf6, 0x2a, 0x39, 0xe8, 0xb2, 0xcf, 0x63, 0xe6, 0x07,
	0x88, 0x50, 0x0d, 0x73, 0x7a, 0x65, 0xa7, 0xb2, 0xbb, 0xd2, 0x8d, 0x9e, 0xb1, 0x01, 0x8b, 0x1d,
	0x77, 0xac, 0x2f, 0x44, 0xa9, 0xf0, 0x11, 0x35, 0xa8, 0x9f, 0xb2, 0x11, 0xf7, 0x2e, 0xf5, 0xc5,
	0x28, 0x29, 0xa2, 0xf0, 0xa6, 0xc9, 0x07, 0x7a, 0x35, 0xbe, 0x69, 0xf2, 0x81, 0xd1, 0x82, 0x66,
	0xe1, 0x4b, 0xbe, 0xcb, 0x1d, 0x9f, 0x19, 0x7b, 0xa0, 0xbd, 0x64, 0x36, 0xbb, 0x1a, 0x89, 0x10,
	0xa8, 0x70, 0x5b, 0x00, 0x3d, 0x80, 0x8d, 0x63, 0x16, 0x5c, 0x09, 0x45, 0x03, 0x75, 0xf6, 0xaa,
	0x80, 0xf8, 0x56, 0x81, 0xcd, 0x03, 0xdb, 0xe6, 0x5f, 0xce, 0xf9, 0x89, 0xf9, 0xc2, 0xe6, 0xfd,
	0x4f, 0x09, 0xca, 0x5d, 0xb8, 0x65, 0x5a, 0x1e, 0x73, 0x02, 0xd7, 0xe3, 0x1f, 0x59, 0x3f, 0x10,
	0x70, 0xb3, 0xc9, 0xe9, 0xb7, 0x16, 0x32, 0x6d, 0xd3, 0x61, 0x49, 0x60, 0x89, 0x2e, 0x25, 0x21,
	0xaa, 0x50, 0x33, 0xb9, 0x17, 0xf8, 0x7a, 0x75, 0x67, 0x71, 0xb7, 0xd6, 0x8d, 0x03, 0x24, 0xb0,
	0x6c, 0x86, 0xbf, 0x4e, 0x9f, 0xdb, 0x7a, 0x2d, 0x7a, 0x61, 0x1a, 0x1b, 0x3a, 0x68, 0x79, 0x7a,
	0x82, 0xf9, 0xf7, 0x0a, 0x34, 0xa3, 0xa3, 0x23, 0x8f, 0x8f, 0x6e, 0x24, 0x77, 0x02, 0x7a, 0x91,
	0xa0, 0x60, 0xff, 0x23, 0x61, 0x7f, 0xce, 0x0b, 0xbf, 0xdf, 0xbf, 0xb3, 0x6f, 0xc3, 0xca, 0x14,
	0x4d, 0xf0, 0x4f, 0x13, 0xd7, 0xa8, 0x60, 0x86, 0xa4, 0xa8, 0xe0, 0x67, 0x05, 0x5a, 0xd3, 0xf2,
	0x6e, 0x70, 0x0d, 0x6d, 0x20, 0x32, 0x9a, 0xa2, 0x8a, 0x1e, 0xb4, 0xe2, 0xed, 0x3a, 0x9c, 0x0c,
	0xfd, 0x60, 0xe8, 0x5c, 0x74, 0xc7, 0xf6, 0xf5, 0x8b, 0x08, 0x3f, 0x2a, 0x83, 0x15, 0x1f, 0x7d,
	0x0b, 0xb5, 0xd7, 0x63, 0x1e, 0x58, 0x91, 0x9c, 0x58, 0x93, 0x8e, 0xd9, 0x13, 0xc8, 0x22, 0x0a,
	0x7b, 0x70, 0x6a, 0x4d, 0x84, 0xd2, 0xc4, 0xb8, 0x69, 0x22, 0x9c, 0xd1, 0x53, 0x6b, 0x62, 0xf2,
	0x81, 0x9f, 0xcc, 0xa8, 0x08, 0x8d, 0x7b, 0xb0, 0x76, 0xcc, 0x82, 0x08, 0x7b, 0x9e, 0x18, 0x3c,
	0x84, 0x46, 0x7a, 0x2d, 0xe6, 0x84, 0x6d, 0xc1, 0x29, 0xba, 0xf8, 0xdf, 0x7e, 0x9d, 0xc6, 0xc7,
	0x71, 0xd2, 0x38, 0x84, 0xf5, 0x03, 0xd7, 0xb5, 0x2f, 0xff, 0x04, 0x9d, 0xc2, 0x2c, 0xc8, 0x60,
	0x54, 0xc0, 0x2c, 0x8c, 0x68, 0xc7, 0xd7, 0x0a, 0xd4, 0x3b, 0xdc, 0x79, 0x3f, 0xbc, 0xc0, 0x6d,
	0x80, 0xf8, 0x29, 0x03, 0x9c, 0xc9, 0xe0, 0x7d, 0x58, 0x8d, 0xa3, 0xa3, 0xa1, 0xcd, 0x32, 0x5d,
	0xcf, 0x65, 0x71, 0x0f, 0xd6, 0xd3, 0x4c, 0x87, 0x3b, 0x01, 0x73, 0x02, 0xd1, 0xac, 0xe2, 0x41,
	0x32, 0x72, 0x6f, 0xa2, 0x91, 0xab, 0xa6, 0x23, 0x17, 0x25, 0x8c, 0xe7, 0xb0, 0x15, 0x2b, 0xf9,
	0x99, 0xd7, 0x73, 0x07, 0x56, 0xc0, 0x62, 0x80, 0xa4, 0x0b, 0x77, 0x12, 0xf2, 0xa2, 0x73, 0x4b,
	0x54, 0x9c, 0x8b, 0xb4, 0xb1, 0x0d, 0x6d, 0xf9, 0xfb, 0xa2, 0xfc, 0x27, 0xb0, 0x11, 0xcf, 0xca,
	0x5f, 0xe2, 0x6a, 0xa0, 0xce, 0xbe, 0x17, 0xe3, 0xed, 0xff, 0xaa, 0x67, 0x36, 0x08, 0x8f, 0x60,
	0x2d, 0xe7, 0x43, 0xd8, 0xa4, 0x72, 0x0f, 0x24, 0x3a, 0x2d, 0xb3, 0x2c, 0x25, 0xc4, 0xc9, 0xd9,
	0x10, 0x36, 0xa9, 0xdc, 0xc6, 0x88, 0x4e, 0xcb, 0x1c, 0x4b, 0xc1, 0x67, 0xf0, 0x7f, 0xd6, 0x88,
	0x50, 0xa5, 0x12, 0x0b, 0x23, 0x9b, 0x54, 0xea, 0x56, 0x0a, 0x76, 0x60, 0x75, 0xd6, 0x0f, 0x50,
	0xa3, 0x52, 0xff, 0x22, 0x4d, 0x5a, 0x62, 0x1c, 0x0a, 0x9e, 0x40, 0x23, 0x2f, 0xcc, 0xa8, 0xd3,
	0x12, 0x33, 0x21, 0x2d, 0x5a, 0xaa, 0xe2, 0x29, 0x54, 0x46, 0x21, 0x13, 0xa8, 0xa2, 0xb2, 0x27,
	0x50, 0x32, 0x39, 0x55, 0xf0, 0x0c, 0xb0, 0x28, 0x54, 0x48, 0x68, 0xa9, 0xc8, 0x92, 0x2d, 0x3a,
	0x47, 0xd9, 0x22, 0xc0, 0xa2, 0x08, 0x21, 0xa1, 0xa5, 0x82, 0x47, 0xb6, 0xe8, 0x1c, 0xd5, 0x52,
	0xf0, 0x11, 0x2c, 0x27, 0xba, 0x81, 0x0d, 0x9a, 0x53, 0x1a, 0xb2, 0x4e, 0xf3, 0xa2, 0x62, 0x28,
	0xf8, 0x14, 0x20, 0xdd, 0x78, 0x44, 0x5a, 0x50, 0x11, 0xb2, 0x41, 0x25, 0x92, 0xa0, 0x60, 0x0f,
	0x54, 0xd9, 0xd6, 0x60, 0x9b, 0xce, 0x59, 0x46, 0x72, 0x9b, 0xce, 0x5d, 0xb5, 0x68, 0xfc, 0xb2,
	0x4b, 0x83, 0x2a, 0x95, 0xec, 0x1e, 0xd9, 0xa4, 0xb2, 0xcd, 0x32, 0x94, 0x77, 0xf5, 0xe8, 0x6f,
	0xe4, 0xe3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xad, 0x00, 0x0f, 0x11, 0x59, 0x0a, 0x00, 0x00,
}
