// Code generated by protoc-gen-go. DO NOT EDIT.
// source: softwareConfig.proto

/*
Package softwareConfig is a generated protocol buffer package.

It is generated from these files:
	softwareConfig.proto

It has these top-level messages:
	SoftWareConfigListRequest
	SoftWareConfigNode
	SoftWareConfigListResponse
*/
package softwareConfig

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 查询软件配置列表
type SoftWareConfigListRequest struct {
	Page         int32 `protobuf:"varint,2,opt,name=Page" json:"Page,omitempty"`
	PageSize     int32 `protobuf:"varint,3,opt,name=PageSize" json:"PageSize,omitempty"`
	SoftwareType int32 `protobuf:"varint,4,opt,name=SoftwareType" json:"SoftwareType,omitempty"`
}

func (m *SoftWareConfigListRequest) Reset()                    { *m = SoftWareConfigListRequest{} }
func (m *SoftWareConfigListRequest) String() string            { return proto.CompactTextString(m) }
func (*SoftWareConfigListRequest) ProtoMessage()               {}
func (*SoftWareConfigListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SoftWareConfigListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SoftWareConfigListRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *SoftWareConfigListRequest) GetSoftwareType() int32 {
	if m != nil {
		return m.SoftwareType
	}
	return 0
}

type SoftWareConfigNode struct {
	Id               int32  `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	SoftwareName     string `protobuf:"bytes,3,opt,name=SoftwareName" json:"SoftwareName,omitempty"`
	SoftwareType     int32  `protobuf:"varint,4,opt,name=SoftwareType" json:"SoftwareType,omitempty"`
	SoftwareVersions string `protobuf:"bytes,5,opt,name=SoftwareVersions" json:"SoftwareVersions,omitempty"`
	CreateTime       string `protobuf:"bytes,6,opt,name=CreateTime" json:"CreateTime,omitempty"`
}

func (m *SoftWareConfigNode) Reset()                    { *m = SoftWareConfigNode{} }
func (m *SoftWareConfigNode) String() string            { return proto.CompactTextString(m) }
func (*SoftWareConfigNode) ProtoMessage()               {}
func (*SoftWareConfigNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SoftWareConfigNode) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SoftWareConfigNode) GetSoftwareName() string {
	if m != nil {
		return m.SoftwareName
	}
	return ""
}

func (m *SoftWareConfigNode) GetSoftwareType() int32 {
	if m != nil {
		return m.SoftwareType
	}
	return 0
}

func (m *SoftWareConfigNode) GetSoftwareVersions() string {
	if m != nil {
		return m.SoftwareVersions
	}
	return ""
}

func (m *SoftWareConfigNode) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

type SoftWareConfigListResponse struct {
	List []*SoftWareConfigNode `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	Sum  int32                 `protobuf:"varint,2,opt,name=Sum" json:"Sum,omitempty"`
}

func (m *SoftWareConfigListResponse) Reset()                    { *m = SoftWareConfigListResponse{} }
func (m *SoftWareConfigListResponse) String() string            { return proto.CompactTextString(m) }
func (*SoftWareConfigListResponse) ProtoMessage()               {}
func (*SoftWareConfigListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SoftWareConfigListResponse) GetList() []*SoftWareConfigNode {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *SoftWareConfigListResponse) GetSum() int32 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func init() {
	proto.RegisterType((*SoftWareConfigListRequest)(nil), "SoftWareConfigListRequest")
	proto.RegisterType((*SoftWareConfigNode)(nil), "SoftWareConfigNode")
	proto.RegisterType((*SoftWareConfigListResponse)(nil), "SoftWareConfigListResponse")
}

func init() { proto.RegisterFile("softwareConfig.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xcd, 0x9f, 0x16, 0x1d, 0xa5, 0x94, 0xd1, 0xc3, 0x1a, 0x41, 0xca, 0x5e, 0x2c, 0x1e,
	0x72, 0xa8, 0x4f, 0x20, 0x3d, 0x15, 0xa4, 0x48, 0xb6, 0xd8, 0x73, 0x24, 0x93, 0xb2, 0x87, 0x64,
	0x62, 0x76, 0x8b, 0xe8, 0x93, 0xf9, 0x78, 0x92, 0x6d, 0x2d, 0x5d, 0x6a, 0xa1, 0xa7, 0xcc, 0xfc,
	0xf2, 0xed, 0xf7, 0xed, 0xce, 0xc0, 0x8d, 0xe1, 0xd2, 0x7e, 0xe6, 0x2d, 0x4d, 0xb9, 0x2e, 0xf5,
	0x2a, 0x6d, 0x5a, 0xb6, 0x2c, 0x19, 0x6e, 0x15, 0x97, 0x76, 0xb9, 0xe3, 0x2f, 0xda, 0xd8, 0x8c,
	0x3e, 0xd6, 0x64, 0x2c, 0x22, 0xc4, 0xaf, 0xf9, 0x8a, 0x44, 0x38, 0x0a, 0xc6, 0xbd, 0xcc, 0xd5,
	0x98, 0xc0, 0x79, 0xf7, 0x55, 0xfa, 0x9b, 0x44, 0xe4, 0xf8, 0xae, 0x47, 0x09, 0x57, 0x6a, 0x1b,
	0xb2, 0xf8, 0x6a, 0x48, 0xc4, 0xee, 0xbf, 0xc7, 0xe4, 0x4f, 0x00, 0xe8, 0x27, 0xce, 0xb9, 0x20,
	0x1c, 0x40, 0x38, 0x2b, 0x44, 0xe0, 0x0e, 0x84, 0xb3, 0x62, 0xdf, 0x6a, 0x9e, 0x57, 0x9b, 0xa8,
	0x8b, 0xcc, 0x63, 0xa7, 0xc4, 0xe1, 0x23, 0x0c, 0xff, 0xfa, 0x37, 0x6a, 0x8d, 0xe6, 0xda, 0x88,
	0x9e, 0xf3, 0x3a, 0xe0, 0x78, 0x0f, 0x30, 0x6d, 0x29, 0xb7, 0xb4, 0xd0, 0x15, 0x89, 0xbe, 0x53,
	0xed, 0x11, 0xb9, 0x84, 0xe4, 0xbf, 0x59, 0x99, 0x86, 0x6b, 0x43, 0xf8, 0x00, 0x71, 0xd7, 0x8b,
	0x60, 0x14, 0x8d, 0x2f, 0x27, 0xd7, 0xe9, 0xe1, 0x23, 0x33, 0x27, 0xc0, 0x21, 0x44, 0x6a, 0x5d,
	0x6d, 0x87, 0xda, 0x95, 0x13, 0x05, 0x03, 0x5f, 0x8d, 0xcf, 0x1b, 0x33, 0x4c, 0xd2, 0xa3, 0xdb,
	0x49, 0xee, 0xd2, 0xe3, 0xb7, 0x91, 0x67, 0xef, 0x7d, 0xb7, 0xe0, 0xa7, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x71, 0x3d, 0x69, 0x3d, 0xf8, 0x01, 0x00, 0x00,
}
