// Code generated by protoc-gen-go. DO NOT EDIT.
// source: namespace.proto

package namespace

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/micro/go-api/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ParentIDList struct {
	ParentProjectID      []int32  `protobuf:"varint,1,rep,packed,name=ParentProjectID,proto3" json:"ParentProjectID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParentIDList) Reset()         { *m = ParentIDList{} }
func (m *ParentIDList) String() string { return proto.CompactTextString(m) }
func (*ParentIDList) ProtoMessage()    {}
func (*ParentIDList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecb1e126f615f5dd, []int{0}
}

func (m *ParentIDList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParentIDList.Unmarshal(m, b)
}
func (m *ParentIDList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParentIDList.Marshal(b, m, deterministic)
}
func (m *ParentIDList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParentIDList.Merge(m, src)
}
func (m *ParentIDList) XXX_Size() int {
	return xxx_messageInfo_ParentIDList.Size(m)
}
func (m *ParentIDList) XXX_DiscardUnknown() {
	xxx_messageInfo_ParentIDList.DiscardUnknown(m)
}

var xxx_messageInfo_ParentIDList proto.InternalMessageInfo

func (m *ParentIDList) GetParentProjectID() []int32 {
	if m != nil {
		return m.ParentProjectID
	}
	return nil
}

type FuzzyListParentReq struct {
	ParentProjectType    int32    `protobuf:"varint,1,opt,name=ParentProjectType,proto3" json:"ParentProjectType,omitempty"`
	ParentProjectEnvType int32    `protobuf:"varint,2,opt,name=ParentProjectEnvType,proto3" json:"ParentProjectEnvType,omitempty"`
	ParentProjectName    string   `protobuf:"bytes,3,opt,name=ParentProjectName,proto3" json:"ParentProjectName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FuzzyListParentReq) Reset()         { *m = FuzzyListParentReq{} }
func (m *FuzzyListParentReq) String() string { return proto.CompactTextString(m) }
func (*FuzzyListParentReq) ProtoMessage()    {}
func (*FuzzyListParentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecb1e126f615f5dd, []int{1}
}

func (m *FuzzyListParentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FuzzyListParentReq.Unmarshal(m, b)
}
func (m *FuzzyListParentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FuzzyListParentReq.Marshal(b, m, deterministic)
}
func (m *FuzzyListParentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FuzzyListParentReq.Merge(m, src)
}
func (m *FuzzyListParentReq) XXX_Size() int {
	return xxx_messageInfo_FuzzyListParentReq.Size(m)
}
func (m *FuzzyListParentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FuzzyListParentReq.DiscardUnknown(m)
}

var xxx_messageInfo_FuzzyListParentReq proto.InternalMessageInfo

func (m *FuzzyListParentReq) GetParentProjectType() int32 {
	if m != nil {
		return m.ParentProjectType
	}
	return 0
}

func (m *FuzzyListParentReq) GetParentProjectEnvType() int32 {
	if m != nil {
		return m.ParentProjectEnvType
	}
	return 0
}

func (m *FuzzyListParentReq) GetParentProjectName() string {
	if m != nil {
		return m.ParentProjectName
	}
	return ""
}

type FuzzyListAuthorizeParentReq struct {
	ParentProjectType    int32    `protobuf:"varint,1,opt,name=ParentProjectType,proto3" json:"ParentProjectType,omitempty"`
	ParentProjectEnvType int32    `protobuf:"varint,2,opt,name=ParentProjectEnvType,proto3" json:"ParentProjectEnvType,omitempty"`
	ParentProjectName    string   `protobuf:"bytes,3,opt,name=ParentProjectName,proto3" json:"ParentProjectName,omitempty"`
	UserID               int32    `protobuf:"varint,4,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FuzzyListAuthorizeParentReq) Reset()         { *m = FuzzyListAuthorizeParentReq{} }
func (m *FuzzyListAuthorizeParentReq) String() string { return proto.CompactTextString(m) }
func (*FuzzyListAuthorizeParentReq) ProtoMessage()    {}
func (*FuzzyListAuthorizeParentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecb1e126f615f5dd, []int{2}
}

func (m *FuzzyListAuthorizeParentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FuzzyListAuthorizeParentReq.Unmarshal(m, b)
}
func (m *FuzzyListAuthorizeParentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FuzzyListAuthorizeParentReq.Marshal(b, m, deterministic)
}
func (m *FuzzyListAuthorizeParentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FuzzyListAuthorizeParentReq.Merge(m, src)
}
func (m *FuzzyListAuthorizeParentReq) XXX_Size() int {
	return xxx_messageInfo_FuzzyListAuthorizeParentReq.Size(m)
}
func (m *FuzzyListAuthorizeParentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FuzzyListAuthorizeParentReq.DiscardUnknown(m)
}

var xxx_messageInfo_FuzzyListAuthorizeParentReq proto.InternalMessageInfo

func (m *FuzzyListAuthorizeParentReq) GetParentProjectType() int32 {
	if m != nil {
		return m.ParentProjectType
	}
	return 0
}

func (m *FuzzyListAuthorizeParentReq) GetParentProjectEnvType() int32 {
	if m != nil {
		return m.ParentProjectEnvType
	}
	return 0
}

func (m *FuzzyListAuthorizeParentReq) GetParentProjectName() string {
	if m != nil {
		return m.ParentProjectName
	}
	return ""
}

func (m *FuzzyListAuthorizeParentReq) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type FuzzyListParentGroupReq struct {
	ParentProjectGroupName string   `protobuf:"bytes,1,opt,name=ParentProjectGroupName,proto3" json:"ParentProjectGroupName,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *FuzzyListParentGroupReq) Reset()         { *m = FuzzyListParentGroupReq{} }
func (m *FuzzyListParentGroupReq) String() string { return proto.CompactTextString(m) }
func (*FuzzyListParentGroupReq) ProtoMessage()    {}
func (*FuzzyListParentGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecb1e126f615f5dd, []int{3}
}

func (m *FuzzyListParentGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FuzzyListParentGroupReq.Unmarshal(m, b)
}
func (m *FuzzyListParentGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FuzzyListParentGroupReq.Marshal(b, m, deterministic)
}
func (m *FuzzyListParentGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FuzzyListParentGroupReq.Merge(m, src)
}
func (m *FuzzyListParentGroupReq) XXX_Size() int {
	return xxx_messageInfo_FuzzyListParentGroupReq.Size(m)
}
func (m *FuzzyListParentGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FuzzyListParentGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_FuzzyListParentGroupReq proto.InternalMessageInfo

func (m *FuzzyListParentGroupReq) GetParentProjectGroupName() string {
	if m != nil {
		return m.ParentProjectGroupName
	}
	return ""
}

type ParentGroupList struct {
	GroupList            []*ParentProjectGroupInfo `protobuf:"bytes,1,rep,name=GroupList,proto3" json:"GroupList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ParentGroupList) Reset()         { *m = ParentGroupList{} }
func (m *ParentGroupList) String() string { return proto.CompactTextString(m) }
func (*ParentGroupList) ProtoMessage()    {}
func (*ParentGroupList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecb1e126f615f5dd, []int{4}
}

func (m *ParentGroupList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParentGroupList.Unmarshal(m, b)
}
func (m *ParentGroupList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParentGroupList.Marshal(b, m, deterministic)
}
func (m *ParentGroupList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParentGroupList.Merge(m, src)
}
func (m *ParentGroupList) XXX_Size() int {
	return xxx_messageInfo_ParentGroupList.Size(m)
}
func (m *ParentGroupList) XXX_DiscardUnknown() {
	xxx_messageInfo_ParentGroupList.DiscardUnknown(m)
}

var xxx_messageInfo_ParentGroupList proto.InternalMessageInfo

func (m *ParentGroupList) GetGroupList() []*ParentProjectGroupInfo {
	if m != nil {
		return m.GroupList
	}
	return nil
}

type ParentID struct {
	ParentProjectID      int32    `protobuf:"varint,1,opt,name=ParentProjectID,proto3" json:"ParentProjectID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParentID) Reset()         { *m = ParentID{} }
func (m *ParentID) String() string { return proto.CompactTextString(m) }
func (*ParentID) ProtoMessage()    {}
func (*ParentID) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecb1e126f615f5dd, []int{5}
}

func (m *ParentID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParentID.Unmarshal(m, b)
}
func (m *ParentID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParentID.Marshal(b, m, deterministic)
}
func (m *ParentID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParentID.Merge(m, src)
}
func (m *ParentID) XXX_Size() int {
	return xxx_messageInfo_ParentID.Size(m)
}
func (m *ParentID) XXX_DiscardUnknown() {
	xxx_messageInfo_ParentID.DiscardUnknown(m)
}

var xxx_messageInfo_ParentID proto.InternalMessageInfo

func (m *ParentID) GetParentProjectID() int32 {
	if m != nil {
		return m.ParentProjectID
	}
	return 0
}

type GroupID struct {
	GroupID              int32    `protobuf:"varint,1,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupID) Reset()         { *m = GroupID{} }
func (m *GroupID) String() string { return proto.CompactTextString(m) }
func (*GroupID) ProtoMessage()    {}
func (*GroupID) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecb1e126f615f5dd, []int{6}
}

func (m *GroupID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupID.Unmarshal(m, b)
}
func (m *GroupID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupID.Marshal(b, m, deterministic)
}
func (m *GroupID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupID.Merge(m, src)
}
func (m *GroupID) XXX_Size() int {
	return xxx_messageInfo_GroupID.Size(m)
}
func (m *GroupID) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupID.DiscardUnknown(m)
}

var xxx_messageInfo_GroupID proto.InternalMessageInfo

func (m *GroupID) GetGroupID() int32 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

type GetParentByGroupReq struct {
	ParentProjectGroupID int32    `protobuf:"varint,1,opt,name=ParentProjectGroupID,proto3" json:"ParentProjectGroupID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetParentByGroupReq) Reset()         { *m = GetParentByGroupReq{} }
func (m *GetParentByGroupReq) String() string { return proto.CompactTextString(m) }
func (*GetParentByGroupReq) ProtoMessage()    {}
func (*GetParentByGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecb1e126f615f5dd, []int{7}
}

func (m *GetParentByGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetParentByGroupReq.Unmarshal(m, b)
}
func (m *GetParentByGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetParentByGroupReq.Marshal(b, m, deterministic)
}
func (m *GetParentByGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetParentByGroupReq.Merge(m, src)
}
func (m *GetParentByGroupReq) XXX_Size() int {
	return xxx_messageInfo_GetParentByGroupReq.Size(m)
}
func (m *GetParentByGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetParentByGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetParentByGroupReq proto.InternalMessageInfo

func (m *GetParentByGroupReq) GetParentProjectGroupID() int32 {
	if m != nil {
		return m.ParentProjectGroupID
	}
	return 0
}

type GetParentByGroupRes struct {
	TestParentProjectID  int32    `protobuf:"varint,1,opt,name=TestParentProjectID,proto3" json:"TestParentProjectID,omitempty"`
	ProParentProjectID   int32    `protobuf:"varint,2,opt,name=ProParentProjectID,proto3" json:"ProParentProjectID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetParentByGroupRes) Reset()         { *m = GetParentByGroupRes{} }
func (m *GetParentByGroupRes) String() string { return proto.CompactTextString(m) }
func (*GetParentByGroupRes) ProtoMessage()    {}
func (*GetParentByGroupRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecb1e126f615f5dd, []int{8}
}

func (m *GetParentByGroupRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetParentByGroupRes.Unmarshal(m, b)
}
func (m *GetParentByGroupRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetParentByGroupRes.Marshal(b, m, deterministic)
}
func (m *GetParentByGroupRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetParentByGroupRes.Merge(m, src)
}
func (m *GetParentByGroupRes) XXX_Size() int {
	return xxx_messageInfo_GetParentByGroupRes.Size(m)
}
func (m *GetParentByGroupRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetParentByGroupRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetParentByGroupRes proto.InternalMessageInfo

func (m *GetParentByGroupRes) GetTestParentProjectID() int32 {
	if m != nil {
		return m.TestParentProjectID
	}
	return 0
}

func (m *GetParentByGroupRes) GetProParentProjectID() int32 {
	if m != nil {
		return m.ProParentProjectID
	}
	return 0
}

type ParentItem struct {
	ParentProjectID        int32    `protobuf:"varint,1,opt,name=ParentProjectID,proto3" json:"ParentProjectID,omitempty"`
	ParentProjectName      string   `protobuf:"bytes,2,opt,name=ParentProjectName,proto3" json:"ParentProjectName,omitempty"`
	ParentProjectK8SName   string   `protobuf:"bytes,3,opt,name=ParentProjectK8sName,proto3" json:"ParentProjectK8sName,omitempty"`
	ParentProjectType      int32    `protobuf:"varint,4,opt,name=ParentProjectType,proto3" json:"ParentProjectType,omitempty"`
	GroupID                int32    `protobuf:"varint,5,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	CPU                    string   `protobuf:"bytes,6,opt,name=CPU,proto3" json:"CPU,omitempty"`
	Memory                 string   `protobuf:"bytes,7,opt,name=Memory,proto3" json:"Memory,omitempty"`
	Pods                   string   `protobuf:"bytes,8,opt,name=Pods,proto3" json:"Pods,omitempty"`
	GroupName              string   `protobuf:"bytes,9,opt,name=GroupName,proto3" json:"GroupName,omitempty"`
	EnvType                int32    `protobuf:"varint,10,opt,name=EnvType,proto3" json:"EnvType,omitempty"`
	GroupK8SName           string   `protobuf:"bytes,11,opt,name=GroupK8sName,proto3" json:"GroupK8sName,omitempty"`
	ParentProjectGroupID   int32    `protobuf:"varint,12,opt,name=ParentProjectGroupID,proto3" json:"ParentProjectGroupID,omitempty"`
	ParentProjectGroupName string   `protobuf:"bytes,13,opt,name=ParentProjectGroupName,proto3" json:"ParentProjectGroupName,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *ParentItem) Reset()         { *m = ParentItem{} }
func (m *ParentItem) String() string { return proto.CompactTextString(m) }
func (*ParentItem) ProtoMessage()    {}
func (*ParentItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecb1e126f615f5dd, []int{9}
}

func (m *ParentItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParentItem.Unmarshal(m, b)
}
func (m *ParentItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParentItem.Marshal(b, m, deterministic)
}
func (m *ParentItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParentItem.Merge(m, src)
}
func (m *ParentItem) XXX_Size() int {
	return xxx_messageInfo_ParentItem.Size(m)
}
func (m *ParentItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ParentItem.DiscardUnknown(m)
}

var xxx_messageInfo_ParentItem proto.InternalMessageInfo

func (m *ParentItem) GetParentProjectID() int32 {
	if m != nil {
		return m.ParentProjectID
	}
	return 0
}

func (m *ParentItem) GetParentProjectName() string {
	if m != nil {
		return m.ParentProjectName
	}
	return ""
}

func (m *ParentItem) GetParentProjectK8SName() string {
	if m != nil {
		return m.ParentProjectK8SName
	}
	return ""
}

func (m *ParentItem) GetParentProjectType() int32 {
	if m != nil {
		return m.ParentProjectType
	}
	return 0
}

func (m *ParentItem) GetGroupID() int32 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *ParentItem) GetCPU() string {
	if m != nil {
		return m.CPU
	}
	return ""
}

func (m *ParentItem) GetMemory() string {
	if m != nil {
		return m.Memory
	}
	return ""
}

func (m *ParentItem) GetPods() string {
	if m != nil {
		return m.Pods
	}
	return ""
}

func (m *ParentItem) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *ParentItem) GetEnvType() int32 {
	if m != nil {
		return m.EnvType
	}
	return 0
}

func (m *ParentItem) GetGroupK8SName() string {
	if m != nil {
		return m.GroupK8SName
	}
	return ""
}

func (m *ParentItem) GetParentProjectGroupID() int32 {
	if m != nil {
		return m.ParentProjectGroupID
	}
	return 0
}

func (m *ParentItem) GetParentProjectGroupName() string {
	if m != nil {
		return m.ParentProjectGroupName
	}
	return ""
}

type EmptyReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyReq) Reset()         { *m = EmptyReq{} }
func (m *EmptyReq) String() string { return proto.CompactTextString(m) }
func (*EmptyReq) ProtoMessage()    {}
func (*EmptyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecb1e126f615f5dd, []int{10}
}

func (m *EmptyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyReq.Unmarshal(m, b)
}
func (m *EmptyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyReq.Marshal(b, m, deterministic)
}
func (m *EmptyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyReq.Merge(m, src)
}
func (m *EmptyReq) XXX_Size() int {
	return xxx_messageInfo_EmptyReq.Size(m)
}
func (m *EmptyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyReq.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyReq proto.InternalMessageInfo

type ParentProjectGroupInfo struct {
	ParentProjectGroupID   int32       `protobuf:"varint,1,opt,name=ParentProjectGroupID,proto3" json:"ParentProjectGroupID,omitempty"`
	ParentProjectGroupName string      `protobuf:"bytes,2,opt,name=ParentProjectGroupName,proto3" json:"ParentProjectGroupName,omitempty"`
	TestParentProject      *ParentItem `protobuf:"bytes,3,opt,name=TestParentProject,proto3" json:"TestParentProject,omitempty"`
	ProParentProject       *ParentItem `protobuf:"bytes,4,opt,name=ProParentProject,proto3" json:"ProParentProject,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}    `json:"-"`
	XXX_unrecognized       []byte      `json:"-"`
	XXX_sizecache          int32       `json:"-"`
}

func (m *ParentProjectGroupInfo) Reset()         { *m = ParentProjectGroupInfo{} }
func (m *ParentProjectGroupInfo) String() string { return proto.CompactTextString(m) }
func (*ParentProjectGroupInfo) ProtoMessage()    {}
func (*ParentProjectGroupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecb1e126f615f5dd, []int{11}
}

func (m *ParentProjectGroupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParentProjectGroupInfo.Unmarshal(m, b)
}
func (m *ParentProjectGroupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParentProjectGroupInfo.Marshal(b, m, deterministic)
}
func (m *ParentProjectGroupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParentProjectGroupInfo.Merge(m, src)
}
func (m *ParentProjectGroupInfo) XXX_Size() int {
	return xxx_messageInfo_ParentProjectGroupInfo.Size(m)
}
func (m *ParentProjectGroupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ParentProjectGroupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ParentProjectGroupInfo proto.InternalMessageInfo

func (m *ParentProjectGroupInfo) GetParentProjectGroupID() int32 {
	if m != nil {
		return m.ParentProjectGroupID
	}
	return 0
}

func (m *ParentProjectGroupInfo) GetParentProjectGroupName() string {
	if m != nil {
		return m.ParentProjectGroupName
	}
	return ""
}

func (m *ParentProjectGroupInfo) GetTestParentProject() *ParentItem {
	if m != nil {
		return m.TestParentProject
	}
	return nil
}

func (m *ParentProjectGroupInfo) GetProParentProject() *ParentItem {
	if m != nil {
		return m.ProParentProject
	}
	return nil
}

type ParentList struct {
	ParentList           []*ParentItem `protobuf:"bytes,1,rep,name=ParentList,proto3" json:"ParentList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ParentList) Reset()         { *m = ParentList{} }
func (m *ParentList) String() string { return proto.CompactTextString(m) }
func (*ParentList) ProtoMessage()    {}
func (*ParentList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecb1e126f615f5dd, []int{12}
}

func (m *ParentList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParentList.Unmarshal(m, b)
}
func (m *ParentList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParentList.Marshal(b, m, deterministic)
}
func (m *ParentList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParentList.Merge(m, src)
}
func (m *ParentList) XXX_Size() int {
	return xxx_messageInfo_ParentList.Size(m)
}
func (m *ParentList) XXX_DiscardUnknown() {
	xxx_messageInfo_ParentList.DiscardUnknown(m)
}

var xxx_messageInfo_ParentList proto.InternalMessageInfo

func (m *ParentList) GetParentList() []*ParentItem {
	if m != nil {
		return m.ParentList
	}
	return nil
}

type ListParentProjectByTypeRequest struct {
	ParentProjectType    int32    `protobuf:"varint,1,opt,name=ParentProjectType,proto3" json:"ParentProjectType,omitempty"`
	EnvType              int32    `protobuf:"varint,2,opt,name=EnvType,proto3" json:"EnvType,omitempty"`
	UserID               int32    `protobuf:"varint,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	UserType             int32    `protobuf:"varint,4,opt,name=UserType,proto3" json:"UserType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListParentProjectByTypeRequest) Reset()         { *m = ListParentProjectByTypeRequest{} }
func (m *ListParentProjectByTypeRequest) String() string { return proto.CompactTextString(m) }
func (*ListParentProjectByTypeRequest) ProtoMessage()    {}
func (*ListParentProjectByTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecb1e126f615f5dd, []int{13}
}

func (m *ListParentProjectByTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListParentProjectByTypeRequest.Unmarshal(m, b)
}
func (m *ListParentProjectByTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListParentProjectByTypeRequest.Marshal(b, m, deterministic)
}
func (m *ListParentProjectByTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListParentProjectByTypeRequest.Merge(m, src)
}
func (m *ListParentProjectByTypeRequest) XXX_Size() int {
	return xxx_messageInfo_ListParentProjectByTypeRequest.Size(m)
}
func (m *ListParentProjectByTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListParentProjectByTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListParentProjectByTypeRequest proto.InternalMessageInfo

func (m *ListParentProjectByTypeRequest) GetParentProjectType() int32 {
	if m != nil {
		return m.ParentProjectType
	}
	return 0
}

func (m *ListParentProjectByTypeRequest) GetEnvType() int32 {
	if m != nil {
		return m.EnvType
	}
	return 0
}

func (m *ListParentProjectByTypeRequest) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *ListParentProjectByTypeRequest) GetUserType() int32 {
	if m != nil {
		return m.UserType
	}
	return 0
}

func init() {
	proto.RegisterType((*ParentIDList)(nil), "ParentIDList")
	proto.RegisterType((*FuzzyListParentReq)(nil), "FuzzyListParentReq")
	proto.RegisterType((*FuzzyListAuthorizeParentReq)(nil), "FuzzyListAuthorizeParentReq")
	proto.RegisterType((*FuzzyListParentGroupReq)(nil), "FuzzyListParentGroupReq")
	proto.RegisterType((*ParentGroupList)(nil), "ParentGroupList")
	proto.RegisterType((*ParentID)(nil), "ParentID")
	proto.RegisterType((*GroupID)(nil), "GroupID")
	proto.RegisterType((*GetParentByGroupReq)(nil), "GetParentByGroupReq")
	proto.RegisterType((*GetParentByGroupRes)(nil), "GetParentByGroupRes")
	proto.RegisterType((*ParentItem)(nil), "ParentItem")
	proto.RegisterType((*EmptyReq)(nil), "EmptyReq")
	proto.RegisterType((*ParentProjectGroupInfo)(nil), "ParentProjectGroupInfo")
	proto.RegisterType((*ParentList)(nil), "ParentList")
	proto.RegisterType((*ListParentProjectByTypeRequest)(nil), "ListParentProjectByTypeRequest")
}

func init() { proto.RegisterFile("namespace.proto", fileDescriptor_ecb1e126f615f5dd) }

var fileDescriptor_ecb1e126f615f5dd = []byte{
	// 1038 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0x8e, 0xe2, 0x24, 0xb5, 0x8f, 0x53, 0xe2, 0xac, 0x13, 0x5b, 0x71, 0x0b, 0x64, 0xc4, 0x30,
	0x64, 0x06, 0xaa, 0x74, 0x5c, 0xda, 0x3a, 0x25, 0xfd, 0x49, 0xaa, 0x60, 0x4c, 0x21, 0xe3, 0x68,
	0x9a, 0xde, 0xcb, 0xd2, 0xc6, 0x31, 0x44, 0x3f, 0xd6, 0x0f, 0x45, 0x79, 0x0c, 0xae, 0xb9, 0xe4,
	0x55, 0x78, 0x15, 0x9e, 0x81, 0x4b, 0x46, 0x2b, 0xc9, 0x96, 0x56, 0x2b, 0x8f, 0xe4, 0xdc, 0x70,
	0xe7, 0xdd, 0xb3, 0xdf, 0xf9, 0xfd, 0xce, 0x59, 0xad, 0x61, 0xcb, 0x50, 0x74, 0xec, 0x58, 0x8a,
	0x8a, 0x45, 0xcb, 0x36, 0x5d, 0xb3, 0xf3, 0xd5, 0x78, 0xe2, 0x5e, 0x7b, 0x23, 0x51, 0x35, 0xf5,
	0x43, 0x7d, 0xa2, 0xda, 0xe6, 0xe1, 0xd8, 0x7c, 0xa4, 0x58, 0x93, 0x43, 0x22, 0x3e, 0x54, 0xac,
	0x49, 0x78, 0x50, 0xe8, 0xc1, 0xe6, 0x50, 0xb1, 0xb1, 0xe1, 0x0e, 0xa4, 0x9f, 0x26, 0x8e, 0x8b,
	0x0e, 0x60, 0x2b, 0x5c, 0x0f, 0x6d, 0xf3, 0x17, 0xac, 0xba, 0x03, 0x89, 0xe7, 0xf6, 0x2b, 0x07,
	0xeb, 0x32, 0xbd, 0x2d, 0xfc, 0xc5, 0x01, 0xfa, 0xde, 0xbb, 0xbd, 0xf5, 0x03, 0x5c, 0x28, 0x94,
	0xf1, 0x14, 0x7d, 0x03, 0xdb, 0xa9, 0x93, 0xef, 0x7d, 0x0b, 0xf3, 0xdc, 0x3e, 0x77, 0xb0, 0x2e,
	0x67, 0x05, 0xa8, 0x0b, 0x3b, 0xa9, 0xcd, 0x33, 0xe3, 0x37, 0x02, 0x58, 0x25, 0x00, 0xa6, 0x2c,
	0x63, 0xe1, 0x5c, 0xd1, 0x31, 0x5f, 0xd9, 0xe7, 0x0e, 0x6a, 0x72, 0x56, 0x20, 0xfc, 0xcd, 0xc1,
	0x83, 0x99, 0x9b, 0x27, 0x9e, 0x7b, 0x6d, 0xda, 0x93, 0x5b, 0xfc, 0xbf, 0xf5, 0x17, 0xb5, 0x60,
	0xc3, 0x73, 0xb0, 0x3d, 0x90, 0xf8, 0x35, 0xa2, 0x33, 0x5a, 0x09, 0x17, 0xd0, 0xa6, 0xb2, 0xdd,
	0xb7, 0x4d, 0xcf, 0x0a, 0x42, 0x78, 0x06, 0xad, 0x94, 0x1e, 0x22, 0x20, 0x56, 0x38, 0x62, 0x25,
	0x47, 0x2a, 0xfc, 0x10, 0xd7, 0x9a, 0x6c, 0x91, 0xf2, 0x3f, 0x85, 0xda, 0x6c, 0x41, 0x0a, 0x5f,
	0xef, 0xb6, 0xc5, 0x2c, 0x7c, 0x60, 0x5c, 0x99, 0xf2, 0xfc, 0xa4, 0xf0, 0x2d, 0x54, 0x63, 0x16,
	0xb1, 0x19, 0xc4, 0xb1, 0x18, 0xf4, 0x05, 0xdc, 0x0b, 0xb5, 0x49, 0x88, 0x9f, 0xfd, 0x8c, 0x0e,
	0xc7, 0x4b, 0x61, 0x00, 0xcd, 0x3e, 0x8e, 0x22, 0x3e, 0xf5, 0x67, 0x31, 0xd3, 0x85, 0x48, 0xa3,
	0x99, 0x32, 0xe1, 0x23, 0x4b, 0x95, 0x83, 0x1e, 0x43, 0xf3, 0x3d, 0x8e, 0x93, 0x4a, 0x3b, 0xcd,
	0x12, 0x21, 0x11, 0xd0, 0xd0, 0x36, 0x69, 0x40, 0xc8, 0x01, 0x86, 0x44, 0xf8, 0xa7, 0x02, 0x10,
	0xe5, 0xc7, 0xc5, 0x7a, 0xf1, 0x0c, 0xb1, 0xa9, 0xb3, 0x9a, 0x47, 0x1d, 0x3a, 0x27, 0xef, 0x7a,
	0x4e, 0x82, 0x6b, 0x4c, 0x19, 0x9b, 0xfe, 0x6b, 0x79, 0xf4, 0x4f, 0x94, 0x69, 0x3d, 0x55, 0x26,
	0xd4, 0x80, 0xca, 0xdb, 0xe1, 0x25, 0xbf, 0x41, 0x4c, 0x05, 0x3f, 0x03, 0x22, 0xff, 0x8c, 0x75,
	0xd3, 0xf6, 0xf9, 0x7b, 0x64, 0x33, 0x5a, 0x21, 0x04, 0x6b, 0x43, 0x53, 0x73, 0xf8, 0x2a, 0xd9,
	0x25, 0xbf, 0xd1, 0xc3, 0x88, 0x76, 0xc4, 0xdd, 0x1a, 0x11, 0xcc, 0x37, 0x02, 0xab, 0x71, 0x9f,
	0x41, 0x68, 0x35, 0x6e, 0x2d, 0x01, 0x36, 0xc9, 0xb1, 0x38, 0xd2, 0x3a, 0x81, 0xa6, 0xf6, 0x72,
	0x99, 0xb2, 0x99, 0xcf, 0x94, 0x05, 0x1d, 0x75, 0x7f, 0x61, 0x47, 0x01, 0x54, 0xcf, 0x74, 0xcb,
	0xf5, 0x65, 0x3c, 0x15, 0xfe, 0xe5, 0x58, 0x4a, 0x82, 0xce, 0x59, 0x86, 0xbc, 0x0b, 0x5c, 0x5a,
	0x5d, 0xe4, 0x12, 0x3a, 0x82, 0xed, 0x0c, 0x85, 0x09, 0x23, 0xea, 0xdd, 0xba, 0x38, 0x27, 0xa5,
	0x9c, 0x3d, 0x85, 0x9e, 0x43, 0x83, 0x26, 0x33, 0xa1, 0x06, 0x85, 0xcc, 0x1c, 0x12, 0x8e, 0x62,
	0xba, 0x93, 0x99, 0xf2, 0x75, 0x72, 0x15, 0x0d, 0x95, 0x94, 0x82, 0x84, 0x58, 0xf8, 0x93, 0x83,
	0xcf, 0xe6, 0x23, 0x2e, 0x52, 0x78, 0xea, 0x07, 0xd5, 0x96, 0xf1, 0xd4, 0xc3, 0x8e, 0x5b, 0x72,
	0x62, 0x27, 0xc8, 0xb3, 0x9a, 0x26, 0x4f, 0x0b, 0x36, 0x2e, 0xc3, 0x49, 0x5b, 0x09, 0x27, 0x6d,
	0xb8, 0x42, 0x1d, 0xa8, 0x06, 0xbf, 0x12, 0x9d, 0x30, 0x5b, 0x77, 0xff, 0x68, 0x42, 0xed, 0x3c,
	0xbe, 0x6b, 0x83, 0x04, 0x9d, 0xe3, 0x8f, 0x16, 0xb1, 0x69, 0x45, 0x49, 0xdb, 0x12, 0xc7, 0xa6,
	0x18, 0xdc, 0xaf, 0x91, 0xbb, 0x9d, 0xc6, 0x7c, 0xc3, 0xb1, 0x4c, 0xc3, 0xc1, 0xc2, 0x0a, 0xea,
	0xc5, 0x21, 0x44, 0xa8, 0x9b, 0x20, 0x4f, 0x85, 0x90, 0x2f, 0xa0, 0x99, 0x41, 0x6a, 0xa3, 0xc2,
	0xd8, 0x4b, 0x4b, 0x53, 0x5c, 0xbc, 0x84, 0xc7, 0xcf, 0xa1, 0x21, 0xe1, 0x9b, 0x25, 0x80, 0x47,
	0x80, 0x2e, 0x3c, 0x6c, 0xfb, 0x4b, 0x40, 0x5f, 0x03, 0xff, 0xd6, 0xf4, 0x0c, 0x37, 0x05, 0x55,
	0x4d, 0xe3, 0x6a, 0x32, 0x2e, 0xa6, 0xe0, 0x0d, 0xec, 0x05, 0x5c, 0x4a, 0xe1, 0x47, 0xbe, 0x61,
	0x6a, 0x78, 0xa2, 0x15, 0xd3, 0xf0, 0x12, 0x5a, 0x67, 0xbf, 0xd3, 0x2a, 0x82, 0x8f, 0xad, 0x62,
	0xf0, 0x2f, 0xa1, 0xd6, 0xc7, 0x11, 0x18, 0xd5, 0x62, 0xce, 0x4b, 0x9d, 0x24, 0xfd, 0x85, 0x15,
	0xf4, 0x08, 0xd0, 0xdc, 0xcf, 0x99, 0x83, 0x55, 0x31, 0xea, 0xfd, 0xd9, 0x71, 0xd2, 0x21, 0x2b,
	0x68, 0x00, 0xed, 0x9c, 0x16, 0x41, 0x9f, 0x8b, 0x8b, 0x9b, 0x87, 0x56, 0xf5, 0x14, 0x3e, 0x39,
	0xd1, 0x34, 0x47, 0xb9, 0xc2, 0xba, 0x62, 0x28, 0x63, 0x6c, 0x17, 0x8b, 0xeb, 0x18, 0x76, 0x89,
	0x6f, 0xd3, 0xa0, 0xb2, 0xa5, 0xd1, 0xdf, 0xc1, 0xce, 0x05, 0x05, 0x1c, 0xf9, 0x45, 0x2b, 0xd2,
	0x83, 0xed, 0x90, 0xc4, 0xa5, 0xcd, 0xf6, 0x60, 0x5b, 0xc2, 0x37, 0x78, 0x09, 0xe4, 0x63, 0xa8,
	0x9d, 0x68, 0x5a, 0x19, 0xe6, 0x3d, 0x81, 0xcd, 0xd0, 0x56, 0x49, 0x50, 0x18, 0x5a, 0x19, 0x50,
	0x17, 0xea, 0x24, 0x99, 0x65, 0x30, 0xcf, 0x60, 0x2b, 0x81, 0x29, 0x4e, 0xe7, 0x63, 0xd8, 0x3d,
	0xd1, 0xb4, 0x54, 0x2f, 0x8c, 0x03, 0x1a, 0x14, 0x6e, 0xe7, 0x30, 0x27, 0x77, 0x50, 0xc0, 0x98,
	0x5f, 0x25, 0x14, 0x48, 0xf0, 0x69, 0x9e, 0x07, 0xea, 0x35, 0x56, 0x7f, 0x2d, 0xa6, 0xe5, 0x15,
	0xb4, 0xb3, 0x13, 0xad, 0x84, 0x17, 0x2f, 0xa1, 0x95, 0x99, 0x4a, 0x25, 0xe0, 0x2f, 0x60, 0x4f,
	0xb6, 0xd4, 0x1b, 0xb6, 0x86, 0x9a, 0x18, 0x7f, 0x7f, 0x74, 0x1a, 0x22, 0xf5, 0x71, 0x1f, 0x9a,
	0xee, 0x63, 0xd7, 0xc5, 0x14, 0xb6, 0x68, 0xef, 0x1d, 0xc3, 0x6e, 0x70, 0x13, 0x5a, 0xcb, 0x5d,
	0x5d, 0xaf, 0x81, 0x7f, 0xd7, 0x73, 0xbc, 0xe5, 0x15, 0xbc, 0x82, 0xf6, 0x07, 0xfd, 0x0e, 0xf8,
	0x37, 0xb0, 0x17, 0x38, 0x60, 0x78, 0x0e, 0x5e, 0x3e, 0x84, 0x0f, 0xfa, 0x5d, 0x14, 0x9c, 0x02,
	0xa2, 0x9f, 0x20, 0x03, 0x09, 0xed, 0x88, 0x8c, 0x27, 0x4e, 0x87, 0xb5, 0xeb, 0x90, 0x30, 0x1e,
	0xc8, 0x96, 0xda, 0xc7, 0xf3, 0xca, 0x9e, 0xfa, 0x89, 0xcf, 0xad, 0xfb, 0x62, 0xf2, 0x41, 0xcf,
	0xa4, 0x41, 0x0f, 0x90, 0x6c, 0xa9, 0xd4, 0x73, 0x12, 0x35, 0xc5, 0xec, 0x73, 0x9e, 0xbe, 0x2f,
	0xfa, 0xd0, 0xce, 0x22, 0x89, 0x6a, 0xc4, 0x8b, 0x39, 0xef, 0x53, 0xa6, 0x0b, 0x3f, 0x92, 0x20,
	0xf2, 0x1e, 0xe6, 0xe8, 0xa1, 0xb8, 0xe0, 0xcd, 0x4e, 0x39, 0x35, 0xda, 0x20, 0x7f, 0x65, 0x3c,
	0xf9, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x7d, 0xc2, 0xde, 0x06, 0x11, 0x00, 0x00,
}
