// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manageJobList.proto

package manageJobList

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type JobProcessReportRequest struct {
	JobId                int32    `protobuf:"varint,1,opt,name=JobId,proto3" json:"JobId,omitempty"`
	State                int32    `protobuf:"varint,2,opt,name=State,proto3" json:"State,omitempty"`
	Log                  string   `protobuf:"bytes,3,opt,name=Log,proto3" json:"Log,omitempty"`
	Desc                 string   `protobuf:"bytes,4,opt,name=Desc,proto3" json:"Desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobProcessReportRequest) Reset()         { *m = JobProcessReportRequest{} }
func (m *JobProcessReportRequest) String() string { return proto.CompactTextString(m) }
func (*JobProcessReportRequest) ProtoMessage()    {}
func (*JobProcessReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9796e5b43a7ee4e2, []int{0}
}

func (m *JobProcessReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobProcessReportRequest.Unmarshal(m, b)
}
func (m *JobProcessReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobProcessReportRequest.Marshal(b, m, deterministic)
}
func (m *JobProcessReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobProcessReportRequest.Merge(m, src)
}
func (m *JobProcessReportRequest) XXX_Size() int {
	return xxx_messageInfo_JobProcessReportRequest.Size(m)
}
func (m *JobProcessReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobProcessReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobProcessReportRequest proto.InternalMessageInfo

func (m *JobProcessReportRequest) GetJobId() int32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *JobProcessReportRequest) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *JobProcessReportRequest) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func (m *JobProcessReportRequest) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type JobProcessReportResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobProcessReportResponse) Reset()         { *m = JobProcessReportResponse{} }
func (m *JobProcessReportResponse) String() string { return proto.CompactTextString(m) }
func (*JobProcessReportResponse) ProtoMessage()    {}
func (*JobProcessReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9796e5b43a7ee4e2, []int{1}
}

func (m *JobProcessReportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobProcessReportResponse.Unmarshal(m, b)
}
func (m *JobProcessReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobProcessReportResponse.Marshal(b, m, deterministic)
}
func (m *JobProcessReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobProcessReportResponse.Merge(m, src)
}
func (m *JobProcessReportResponse) XXX_Size() int {
	return xxx_messageInfo_JobProcessReportResponse.Size(m)
}
func (m *JobProcessReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobProcessReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobProcessReportResponse proto.InternalMessageInfo

func (m *JobProcessReportResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type ClusterNodeJobProcessReportRequest struct {
	JobId                int32    `protobuf:"varint,1,opt,name=JobId,proto3" json:"JobId,omitempty"`
	State                int32    `protobuf:"varint,2,opt,name=State,proto3" json:"State,omitempty"`
	Log                  string   `protobuf:"bytes,3,opt,name=Log,proto3" json:"Log,omitempty"`
	Desc                 string   `protobuf:"bytes,4,opt,name=Desc,proto3" json:"Desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterNodeJobProcessReportRequest) Reset()         { *m = ClusterNodeJobProcessReportRequest{} }
func (m *ClusterNodeJobProcessReportRequest) String() string { return proto.CompactTextString(m) }
func (*ClusterNodeJobProcessReportRequest) ProtoMessage()    {}
func (*ClusterNodeJobProcessReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9796e5b43a7ee4e2, []int{2}
}

func (m *ClusterNodeJobProcessReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterNodeJobProcessReportRequest.Unmarshal(m, b)
}
func (m *ClusterNodeJobProcessReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterNodeJobProcessReportRequest.Marshal(b, m, deterministic)
}
func (m *ClusterNodeJobProcessReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterNodeJobProcessReportRequest.Merge(m, src)
}
func (m *ClusterNodeJobProcessReportRequest) XXX_Size() int {
	return xxx_messageInfo_ClusterNodeJobProcessReportRequest.Size(m)
}
func (m *ClusterNodeJobProcessReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterNodeJobProcessReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterNodeJobProcessReportRequest proto.InternalMessageInfo

func (m *ClusterNodeJobProcessReportRequest) GetJobId() int32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *ClusterNodeJobProcessReportRequest) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *ClusterNodeJobProcessReportRequest) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func (m *ClusterNodeJobProcessReportRequest) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type ClusterNodeJobProcessReportResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterNodeJobProcessReportResponse) Reset()         { *m = ClusterNodeJobProcessReportResponse{} }
func (m *ClusterNodeJobProcessReportResponse) String() string { return proto.CompactTextString(m) }
func (*ClusterNodeJobProcessReportResponse) ProtoMessage()    {}
func (*ClusterNodeJobProcessReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9796e5b43a7ee4e2, []int{3}
}

func (m *ClusterNodeJobProcessReportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterNodeJobProcessReportResponse.Unmarshal(m, b)
}
func (m *ClusterNodeJobProcessReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterNodeJobProcessReportResponse.Marshal(b, m, deterministic)
}
func (m *ClusterNodeJobProcessReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterNodeJobProcessReportResponse.Merge(m, src)
}
func (m *ClusterNodeJobProcessReportResponse) XXX_Size() int {
	return xxx_messageInfo_ClusterNodeJobProcessReportResponse.Size(m)
}
func (m *ClusterNodeJobProcessReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterNodeJobProcessReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterNodeJobProcessReportResponse proto.InternalMessageInfo

func (m *ClusterNodeJobProcessReportResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*JobProcessReportRequest)(nil), "JobProcessReportRequest")
	proto.RegisterType((*JobProcessReportResponse)(nil), "JobProcessReportResponse")
	proto.RegisterType((*ClusterNodeJobProcessReportRequest)(nil), "ClusterNodeJobProcessReportRequest")
	proto.RegisterType((*ClusterNodeJobProcessReportResponse)(nil), "ClusterNodeJobProcessReportResponse")
}

func init() { proto.RegisterFile("manageJobList.proto", fileDescriptor_9796e5b43a7ee4e2) }

var fileDescriptor_9796e5b43a7ee4e2 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xce, 0x4d, 0xcc, 0x4b,
	0x4c, 0x4f, 0xf5, 0xca, 0x4f, 0xf2, 0xc9, 0x2c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57,
	0xca, 0xe6, 0x12, 0xf7, 0xca, 0x4f, 0x0a, 0x28, 0xca, 0x4f, 0x4e, 0x2d, 0x2e, 0x0e, 0x4a, 0x2d,
	0xc8, 0x2f, 0x2a, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe1, 0x62, 0xf5, 0xca,
	0x4f, 0xf2, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0x70, 0x40, 0xa2, 0xc1, 0x25,
	0x89, 0x25, 0xa9, 0x12, 0x4c, 0x10, 0x51, 0x30, 0x47, 0x48, 0x80, 0x8b, 0xd9, 0x27, 0x3f, 0x5d,
	0x82, 0x59, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc4, 0x14, 0x12, 0xe2, 0x62, 0x71, 0x49, 0x2d, 0x4e,
	0x96, 0x60, 0x01, 0x0b, 0x81, 0xd9, 0x4a, 0x5a, 0x5c, 0x12, 0x98, 0x96, 0x15, 0x17, 0xe4, 0xe7,
	0x15, 0xa7, 0x0a, 0xf1, 0x71, 0x31, 0xf9, 0x67, 0x83, 0xad, 0xe2, 0x08, 0x62, 0xf2, 0xcf, 0x56,
	0x2a, 0xe3, 0x52, 0x72, 0xce, 0x29, 0x2d, 0x2e, 0x49, 0x2d, 0xf2, 0xcb, 0x4f, 0x49, 0xa5, 0x9f,
	0x1b, 0x4d, 0xb9, 0x94, 0xf1, 0xda, 0x8b, 0xdd, 0xb9, 0x46, 0xc7, 0x18, 0xb9, 0x78, 0x7d, 0x91,
	0xc3, 0x57, 0xc8, 0x93, 0x4b, 0x00, 0x5d, 0xb7, 0x90, 0x84, 0x1e, 0x0e, 0x8f, 0x48, 0x49, 0xea,
	0xe1, 0xb2, 0x4a, 0x89, 0x41, 0x28, 0x8b, 0x4b, 0x1a, 0x8f, 0x9b, 0x84, 0x94, 0xf5, 0x08, 0x87,
	0x94, 0x94, 0x8a, 0x1e, 0x11, 0xde, 0x52, 0x62, 0x48, 0x62, 0x03, 0xa7, 0x0b, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x15, 0x26, 0x49, 0x9b, 0x2e, 0x02, 0x00, 0x00,
}
