// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ansible.proto

package ansible

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Host struct {
	Type                 string   `protobuf:"bytes,6,opt,name=Type,proto3" json:"Type,omitempty"`
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=Host,proto3" json:"Host,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=Port,proto3" json:"Port,omitempty"`
	User                 string   `protobuf:"bytes,4,opt,name=User,proto3" json:"User,omitempty"`
	Pass                 string   `protobuf:"bytes,5,opt,name=Pass,proto3" json:"Pass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Host) Reset()         { *m = Host{} }
func (m *Host) String() string { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()    {}
func (*Host) Descriptor() ([]byte, []int) {
	return fileDescriptor_ansible_0f99f01f165d835f, []int{0}
}
func (m *Host) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Host.Unmarshal(m, b)
}
func (m *Host) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Host.Marshal(b, m, deterministic)
}
func (dst *Host) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Host.Merge(dst, src)
}
func (m *Host) XXX_Size() int {
	return xxx_messageInfo_Host.Size(m)
}
func (m *Host) XXX_DiscardUnknown() {
	xxx_messageInfo_Host.DiscardUnknown(m)
}

var xxx_messageInfo_Host proto.InternalMessageInfo

func (m *Host) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Host) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Host) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Host) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *Host) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Host) GetPass() string {
	if m != nil {
		return m.Pass
	}
	return ""
}

type Config struct {
	ConfigPath           string   `protobuf:"bytes,1,opt,name=ConfigPath,proto3" json:"ConfigPath,omitempty"`
	ConfigEtcdPattern    string   `protobuf:"bytes,2,opt,name=ConfigEtcdPattern,proto3" json:"ConfigEtcdPattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_ansible_0f99f01f165d835f, []int{1}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetConfigPath() string {
	if m != nil {
		return m.ConfigPath
	}
	return ""
}

func (m *Config) GetConfigEtcdPattern() string {
	if m != nil {
		return m.ConfigEtcdPattern
	}
	return ""
}

type ConfigList struct {
	Items                []*Config `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ConfigList) Reset()         { *m = ConfigList{} }
func (m *ConfigList) String() string { return proto.CompactTextString(m) }
func (*ConfigList) ProtoMessage()    {}
func (*ConfigList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ansible_0f99f01f165d835f, []int{2}
}
func (m *ConfigList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigList.Unmarshal(m, b)
}
func (m *ConfigList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigList.Marshal(b, m, deterministic)
}
func (dst *ConfigList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigList.Merge(dst, src)
}
func (m *ConfigList) XXX_Size() int {
	return xxx_messageInfo_ConfigList.Size(m)
}
func (m *ConfigList) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigList.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigList proto.InternalMessageInfo

func (m *ConfigList) GetItems() []*Config {
	if m != nil {
		return m.Items
	}
	return nil
}

type HostList struct {
	Items                []*Host  `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostList) Reset()         { *m = HostList{} }
func (m *HostList) String() string { return proto.CompactTextString(m) }
func (*HostList) ProtoMessage()    {}
func (*HostList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ansible_0f99f01f165d835f, []int{3}
}
func (m *HostList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostList.Unmarshal(m, b)
}
func (m *HostList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostList.Marshal(b, m, deterministic)
}
func (dst *HostList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostList.Merge(dst, src)
}
func (m *HostList) XXX_Size() int {
	return xxx_messageInfo_HostList.Size(m)
}
func (m *HostList) XXX_DiscardUnknown() {
	xxx_messageInfo_HostList.DiscardUnknown(m)
}

var xxx_messageInfo_HostList proto.InternalMessageInfo

func (m *HostList) GetItems() []*Host {
	if m != nil {
		return m.Items
	}
	return nil
}

type Git struct {
	User                 string   `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Pass                 string   `protobuf:"bytes,2,opt,name=Pass,proto3" json:"Pass,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=Url,proto3" json:"Url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Git) Reset()         { *m = Git{} }
func (m *Git) String() string { return proto.CompactTextString(m) }
func (*Git) ProtoMessage()    {}
func (*Git) Descriptor() ([]byte, []int) {
	return fileDescriptor_ansible_0f99f01f165d835f, []int{4}
}
func (m *Git) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Git.Unmarshal(m, b)
}
func (m *Git) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Git.Marshal(b, m, deterministic)
}
func (dst *Git) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Git.Merge(dst, src)
}
func (m *Git) XXX_Size() int {
	return xxx_messageInfo_Git.Size(m)
}
func (m *Git) XXX_DiscardUnknown() {
	xxx_messageInfo_Git.DiscardUnknown(m)
}

var xxx_messageInfo_Git proto.InternalMessageInfo

func (m *Git) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Git) GetPass() string {
	if m != nil {
		return m.Pass
	}
	return ""
}

func (m *Git) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Role struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Git                  *Git     `protobuf:"bytes,2,opt,name=Git,proto3" json:"Git,omitempty"`
	BranchOrTag          string   `protobuf:"bytes,3,opt,name=BranchOrTag,proto3" json:"BranchOrTag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_ansible_0f99f01f165d835f, []int{5}
}
func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (dst *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(dst, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetGit() *Git {
	if m != nil {
		return m.Git
	}
	return nil
}

func (m *Role) GetBranchOrTag() string {
	if m != nil {
		return m.BranchOrTag
	}
	return ""
}

type RoleList struct {
	Items                []*Role  `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleList) Reset()         { *m = RoleList{} }
func (m *RoleList) String() string { return proto.CompactTextString(m) }
func (*RoleList) ProtoMessage()    {}
func (*RoleList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ansible_0f99f01f165d835f, []int{6}
}
func (m *RoleList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleList.Unmarshal(m, b)
}
func (m *RoleList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleList.Marshal(b, m, deterministic)
}
func (dst *RoleList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleList.Merge(dst, src)
}
func (m *RoleList) XXX_Size() int {
	return xxx_messageInfo_RoleList.Size(m)
}
func (m *RoleList) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleList.DiscardUnknown(m)
}

var xxx_messageInfo_RoleList proto.InternalMessageInfo

func (m *RoleList) GetItems() []*Role {
	if m != nil {
		return m.Items
	}
	return nil
}

type Tag struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_ansible_0f99f01f165d835f, []int{7}
}
func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (dst *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(dst, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TagList struct {
	Items                []*Tag   `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagList) Reset()         { *m = TagList{} }
func (m *TagList) String() string { return proto.CompactTextString(m) }
func (*TagList) ProtoMessage()    {}
func (*TagList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ansible_0f99f01f165d835f, []int{8}
}
func (m *TagList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagList.Unmarshal(m, b)
}
func (m *TagList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagList.Marshal(b, m, deterministic)
}
func (dst *TagList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagList.Merge(dst, src)
}
func (m *TagList) XXX_Size() int {
	return xxx_messageInfo_TagList.Size(m)
}
func (m *TagList) XXX_DiscardUnknown() {
	xxx_messageInfo_TagList.DiscardUnknown(m)
}

var xxx_messageInfo_TagList proto.InternalMessageInfo

func (m *TagList) GetItems() []*Tag {
	if m != nil {
		return m.Items
	}
	return nil
}

type VarList struct {
	// map<key, value>
	// key: the key off values
	Items                map[string]string `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *VarList) Reset()         { *m = VarList{} }
func (m *VarList) String() string { return proto.CompactTextString(m) }
func (*VarList) ProtoMessage()    {}
func (*VarList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ansible_0f99f01f165d835f, []int{9}
}
func (m *VarList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VarList.Unmarshal(m, b)
}
func (m *VarList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VarList.Marshal(b, m, deterministic)
}
func (dst *VarList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VarList.Merge(dst, src)
}
func (m *VarList) XXX_Size() int {
	return xxx_messageInfo_VarList.Size(m)
}
func (m *VarList) XXX_DiscardUnknown() {
	xxx_messageInfo_VarList.DiscardUnknown(m)
}

var xxx_messageInfo_VarList proto.InternalMessageInfo

func (m *VarList) GetItems() map[string]string {
	if m != nil {
		return m.Items
	}
	return nil
}

type PlayBook struct {
	Id                   string      `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	RoleList             *RoleList   `protobuf:"bytes,2,opt,name=RoleList,proto3" json:"RoleList,omitempty"`
	HostList             *HostList   `protobuf:"bytes,3,opt,name=HostList,proto3" json:"HostList,omitempty"`
	VarList              *VarList    `protobuf:"bytes,4,opt,name=VarList,proto3" json:"VarList,omitempty"`
	ConfigList           *ConfigList `protobuf:"bytes,5,opt,name=ConfigList,proto3" json:"ConfigList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PlayBook) Reset()         { *m = PlayBook{} }
func (m *PlayBook) String() string { return proto.CompactTextString(m) }
func (*PlayBook) ProtoMessage()    {}
func (*PlayBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_ansible_0f99f01f165d835f, []int{10}
}
func (m *PlayBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayBook.Unmarshal(m, b)
}
func (m *PlayBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayBook.Marshal(b, m, deterministic)
}
func (dst *PlayBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayBook.Merge(dst, src)
}
func (m *PlayBook) XXX_Size() int {
	return xxx_messageInfo_PlayBook.Size(m)
}
func (m *PlayBook) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayBook.DiscardUnknown(m)
}

var xxx_messageInfo_PlayBook proto.InternalMessageInfo

func (m *PlayBook) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PlayBook) GetRoleList() *RoleList {
	if m != nil {
		return m.RoleList
	}
	return nil
}

func (m *PlayBook) GetHostList() *HostList {
	if m != nil {
		return m.HostList
	}
	return nil
}

func (m *PlayBook) GetVarList() *VarList {
	if m != nil {
		return m.VarList
	}
	return nil
}

func (m *PlayBook) GetConfigList() *ConfigList {
	if m != nil {
		return m.ConfigList
	}
	return nil
}

type LogRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	LogString            string   `protobuf:"bytes,2,opt,name=LogString,proto3" json:"LogString,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogRequest) Reset()         { *m = LogRequest{} }
func (m *LogRequest) String() string { return proto.CompactTextString(m) }
func (*LogRequest) ProtoMessage()    {}
func (*LogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ansible_0f99f01f165d835f, []int{11}
}
func (m *LogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogRequest.Unmarshal(m, b)
}
func (m *LogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogRequest.Marshal(b, m, deterministic)
}
func (dst *LogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogRequest.Merge(dst, src)
}
func (m *LogRequest) XXX_Size() int {
	return xxx_messageInfo_LogRequest.Size(m)
}
func (m *LogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogRequest proto.InternalMessageInfo

func (m *LogRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *LogRequest) GetLogString() string {
	if m != nil {
		return m.LogString
	}
	return ""
}

func (m *LogRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type Response struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ansible_0f99f01f165d835f, []int{12}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type StatusResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ansible_0f99f01f165d835f, []int{13}
}
func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (dst *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(dst, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type K8SScaleNodeRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Masters              []*Host  `protobuf:"bytes,2,rep,name=Masters,proto3" json:"Masters,omitempty"`
	Nodes                []*Host  `protobuf:"bytes,3,rep,name=Nodes,proto3" json:"Nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *K8SScaleNodeRequest) Reset()         { *m = K8SScaleNodeRequest{} }
func (m *K8SScaleNodeRequest) String() string { return proto.CompactTextString(m) }
func (*K8SScaleNodeRequest) ProtoMessage()    {}
func (*K8SScaleNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ansible_0f99f01f165d835f, []int{14}
}
func (m *K8SScaleNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_K8SScaleNodeRequest.Unmarshal(m, b)
}
func (m *K8SScaleNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_K8SScaleNodeRequest.Marshal(b, m, deterministic)
}
func (dst *K8SScaleNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_K8SScaleNodeRequest.Merge(dst, src)
}
func (m *K8SScaleNodeRequest) XXX_Size() int {
	return xxx_messageInfo_K8SScaleNodeRequest.Size(m)
}
func (m *K8SScaleNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_K8SScaleNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_K8SScaleNodeRequest proto.InternalMessageInfo

func (m *K8SScaleNodeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *K8SScaleNodeRequest) GetMasters() []*Host {
	if m != nil {
		return m.Masters
	}
	return nil
}

func (m *K8SScaleNodeRequest) GetNodes() []*Host {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type K8SDeleteNodeRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Masters              []*Host  `protobuf:"bytes,2,rep,name=Masters,proto3" json:"Masters,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *K8SDeleteNodeRequest) Reset()         { *m = K8SDeleteNodeRequest{} }
func (m *K8SDeleteNodeRequest) String() string { return proto.CompactTextString(m) }
func (*K8SDeleteNodeRequest) ProtoMessage()    {}
func (*K8SDeleteNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ansible_0f99f01f165d835f, []int{15}
}
func (m *K8SDeleteNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_K8SDeleteNodeRequest.Unmarshal(m, b)
}
func (m *K8SDeleteNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_K8SDeleteNodeRequest.Marshal(b, m, deterministic)
}
func (dst *K8SDeleteNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_K8SDeleteNodeRequest.Merge(dst, src)
}
func (m *K8SDeleteNodeRequest) XXX_Size() int {
	return xxx_messageInfo_K8SDeleteNodeRequest.Size(m)
}
func (m *K8SDeleteNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_K8SDeleteNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_K8SDeleteNodeRequest proto.InternalMessageInfo

func (m *K8SDeleteNodeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *K8SDeleteNodeRequest) GetMasters() []*Host {
	if m != nil {
		return m.Masters
	}
	return nil
}

func (m *K8SDeleteNodeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Host)(nil), "Host")
	proto.RegisterType((*Config)(nil), "Config")
	proto.RegisterType((*ConfigList)(nil), "ConfigList")
	proto.RegisterType((*HostList)(nil), "HostList")
	proto.RegisterType((*Git)(nil), "Git")
	proto.RegisterType((*Role)(nil), "Role")
	proto.RegisterType((*RoleList)(nil), "RoleList")
	proto.RegisterType((*Tag)(nil), "Tag")
	proto.RegisterType((*TagList)(nil), "TagList")
	proto.RegisterType((*VarList)(nil), "VarList")
	proto.RegisterMapType((map[string]string)(nil), "VarList.ItemsEntry")
	proto.RegisterType((*PlayBook)(nil), "PlayBook")
	proto.RegisterType((*LogRequest)(nil), "LogRequest")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*StatusResponse)(nil), "StatusResponse")
	proto.RegisterType((*K8SScaleNodeRequest)(nil), "K8SScaleNodeRequest")
	proto.RegisterType((*K8SDeleteNodeRequest)(nil), "K8SDeleteNodeRequest")
}

func init() { proto.RegisterFile("ansible.proto", fileDescriptor_ansible_0f99f01f165d835f) }

var fileDescriptor_ansible_0f99f01f165d835f = []byte{
	// 681 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x55, 0x9b, 0xf4, 0xeb, 0x86, 0x0d, 0xf0, 0xc6, 0x14, 0xca, 0x3e, 0xaa, 0x88, 0x69, 0x43,
	0x20, 0x23, 0xca, 0x4b, 0xc5, 0x0b, 0x62, 0xeb, 0x34, 0xa6, 0x96, 0x51, 0x25, 0xdd, 0x5e, 0x78,
	0xf2, 0x5a, 0x93, 0x55, 0xcd, 0xe2, 0x12, 0xbb, 0x48, 0x7d, 0xe1, 0x97, 0xf0, 0x47, 0xf8, 0x77,
	0xc8, 0x8e, 0x13, 0xa7, 0x5b, 0xcb, 0x0b, 0x6f, 0xd7, 0xe7, 0x1c, 0x5f, 0xdf, 0x7b, 0xee, 0x6d,
	0x0a, 0x1b, 0x24, 0xe6, 0x93, 0x9b, 0x88, 0xe2, 0x59, 0xc2, 0x04, 0xf3, 0x7e, 0x81, 0xfd, 0x99,
	0x71, 0x81, 0x10, 0xd8, 0xc3, 0xc5, 0x8c, 0xba, 0xd5, 0x56, 0xe9, 0xb8, 0xe1, 0xab, 0x58, 0x62,
	0x97, 0xe4, 0x8e, 0xba, 0xa5, 0x14, 0x93, 0xb1, 0xc4, 0xa4, 0xde, 0x2d, 0xa7, 0x58, 0x76, 0x77,
	0xc0, 0x12, 0xe1, 0x5a, 0x29, 0x26, 0x63, 0x89, 0x5d, 0x71, 0x9a, 0xb8, 0x76, 0x8a, 0xc9, 0x58,
	0xe9, 0x08, 0xe7, 0x6e, 0x45, 0xeb, 0x08, 0xe7, 0xde, 0x35, 0x54, 0x4f, 0x59, 0xfc, 0x7d, 0x12,
	0xa2, 0x7d, 0x80, 0x34, 0x1a, 0x10, 0x71, 0xab, 0xdf, 0x2c, 0x20, 0xe8, 0x0d, 0x3c, 0x4d, 0x4f,
	0x67, 0x62, 0x34, 0x1e, 0x10, 0x21, 0x68, 0x12, 0xeb, 0x32, 0x1e, 0x12, 0xde, 0xeb, 0x2c, 0x5b,
	0x7f, 0xc2, 0x05, 0xda, 0x83, 0xca, 0x85, 0xa0, 0x77, 0xdc, 0x2d, 0xb5, 0xac, 0x63, 0xa7, 0x5d,
	0xc3, 0x29, 0xe7, 0xa7, 0xa8, 0x77, 0x04, 0x75, 0xd9, 0x88, 0x92, 0xbe, 0x58, 0x96, 0x56, 0xb0,
	0x64, 0x32, 0xe1, 0x47, 0xb0, 0xce, 0x27, 0xa6, 0xb9, 0xd2, 0x8a, 0xe6, 0xca, 0xa6, 0x39, 0xf4,
	0x04, 0xac, 0xab, 0x24, 0xd2, 0xbe, 0xc8, 0xd0, 0x1b, 0x82, 0xed, 0xb3, 0x68, 0xb5, 0xb5, 0x3b,
	0x2a, 0xb9, 0x4a, 0xe0, 0xb4, 0x6d, 0x7c, 0x3e, 0x11, 0xbe, 0x7a, 0xad, 0x05, 0xce, 0x49, 0x42,
	0xe2, 0xd1, 0xed, 0xd7, 0x64, 0x48, 0x42, 0x9d, 0xad, 0x08, 0xc9, 0xfa, 0x65, 0xd6, 0xd5, 0xf5,
	0x4b, 0x26, 0xab, 0xff, 0x39, 0x58, 0x43, 0x12, 0xae, 0x7a, 0xdd, 0x3b, 0x84, 0xda, 0x90, 0xa4,
	0x6e, 0x35, 0x97, 0x53, 0xd8, 0x78, 0x48, 0x72, 0xab, 0x62, 0xa8, 0x5d, 0x93, 0x44, 0xc9, 0x5e,
	0x2d, 0xcb, 0xb6, 0xb0, 0x26, 0xb0, 0x42, 0xcf, 0x62, 0x91, 0x2c, 0xf4, 0xad, 0x66, 0x07, 0xc0,
	0x80, 0xd2, 0x96, 0x29, 0x5d, 0xe8, 0xd7, 0x65, 0x88, 0xb6, 0xa1, 0xf2, 0x93, 0x44, 0x73, 0xaa,
	0xdd, 0x4b, 0x0f, 0x1f, 0xca, 0x9d, 0x92, 0xf7, 0xa7, 0x04, 0xf5, 0x41, 0x44, 0x16, 0x27, 0x8c,
	0x4d, 0xd1, 0x26, 0x94, 0x2f, 0xc6, 0xfa, 0x5e, 0xf9, 0x62, 0x8c, 0x0e, 0x4d, 0xdf, 0xda, 0xb6,
	0x06, 0xce, 0x00, 0xdf, 0x58, 0x72, 0x68, 0xc6, 0xab, 0xdc, 0x93, 0xb2, 0x0c, 0xf0, 0xcd, 0xe4,
	0xbd, 0xbc, 0x35, 0xb5, 0xb5, 0x4e, 0xbb, 0x9e, 0x75, 0xe4, 0xe7, 0x3d, 0x2f, 0xad, 0x95, 0x5a,
	0x64, 0xa7, 0xed, 0x60, 0x03, 0xf9, 0x05, 0xda, 0xf3, 0x01, 0xfa, 0x2c, 0xf4, 0xe9, 0x8f, 0x39,
	0xe5, 0x42, 0x15, 0xdf, 0xcd, 0x8b, 0xef, 0xa2, 0x5d, 0x68, 0xf4, 0x59, 0x18, 0x88, 0x64, 0x12,
	0x87, 0xba, 0x6f, 0x03, 0xa0, 0x1d, 0xa8, 0x06, 0x82, 0x88, 0x39, 0xd7, 0xf3, 0xd6, 0x27, 0xaf,
	0x09, 0x75, 0x9f, 0xf2, 0x19, 0x8b, 0x39, 0xbd, 0x9f, 0xd1, 0x3b, 0x86, 0xcd, 0x54, 0x95, 0x2b,
	0x4c, 0x16, 0xa9, 0xaa, 0xe7, 0x59, 0x46, 0xb0, 0xd5, 0xeb, 0x04, 0xc1, 0x88, 0x44, 0xf4, 0x92,
	0x8d, 0x69, 0xb1, 0xc4, 0xa2, 0xbf, 0x07, 0x50, 0xfb, 0x42, 0xb8, 0xa0, 0x89, 0x5c, 0xeb, 0xc2,
	0xaf, 0x21, 0x43, 0xe5, 0xb2, 0xc9, 0xfb, 0xb2, 0xc8, 0xe2, 0x8f, 0x45, 0x61, 0xde, 0x37, 0xd8,
	0xee, 0x75, 0x82, 0x2e, 0x8d, 0xa8, 0xf8, 0xbf, 0x57, 0xb2, 0x75, 0xb5, 0xcc, 0xba, 0xb6, 0x7f,
	0x5b, 0x50, 0xfb, 0x94, 0x7e, 0xc9, 0xd0, 0x3e, 0x54, 0xbb, 0x74, 0x16, 0xb1, 0x05, 0x6a, 0xe0,
	0x6c, 0x57, 0x9a, 0x0d, 0x9c, 0xbb, 0xa0, 0x78, 0x59, 0xc5, 0x1a, 0xbe, 0xa5, 0xd6, 0x28, 0x3a,
	0x21, 0xa3, 0xe9, 0x1a, 0xc5, 0x2e, 0xd8, 0x81, 0x60, 0xb3, 0x35, 0xec, 0x1e, 0x54, 0x02, 0x41,
	0x12, 0xb1, 0x86, 0x3e, 0x80, 0x9a, 0x4f, 0xf9, 0x3f, 0x04, 0x2f, 0xb3, 0x29, 0x15, 0xf9, 0xc7,
	0xf8, 0xde, 0x2c, 0x8f, 0xa0, 0x71, 0x7a, 0x4b, 0x47, 0x53, 0xf5, 0xc9, 0x35, 0x0b, 0xfc, 0x50,
	0xf8, 0x16, 0x1e, 0xf5, 0x78, 0x3e, 0x5b, 0x8e, 0xb6, 0xf1, 0x8a, 0x59, 0x17, 0xdf, 0x7f, 0x07,
	0x1b, 0x3d, 0x6e, 0xe6, 0xc4, 0xd1, 0x33, 0xbc, 0x6a, 0x70, 0xcb, 0x96, 0xda, 0x7d, 0x16, 0x72,
	0xe4, 0x60, 0xb3, 0xe1, 0x05, 0xfe, 0xa6, 0xaa, 0xfe, 0x5d, 0xde, 0xff, 0x0d, 0x00, 0x00, 0xff,
	0xff, 0x46, 0xd3, 0x06, 0x33, 0x6e, 0x06, 0x00, 0x00,
}
